force-app/main/default/objects/Account/recordTypes/Outbound.recordType-meta.xml
<RecordType>
    <fullName>Outbound</fullName>
    <active>true</active>
    <description>Accounts that are in outbound marketing (B2B Marketing)</description>
    <label>Outbound</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Demo_Date__c.field-meta.xml
<CustomField>
    <fullName>Demo_Date__c</fullName>
    <inlineHelpText>Datum, an dem die Demo mit dem Kund*in stattfindet.</inlineHelpText>
    <label>Demo Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hunter__c.field-meta.xml
<CustomField>
    <fullName>Hunter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name der Person, die die Demo hält.</inlineHelpText>
    <label>Demo Hunter</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Head of</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Large</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Small</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Large VP</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Enterprise</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Agency</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>System</value>
        </filterItems>
        <infoMessage>Make sure to choose someone from the German Customer Acquisition team!</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Currently_in_Contact__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Currently_in_Contact__c</fullName>
    <description>Set the Timestamp when Opportunity is in Stage Currently in Contact</description>
    <inlineHelpText>Timestamp when Opportunity was in Stage Currently in Contact</inlineHelpText>
    <label>Timestamp Currently in Contact</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Currently_in_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Currently_in_Contact_Time__c</fullName>
    <description>RO-1473</description>
    <label>Timestamp Currently in Contact-Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Demo_confirmed__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Demo_confirmed__c</fullName>
    <description>Set the Timestamp when Opportunity is in Stage Confirmed</description>
    <inlineHelpText>Timestamp when Opportunity was in Stage Confirmed</inlineHelpText>
    <label>Timestamp Demo confirmed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Demo_Held__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Demo_Held__c</fullName>
    <description>RO-281 Tracks if the Demo took place. Populates by flow in 1 day after the Event&apos;s Start Time and if the Event was not cancelled.</description>
    <label>Timestamp Demo Held</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Demo_Held_Time__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Demo_Held_Time__c</fullName>
    <description>RO-1473</description>
    <label>Timestamp Demo Held-Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Demo_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Demo_Scheduled__c</fullName>
    <description>1st time when Opportunity was in Stage Demo</description>
    <inlineHelpText>1st time when Opportunity was in Stage Demo</inlineHelpText>
    <label>Timestamp Demo Scheduled</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Not_reached_yet__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Not_reached_yet__c</fullName>
    <description>Set the Timestamp when Opportunity is in Stage Not reached yet</description>
    <inlineHelpText>Timestamp when Opportunity was in Stage Not reached yet</inlineHelpText>
    <label>Timestamp Not reached yet</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Not_reached_yet_time__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Not_reached_yet_time__c</fullName>
    <description>RO-1473</description>
    <label>Timestamp Not reached yet-time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Qualified_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Qualified_Prospect__c</fullName>
    <description>Set the Timestamp when Opportunity is in Stage Qualified Prospect</description>
    <inlineHelpText>Timestamp when Opportunity was in Stage Qualified Prospect</inlineHelpText>
    <label>Timestamp Qualified Prospect</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Qualified_Prospect_Time__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Qualified_Prospect_Time__c</fullName>
    <description>RO-1473</description>
    <label>Timestamp Qualified Prospect-Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Inbound.recordType-meta.xml
<RecordType>
    <fullName>Inbound</fullName>
    <active>false</active>
    <businessProcess>Inbound</businessProcess>
    <description>Legacy - Inbound sales process for SMB pilot business</description>
    <label>Inbound</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/LocalDemoHeldUpdate.cls
/*
 *      @author Lisa Müller
 *      @date   25-Jul-2023
 *      @description   RO-1620 Class to perform update of Demo Held Timestamp of lost Local opps 
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Lisa Müller					11.09.2023				Populate previous timestamps RO-1674
 * 
 */

public with sharing class LocalDemoHeldUpdate {
    public static void UpdateDemoFields(List<Opportunity> oppList){
        
        // get opp & account IDs & maps for query
        Set<Id> oppIds = new Set<Id>();
        Set<Id> accIds = new Set<Id>();
        Map<Id, Id> accToOppMap = new Map<Id, Id>();
        Map<Id, Id> accToOppOwnerMap = new Map<Id, Id>();
        Map<Id, datetime> accToOppCreatedDateMap = new Map<Id, datetime>();
        for(Opportunity opp: oppList){
            oppIds.add(opp.Id);
            accIds.add(opp.AccountId);
            accToOppMap.put(opp.AccountId, opp.Id);
            accToOppOwnerMap.put(opp.AccountId, opp.OwnerId);
            accToOppCreatedDateMap.put(opp.AccountId, opp.CreatedDate);
        }
        
        // get task records by query         
        Task[] relevantCalls = [SELECT Id, OwnerId, CreatedDate, WhatId FROM Task WHERE (CallType = 'Inbound' OR CallType = 'Outbound') AND CallDurationInSeconds >= 120 AND (WhatId IN :oppIds OR WhatId IN :accIds) ORDER BY CreatedDate ASC];
 
        // create map of opp Id to related call (if any)
        Map<Id, Task> oppIdToCallMap = new Map<Id, Task>();
        for (Task call: relevantCalls){
            // if related to an opp and not in map: add to map
            if(oppIds.contains(call.WhatId) && !oppIdToCallMap.containsKey(call.WhatId)){
       			oppIdToCallMap.put(call.WhatId, call);
            }
            // if related to an account and not in map and owner and created date match the corresponding opp data: add to map
            else if( accIds.contains(call.WhatId) && !oppIdToCallMap.containsKey(accToOppMap.get(call.WhatId)) && accToOppOwnerMap.get(call.WhatId) == call.OwnerId && accToOppCreatedDateMap.get(call.WhatId) <= call.CreatedDate){
           		oppIdToCallMap.put(accToOppMap.get(call.WhatId), call);
            }
    	}
        
        // loop through opps & update
        for (Opportunity opp: oppList){
            if (oppIdToCallMap.containsKey(opp.Id)){
                Task relatedCall = oppIdToCallMap.get(opp.Id);
                opp.Demo_Date__c = relatedCall.CreatedDate.date();
                opp.Hunter__c = relatedCall.OwnerId;
                opp.Timestamp_Demo_Held__c = relatedCall.CreatedDate.date();
                opp.Timestamp_Demo_Held_Time__c = relatedCall.CreatedDate;
                
                // populate previous timestamps if empty
                if (opp.Timestamp_Not_reached_yet__c == NULL){
                    opp.Timestamp_Not_reached_yet__c = relatedCall.CreatedDate.date();
                    opp.Timestamp_Not_reached_yet_time__c = relatedCall.CreatedDate;
                }
                if (opp.Timestamp_Qualified_Prospect__c == NULL){
                    opp.Timestamp_Qualified_Prospect__c = relatedCall.CreatedDate.date();
                    opp.Timestamp_Qualified_Prospect_Time__c = relatedCall.CreatedDate;
                }
                if (opp.Timestamp_Currently_in_Contact__c == NULL){
                    opp.Timestamp_Currently_in_Contact__c = relatedCall.CreatedDate.date();
                    opp.Timestamp_Currently_in_Contact_Time__c = relatedCall.CreatedDate;
            	}               
                if (opp.Timestamp_Demo_Scheduled__c == NULL){
                    opp.Timestamp_Demo_Scheduled__c = relatedCall.CreatedDate.date();
                }
                if (opp.Timestamp_Demo_confirmed__c == NULL){
                    opp.Timestamp_Demo_confirmed__c = relatedCall.CreatedDate.date();
                }
            }
        }
        
     	try{
            update oppList;
            }catch(Exception e){
                
            }
      	
    }

}