force-app/main/default/objects/Account/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <description>Accounts that are in Sales Process (Customer Acquisition, Account Management)</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Campaign/fields/Lead_Score_Group__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Group__c</fullName>
    <description>Defines the Target Group for Reporting and Naming Convention</description>
    <inlineHelpText>Defines the Target Group for Reporting and Naming Convention</inlineHelpText>
    <label>Lead Score Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAA</fullName>
            </value>
            <value>
                <fullName>AA</fullName>
            </value>
            <value>
                <fullName>A+</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B+</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Target_Group__c.field-meta.xml
<CustomField>
    <fullName>Target_Group__c</fullName>
    <description>Defines the Target Group for Reporting and Naming Convention</description>
    <inlineHelpText>Defines the Target Group for Reporting and Naming Convention</inlineHelpText>
    <label>Target Group</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>Head of HR</fullName>
            </value>
            <value>
                <fullName>Head ofs (not HR)</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>HR in General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignMemberTriggerHandlerTest.cls
@isTest
public class CampaignMemberTriggerHandlerTest {
    @isTest
    public static void dotest(){
        Account objAcc = new Account(Name='Test Account');
        Insert objAcc;
        Contact testContact = new Contact(AccountId = objAcc.Id, FirstName = 'TestContactF', LastName = 'TestContactL', Email = 'none@none.net');
        insert testContact;
        Contact testContact2 = new Contact(AccountId = objAcc.Id, FirstName = 'TestContactF2', LastName = 'TestContactL2', Email = 'none2@none.net');
        insert testContact2;
        Campaign objCampaign = new Campaign(Type='Email', Name='Test Campaign',Target_Group__c = 'HR' ,  Lead_Score_Group__c= 'AA');
        Insert objCampaign;
        //Creates a new campaign memeber, associaites it with 1 provider sales campaign, and inserts
        CampaignMember newMember = 
        new CampaignMember(CampaignId = objCampaign.Id,Status='Sent', ContactId = testContact.Id);
        insert newMember;
        Test.startTest();
        CampaignMember newMember2 = 
        new CampaignMember(CampaignId = objCampaign.Id,Status='Sent', ContactId = testContact2.Id);
        insert newMember2;
        Test.stopTest();
    }
}