force-app/main/default/objects/Account/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <description>Accounts that are in Sales Process (Customer Acquisition, Account Management)</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Domain_Match_on_Lead__c.field-meta.xml
<CustomField>
    <fullName>Domain_Match_on_Lead__c</fullName>
    <label>Domain Match on Lead</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Timestamp_Latest_MQL_conversion__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Latest_MQL_conversion__c</fullName>
    <description>RO-1700</description>
    <label>Timestamp Latest MQL conversion</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Timestamp_SSSU_lead__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_SSSU_lead__c</fullName>
    <inlineHelpText>This timestamps gets populated when the customer submitted the Self-Service Sign Up Form on our website</inlineHelpText>
    <label>Timestamp SSSU</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Webinar_Campaign_Source__c.field-meta.xml
<CustomField>
    <fullName>Webinar_Campaign_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legacy - Webinar Campaign Source</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Latest_MQL_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Latest_MQL_Conversion__c</fullName>
    <inlineHelpText>Zeitpunkt der neuesten MQL-Konvertierung.</inlineHelpText>
    <label>Timestamp Latest MQL Conversion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Webinar_Campaign_Source__c.field-meta.xml
<CustomField>
    <fullName>Webinar_Campaign_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legacy - Webinar Campaign Source</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Opportunities (Webinar Campaign Source)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Customer Acquisition Deals Subscription</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/classes/MQLConversionFunction.cls
/*
*      @author Arun Kumar
*      @date   21-Nov-2023
*      @description   Logic to handle the conversion of MQLs
*
*      Modification Log:
*      ------------------------------------------------------------------------------------
*      Developer        Date                Description
*      ------------------------------------------------------------------------------------
*       Arun Kumar      23-Apr-2024         Updated convertLead(),postMQLConversionUpdates() for RO-2054                
*/

public with sharing class MQLConversionFunction {
    
    public static final string MQL_CONVERSION = 'MQL Conversion';
    
    /**
@Methodname     : checkMQLConversionEligibilityOnInsert
@Param          : List<Lead>
@Return         : Null
@Description    : To check if the MQL could be converted during the creation
**/
    public static void checkMQLConversionEligibilityOnInsert(List<Lead> newLeadList){
         
        Map<Lead, String> leadVsConversionTypeMap = new Map<Lead, String>();
        Map<Id, Id> leadVsCampaignIdMap = new Map<Id, Id>();
        
        //Check for the conversion eligibility
       for(Lead ld : newLeadList){
            if(ld.Domain_Match_on_Lead__c == Integer.valueOf(SYSTEM.Label.SSSU_Domain_Match_Count) && ld.Timestamp_SSSU_lead__c == NULL
               && ld.Timestamp_Latest_MQL_conversion__c != NULL){
                   leadVsConversionTypeMap.put(ld, MQL_CONVERSION);
                   leadVsCampaignIdMap.put(ld.Id, ld.Webinar_Campaign_Source__c);
               }
        }
        
        //Send lead to initiate conversion
        if(!leadVsConversionTypeMap.isEmpty()){
            initiateMQLConversion(leadVsConversionTypeMap, leadVsCampaignIdMap);
        }   
    }
    
    /**
@Methodname     : checkMQLConversionEligibilityOnUpdate
@Param          : List<Lead>
@Return         : Null
@Description    : To check if the MQL could be converted during the Timestamp Latest MQL Conversion updates
**/
    public static void checkMQLConversionEligibilityOnUpdate(List<Lead> newLeadList, List<Lead> oldLeadList){
        
        Map<Id, Lead> oldLeadMap = new Map<Id, Lead>();
        Map<Lead, String> leadVsConversionTypeMap = new Map<Lead, String>();
        Map<Id, Id> leadVsCampaignIdMap = new Map<Id, Id>();
        
        for(Lead ld : oldLeadList){
            oldLeadMap.put(ld.Id, ld);
        }
        
        //Check for the conversion eligibility
       for(Lead ld : newLeadList){
            if(ld.Domain_Match_on_Lead__c == Integer.valueOf(SYSTEM.Label.SSSU_Domain_Match_Count) && ld.Timestamp_SSSU_lead__c == NULL
               && (oldLeadMap.get(ld.Id).Timestamp_Latest_MQL_conversion__c != ld.Timestamp_Latest_MQL_conversion__c) && ld.Timestamp_Latest_MQL_conversion__c != NULL){
                       leadVsConversionTypeMap.put(ld, MQL_CONVERSION);
                       leadVsCampaignIdMap.put(ld.Id, ld.Webinar_Campaign_Source__c);
                   }
        }
        
        //Send lead to initiate conversion
        if(!leadVsConversionTypeMap.isEmpty()){
            initiateMQLConversion(leadVsConversionTypeMap, leadVsCampaignIdMap);
        }
    }
    
     /**
@Methodname     : initiateMQLConversion
@Param          : Map<Lead, String>, Map<Id, Id>
@Return         : Null
@Description    : To initiate the MQL Conversions
**/
    
    public static void initiateMQLConversion(Map<Lead, String> leadVsProcessMap, Map<Id, Id> leadVsCampaignIdMap){
        
        List<Database.LeadConvertResult> conversionResults = new List<Database.LeadConvertResult>();
        
        //Initiate lead conversion
        if(!leadVsProcessMap.isEmpty()){
            conversionResults = convertLead(leadVsProcessMap);
        }
        
        //Perform updates on the converted records
        if(!conversionResults.isEmpty()){
            postMQLConversionUpdates(conversionResults, leadVsCampaignIdMap);
        }
    }
        
    /**
@Methodname     : convertLead
@Param          : List<Lead>
@Return         : Null
@Description    : To convert the MQLs to account, contact and opportunity
**/
    
    public static List<Database.LeadConvertResult> convertLead(Map<Lead,String> leadVsProcessNameMap){
        
        Id presalesAdminID = [SELECT Id FROM User WHERE Name = 'Pre-Sales Admin' LIMIT 1].Id;
        List<Database.LeadConvert> mqlLeadConverts = new List<Database.LeadConvert>();
        List<Database.LeadConvertResult> leadConvertResultList = new List<Database.LeadConvertResult>();
        
        // Convert leads
        for(Lead mqlLead : leadVsProcessNameMap.keySet()){
            Database.LeadConvert lc = new Database.LeadConvert();
            lc.setLeadId(mqlLead.Id);
            lc.setOwnerId(presalesAdminID);
            lc.setDoNotCreateOpportunity(true);
            lc.setConvertedStatus('Converted');
            mqlLeadConverts.add(lc);
        }
        
        if(!mqlLeadConverts.isEmpty()){
            try{
                leadConvertResultList = Database.convertLead(mqlLeadConverts);
            }catch(Exception e){
                Logger.finest('Failed MQL conversion: '+ mqlLeadConverts+' '+'The error occurred: '+ e.getMessage());
                Logger.saveLog();
            }
        }
        
        return leadConvertResultList;
    }
    
    /**
@Methodname     : postConversionUpdates
@Param          : List<Database.LeadConvertResult>
@Return         : Null
@Description    : Updating Recordtypes and creating related records for the Account, Contact and Opportunity from MQL Conversion
**/
    
    public static void postMQLConversionUpdates(List<Database.LeadConvertResult> leadConversionResults, Map<Id, Id> leadVsCampaignMap){
        
        Id accountSalesRT                   = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        //Id oppSalesRT                         = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        Set<Id> convertedAccIdSet           = new Set<Id>();
        Set<Id> convertedConIdSet           = new Set<Id>();
        //Set<Id> convertedOppIdSet             = new Set<Id>();
        List<sObject> convertedObjList      = new List<sObject>();
        //Map<Id, Id> conVsOppIdMap         = new Map<Id, Id>();
        Map<Id, Id> oppVsLeadIdMap          = new Map<Id, Id>();
        
        //Retrieve the converted account, contact and opportunity Ids
        for(Database.LeadConvertResult lcr : leadConversionResults){
            if(lcr.isSuccess()){
                convertedAccIdSet.add(lcr.getAccountId());
                convertedConIdSet.add(lcr.getContactId());
                //convertedOppIdSet.add(lcr.getOpportunityId());
                oppVsLeadIdMap.put(lcr.getOpportunityId(),lcr.getLeadId());
                //conVsOppIdMap.put(lcr.getContactId(),lcr.getOpportunityId());
            }
        }
        
        //Update converted accounts
        if(!convertedAccIdSet.isEmpty()){
            for(Id accId : convertedAccIdSet){
                Account acc      = new Account();
                acc.Id           = accId;
                acc.RecordTypeId = accountSalesRT;
                convertedObjList.add(acc);
            }
        }
        
        //update converted opportunities
        /*
        if(!convertedOppIdSet.isEmpty()){
            for(Id oppId : convertedOppIdSet){
                Opportunity opp     = new Opportunity();
                opp.Id              = oppId;
                opp.RecordTypeId    = oppSalesRT;
                opp.StageName       = 'Qualified Prospect';
                opp.CloseDate       = SYSTEM.Today()+30;
                opp.CampaignId      = leadVsCampaignMap.get(oppVsLeadIdMap.get(oppId));
                convertedObjList.add(opp);
            }
        }*/
        
        //Update converted contacts
        if(!convertedConIdSet.isEmpty()){
            for(Id conId : convertedConIdSet){
                Contact con = new Contact();
                con.Id      = conId;
                convertedObjList.add(con);
            }
        }
        
        if(!convertedObjList.isEmpty()){
            try{
                upsert convertedObjList;
            }catch(Exception e){
                Logger.finest('Failed to update converted MQL: '+convertedObjList+' '+'The error occurred: '+e.getMessage());
                Logger.saveLog();
            }
        } 
    }
}