force-app/main/default/objects/Account/fields/Active_HeyPaket__c.field-meta.xml
<CustomField>
    <fullName>Active_HeyPaket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Active HeyPaket Opportunity
RO-1432</description>
    <inlineHelpText>Zeigt die aktive HeyPaket Opportunity</inlineHelpText>
    <label>Active HeyPaket</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Accounts (Active HeyPaket)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Category_3__c.field-meta.xml
<CustomField>
    <fullName>Category_3__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertising Agencies</fullName>
            </value>
            <value>
                <fullName>Advertising sales</fullName>
            </value>
            <value>
                <fullName>Agricultural Engineering</fullName>
            </value>
            <value>
                <fullName>Agricultural Machinery</fullName>
            </value>
            <value>
                <fullName>Aircraft manufacturers</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Aluminum Plants</fullName>
            </value>
            <value>
                <fullName>Animal Feed</fullName>
            </value>
            <value>
                <fullName>Animal Hospitals</fullName>
            </value>
            <value>
                <fullName>Animal Shelters</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Associations</fullName>
            </value>
            <value>
                <fullName>Auditors</fullName>
            </value>
            <value>
                <fullName>Car manufacturers</fullName>
            </value>
            <value>
                <fullName>Car Service</fullName>
            </value>
            <value>
                <fullName>Car Suppliers</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Basic Chemicals</fullName>
            </value>
            <value>
                <fullName>Basketball Teams</fullName>
            </value>
            <value>
                <fullName>Bedroom Stores</fullName>
            </value>
            <value>
                <fullName>Beverage Industry</fullName>
            </value>
            <value>
                <fullName>Bicycle Manufacturer</fullName>
            </value>
            <value>
                <fullName>Book Publishers</fullName>
            </value>
            <value>
                <fullName>Bookstore</fullName>
            </value>
            <value>
                <fullName>Bowling Center</fullName>
            </value>
            <value>
                <fullName>Brewery</fullName>
            </value>
            <value>
                <fullName>Bread Factories</fullName>
            </value>
            <value>
                <fullName>Breweries</fullName>
            </value>
            <value>
                <fullName>Computer Games</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Estates</fullName>
            </value>
            <value>
                <fullName>Translation</fullName>
            </value>
            <value>
                <fullName>Headhunter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/HeyPaket_Status__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Status__c</fullName>
    <description>Shows the HeyPaket Status of the Opportunity linked under Active HeyPaket.
RO-1432</description>
    <formula>TEXT( Active_HeyPaket__r.HeyPaket_Status__c )</formula>
    <inlineHelpText>Zeigt den HeyPaket-Status der mit dem aktiven HeyPaket verknüpften Opportunity an.</inlineHelpText>
    <label>HeyPaket Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Stage_ACM__c.field-meta.xml
<CustomField>
    <fullName>Stage_ACM__c</fullName>
    <defaultValue>&apos;Prospect&apos;</defaultValue>
    <inlineHelpText>Definiert, wo sich der Account derzeit in unserem Verkaufsprozess befindet.
Finde die genauen Stage-Definitionen hier: https://heyjobs.atlassian.net/wiki/spaces/EO/pages/2155217116/Salesforce+Accounts+Definition+und+Use-Case#Account-Lifecycle-Stage</inlineHelpText>
    <label>Account Lifecycle Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage_ACM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Test_Account__c.field-meta.xml
<CustomField>
    <fullName>Test_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Zeigt an, ob der Account ein Test Account ist.</inlineHelpText>
    <label>Test Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HeyPaket_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Start_Date__c</fullName>
    <description>RO-1432</description>
    <inlineHelpText>Startdatum des HeyPakets. Das Datum wird automatisch beim Akzeptieren der Quote aus dem HeyPaket Start Date auf der Quote eingetragen und definiert, wann das HeyPaket aktiviert wird, also ab wann der Kunde das Budget freigeschaltet bekommt.</inlineHelpText>
    <label>HeyPaket Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HeyPaket_Status__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Status__c</fullName>
    <description>RO-1432</description>
    <inlineHelpText>Aktueller Status des HeyPakets. 
Active = HeyPaket ist aktiv und wird automatisch zum angegebenen End date verlängert
Inactive = HeyPaket wird nicht verlängert, Account hat kein aktives HeyPaket
Renewed = HeyPaket ist aktiv und die Kündigungsfrist ist abgelaufen. HeyPaket wird zum End date automatisch erneuert
Cancelled = HeyPaket wurde gekündigt, verlängert sich nicht, und hat ab dem End date kein aktives HeyPaket mehr
Scheduled = HeyPaket ist für die Zukunft geplant.</inlineHelpText>
    <label>HeyPaket Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HeyPaket_Type__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Type__c</fullName>
    <description>RO-1432</description>
    <inlineHelpText>&quot;HeyPaket-Typ der Opportunity. Mögliche Werte sind: Essential, Advanced, Professional, Ultimate

Mehr Informationen findest du hier https://heyjobs.atlassian.net/wiki/spaces/B2B/pages/2820964365/HeyPakete+bersicht#Leistungen-der-einzelnen-HeyPakete-im-Detail &quot;</inlineHelpText>
    <label>HeyPaket Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Essential</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Ultimate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <formula>TEXT(Account.Service_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Stage_ACM.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot Lost</fullName>
        <isActive>false</isActive>
        <label>Pilot Lost</label>
    </customValue>
    <customValue>
        <fullName>Restart Hunting</fullName>
        <isActive>false</isActive>
        <label>Restart Hunting</label>
    </customValue>
    <customValue>
        <fullName>Blacklist</fullName>
        <isActive>false</isActive>
        <label>Blacklist</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
        <isActive>false</isActive>
        <label>Expansion</label>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
        <isActive>false</isActive>
        <label>Invalid</label>
    </customValue>
    <customValue>
        <fullName>Offline - Pause</fullName>
        <isActive>false</isActive>
        <label>Offline - Pause</label>
    </customValue>
    <customValue>
        <fullName>Hunting Lost</fullName>
        <isActive>false</isActive>
        <label>Hunting Lost</label>
    </customValue>
    <customValue>
        <fullName>Does not exist anymore</fullName>
        <isActive>false</isActive>
        <label>Does not exist anymore</label>
    </customValue>
    <customValue>
        <fullName>Existing Lost</fullName>
        <isActive>false</isActive>
        <label>Existing Lost</label>
    </customValue>
    <masterLabel>Stage_ACM</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_HeyPaketUtility.cls
@IsTest
public class Test_HeyPaketUtility {
    
    @IsTest
    static void testHeyPaketUtility_Activation(){
        List<Account> accList = new List<Account>();
        List<Opportunity> oppList = new List<Opportunity>();
        List<string> categoryList1 = new list<string>{'Auditors','Computer Games'};
           
        Test.startTest();
        //Accounts for new activation
        for(integer i = 0; i < categoryList1.size(); i++) {
            Account acc = new Account();
            acc.Name = 'TestIT'+i;
            acc.Category_1__c = 'Service Provider';
            acc.Category_2__c = 'Consultant & IT';
            acc.Category_3__c = categoryList1[i];
            acc.NumberOfEmployees = 15000;
            acc.Service_Country__c = 'DE';
            acc.Stage_ACM__c = 'Lost';
            acc.Test_Account__c = true;
            accList.add(acc); 
        }
        insert accList;
        
         //Opportunities for normal activation
        for(integer i = 0; i < accList.size(); i++){
            Opportunity opp = new Opportunity();
            opp.Name = 'test';
            opp.RecordTypeId = '0121v000000z2JFAAY';
            opp.AccountId = accList[i].Id;
            opp.CloseDate = Date.today() + 180;
            opp.StageName = 'Contract Received';
            opp.HeyPaket_Start_Date__c = Date.today();
            opp.HeyPaket_Type__c = 'Essential';
            oppList.add(opp);
        }
        insert oppList;
        
        HeyPaketUtility.heypaketActivation(oppList);
        Test.stopTest();
    }
    
     @isTest
    static void testHeyPaketUtility_RenewalActivation(){
        
        List<Account> renewalAccList = new List<Account>();
        List<Opportunity> renewalOppList = new List<Opportunity>();
        List<Opportunity> newRenewalOppList = new List<Opportunity>();
        List<string> categoryList2 = new list<string>{'Engineering','Estates'};
        
        Test.startTest();
        
        //Accounts for upsell activation
        for(integer i = 0; i < categoryList2.size(); i++) {
            Account acc = new Account();
            acc.Name = 'Upsell '+i+categoryList2[i];
            acc.Category_1__c = 'Service Provider';
            acc.Category_2__c = 'Consultant & IT';
            acc.Category_3__c = categoryList2[i];
            acc.NumberOfEmployees = 15000;
            acc.Service_Country__c = 'DE';
            acc.Test_Account__c = true;
            renewalAccList.add(acc); 
        }
        insert renewalAccList;
        
        //Existing Opportunities that are in Renewed Stage
        for(integer i = 0; i < renewalAccList.size(); i++){
            Opportunity opp = new Opportunity();
            opp.Name = 'test';
            opp.RecordTypeId = '0121v000000z2JFAAY';
            opp.AccountId = renewalAccList[i].Id;
            opp.CloseDate = Date.today() + 180;
            opp.StageName = 'Contract Received';
            opp.HeyPaket_Start_Date__c = Date.today() -180;
            opp.HeyPaket_Type__c = 'Professional';
            opp.HeyPaket_Status__c = 'Renewed';
            renewalOppList.add(opp);
        }
        insert renewalOppList;
        
        for(integer i = 0; i < renewalAccList.size(); i++){
            renewalAccList[i].Active_HeyPaket__c = renewalOppList[i].Id;
        }
        
        update renewalAccList;
        
        //New Opportunities to override the existing Active pakets
        for(integer i = 0; i < renewalAccList.size(); i++){
            Opportunity opp = new Opportunity();
            opp.Name = 'test';
            opp.RecordTypeId = '0121v000000z2JFAAY';
            opp.AccountId = renewalAccList[i].Id;
            opp.CloseDate = Date.today() + 180;
            opp.StageName = 'Contract Received';
            opp.HeyPaket_Start_Date__c = Date.today();
            opp.HeyPaket_Type__c = 'Professional';
            opp.HeyPaket_Status__c = 'Active';
            newRenewalOppList.add(opp);
        }
        insert newRenewalOppList;
        
        HeyPaketUtility.heypaketActivation(newRenewalOppList);
        Test.stopTest(); 
    }
    
    @isTest
    static void testHeyPaketUtility_UpsellActivation(){
        
        List<Account> activeAccList = new List<Account>();
        List<Opportunity> activeOppList = new List<Opportunity>();
        List<Opportunity> newActiveOppList = new List<Opportunity>();
        List<string> categoryList3 = new list<string>{'Translation','Headhunter'};
        
        Test.startTest();
        
        //Accounts for upsell activation
        for(integer i = 0; i < categoryList3.size(); i++) {
            Account acc = new Account();
            acc.Name = 'Upsell '+i+categoryList3[i];
            acc.Category_1__c = 'Service Provider';
            acc.Category_2__c = 'Consultant & IT';
            acc.Category_3__c = categoryList3[i];
            acc.NumberOfEmployees = 15000;
            acc.Service_Country__c = 'DE';
            acc.Test_Account__c = true;
            activeAccList.add(acc); 
        }
        insert activeAccList;
        
        //Existing Opportunities that are in Active Stage
        for(integer i = 0; i < activeAccList.size(); i++){
            Opportunity opp = new Opportunity();
            opp.Name = 'test';
            opp.RecordTypeId = '0121v000000z2JFAAY';
            opp.AccountId = activeAccList[i].Id;
            opp.CloseDate = Date.today() + 180;
            opp.StageName = 'Contract Received';
            opp.HeyPaket_Start_Date__c = Date.today() -180;
            opp.HeyPaket_Type__c = 'Essential';
            opp.HeyPaket_Status__c = 'Active';
            activeOppList.add(opp);
        }
        insert activeOppList;
        
        for(integer i = 0; i < activeAccList.size(); i++){
            activeAccList[i].Active_HeyPaket__c = activeOppList[i].Id;
        }
        
        update activeAccList;
        
        //New Opportunities to override the existing Active pakets
        for(integer i = 0; i < activeAccList.size(); i++){
            Opportunity opp = new Opportunity();
            opp.Name = 'test';
            opp.RecordTypeId = '0121v000000z2JFAAY';
            opp.AccountId = activeAccList[i].Id;
            opp.CloseDate = Date.today() + 180;
            opp.StageName = 'Contract Received';
            opp.HeyPaket_Start_Date__c = Date.today() -180;
            opp.HeyPaket_Type__c = 'Essential';
            opp.HeyPaket_Status__c = 'Active';
            newActiveOppList.add(opp);
        }
        insert newActiveOppList;
        
        HeyPaketUtility.heypaketActivation(newActiveOppList);
        Test.stopTest();
        
    }
    
   
}