force-app/main/default/objects/Account/fields/Active_HeyPaket__c.field-meta.xml
<CustomField>
    <fullName>Active_HeyPaket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Active HeyPaket Opportunity
RO-1432</description>
    <inlineHelpText>Zeigt die aktive HeyPaket Opportunity</inlineHelpText>
    <label>Active HeyPaket</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Accounts (Active HeyPaket)</relationshipLabel>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/HeyPaket_Status__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Status__c</fullName>
    <description>Shows the HeyPaket Status of the Opportunity linked under Active HeyPaket.
RO-1432</description>
    <formula>TEXT( Active_HeyPaket__r.HeyPaket_Status__c )</formula>
    <inlineHelpText>Zeigt den HeyPaket-Status der mit dem aktiven HeyPaket verknüpften Opportunity an.</inlineHelpText>
    <label>HeyPaket Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_HeyPaket__c.field-meta.xml
<CustomField>
    <fullName>Last_HeyPaket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RO-1432</description>
    <inlineHelpText>Zeigt das letzte HeyPaket</inlineHelpText>
    <label>Last HeyPaket</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Accounts (Last HeyPaket)</relationshipLabel>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Next_HeyPaket__c.field-meta.xml
<CustomField>
    <fullName>Next_HeyPaket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RO-1432</description>
    <inlineHelpText>Zeigt das nächste HeyPaket</inlineHelpText>
    <label>Next HeyPaket</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Accounts (Next HeyPaket)</relationshipLabel>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Description_RichText__c.field-meta.xml
<CustomField>
    <fullName>Description_RichText__c</fullName>
    <description>RO-1458</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </filterItems>
        <filterItems>
            <field>Opportunity.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Parent_Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <infoMessage>Shows all linked Opportunities to the Account and it&apos;s Parent Account</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Feature_Activation__mdt/Feature_Activation__mdt.object-meta.xml
<CustomObject>
    <label>Feature Activation</label>
    <pluralLabel>Features Activation</pluralLabel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/HeyPaket_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Start_Date__c</fullName>
    <description>RO-1432</description>
    <inlineHelpText>Startdatum des HeyPakets. Das Datum wird automatisch beim Akzeptieren der Quote aus dem HeyPaket Start Date auf der Quote eingetragen und definiert, wann das HeyPaket aktiviert wird, also ab wann der Kunde das Budget freigeschaltet bekommt.</inlineHelpText>
    <label>HeyPaket Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HeyPaket_Start_Date_reached__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Start_Date_reached__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HeyPaket Start Date reached</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HeyPaket_Status__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Status__c</fullName>
    <description>RO-1432</description>
    <inlineHelpText>Aktueller Status des HeyPakets. 
Active = HeyPaket ist aktiv und wird automatisch zum angegebenen End date verlängert
Inactive = HeyPaket wird nicht verlängert, Account hat kein aktives HeyPaket
Renewed = HeyPaket ist aktiv und die Kündigungsfrist ist abgelaufen. HeyPaket wird zum End date automatisch erneuert
Cancelled = HeyPaket wurde gekündigt, verlängert sich nicht, und hat ab dem End date kein aktives HeyPaket mehr
Scheduled = HeyPaket ist für die Zukunft geplant.</inlineHelpText>
    <label>HeyPaket Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HeyPaket_Type__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Type__c</fullName>
    <description>RO-1432</description>
    <inlineHelpText>&quot;HeyPaket-Typ der Opportunity. Mögliche Werte sind: Essential, Advanced, Professional, Ultimate

Mehr Informationen findest du hier https://heyjobs.atlassian.net/wiki/spaces/B2B/pages/2820964365/HeyPakete+bersicht#Leistungen-der-einzelnen-HeyPakete-im-Detail &quot;</inlineHelpText>
    <label>HeyPaket Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Essential</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Ultimate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_HeyPaket_Activation__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_HeyPaket_Activation__c</fullName>
    <description>RO-1432</description>
    <inlineHelpText>Zeitpunkt der Aktivierung des HeyPakets.</inlineHelpText>
    <label>Timestamp HeyPaket Activation</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/HeyPaketUtility.cls
/*
*      @author Arun Kumar
*      @date   21-Apr-2023
*      @description   Class to handle generic functions related to HeyPaket
*
*      Modification Log:
*      ------------------------------------------------------------------------------------
*      	Developer      	Date         	Description
*      ------------------------------------------------------------------------------------
*		Arun Kumar		08.06.2023		Updated heypaketActivation() to include additional fields
*	   	Arun Kumar		12.06.2023		Updated heypaketActivation() to include activating new packets and deactivating old packets
*		Arun Kumar		08.08.2023		RO-1604 : Updated heypaketActivation() to combine the field updates for renewal and upsell activations
*		Arun Kumar		08.08.2023		RO-1604 : Created createBudgetValidityCase().
*		Arun Kumar		08.08.2023		RO-1604 : Updated heypaketActivation() to include the calling of createBudgetValidityCase() in renewal/upsell logic
*		Arun Kumar		09.08.2023		RO-1604 : Updated heypaketActivation()to comment the calling for flow HeyPaket_Activation
*		Arun Kumar		24.10.2023		RO-1666 : Created checkHeyPaketActivationEligibility() for validating and triggering HeyPaket Activation
*		Lisa Müller		09.02.2024		RO-1941 : Updated error logging to create a single log for every record instead of one log for the whole batch
*/
public with sharing class HeyPaketUtility {
    
    /**
@Methodname     : checkHeyPaketActivationEligibility
@Param          : List<Opportunity>, List<Opportunity>
@Return         : Null
@Description    : To trigger the HeyPaket activation for the opportunity if the criteria is matched
**/ 
    public static void checkActivationEligibility(List<Opportunity> newList, List<Opportunity> oldList){
        
        List<Opportunity> opptoActivateList = new List<Opportunity>();
        Map<Id, Opportunity> oldOppMap = new Map<Id, Opportunity>();
        
        for(Opportunity opp : oldList){
           oldOppMap.put(opp.Id, opp); 
        }
        
        for(Opportunity opp : newList){
            if(oldOppMap.containsKey(opp.Id) && oldOppMap.get(opp.Id).StageName != opp.StageName 
               && opp.StageName == SYSTEM.Label.STAGE_CLOSED_WON && opp.HeyPaket_Start_Date__c == SYSTEM.Today() && opp.HeyPaket_Status__c != 'Active'){
                opptoActivateList.add(opp);
            }
        }
        
        if(!opptoActivateList.isEmpty()){
            heypaketActivation(opptoActivateList);
        }
    }
    
     /**
@Methodname     : heypaketActivation
@Param          : List<Opportunity>
@Return         : Null
@Description    : To initiate the HeyPaket activation
**/ 
    public static void heypaketActivation(List<Opportunity> oppList){
        
        Set<Id> accountIds = new Set<Id>();
        List<Account> activatedAccList = new List<Account>();
        List<Opportunity> deactivatedOppList = new List<Opportunity>();
        Map<Id, Account> accountMap;
        Map<Id, Id> oppIdVsAccIdMap = new Map<Id, Id>();
        
        //Retrieve eligibility 
        Feature_Activation__mdt fa = Feature_Activation__mdt.getInstance('HeyPaket_Activation_via_Customisation');
        Boolean isActive = (Boolean)fa.get('Is_Active__c');
        
        for(Opportunity opp : oppList) {
            accountIds.add(opp.AccountId);
        }
        
        accountMap = new Map<Id, Account>([SELECT Id, Name, Next_HeyPaket__c, Last_HeyPaket__c, Active_HeyPaket__c, Active_HeyPaket__r.HeyPaket_Status__c, Active_HeyPaket__r.HeyPaket_Type__c FROM Account WHERE Id IN :accountIds]);
        
        if(isActive){
            for(Opportunity opp : oppList){
                opp.HeyPaket_Status__c = SYSTEM.Label.HeyPaket_Active;
                opp.Timestamp_HeyPaket_Activation__c = System.now();
                if(!opp.HeyPaket_Start_Date_reached__c) opp.HeyPaket_Start_Date_reached__c = TRUE;
                
                if(!accountMap.isEmpty() && accountMap.containsKey(opp.AccountId)){
                    if(accountMap.get(opp.AccountId).Active_HeyPaket__c == NULL){//New Activation
                        //Activating accounts
                        accountMap.get(opp.AccountId).Active_HeyPaket__c = opp.Id;
                        accountMap.get(opp.AccountId).Next_HeyPaket__c = NULL;
                        activatedAccList.add(accountMap.get(opp.AccountId));
                        //To do - Logic to send New Activation Slack message
                    }else if((accountMap.get(opp.AccountId).Active_HeyPaket__c != NULL && accountMap.get(opp.AccountId).Active_HeyPaket__r.HeyPaket_Status__c == SYSTEM.Label.HeyPaket_Renewed) // Renewal
                            || (accountMap.get(opp.AccountId).Active_HeyPaket__c != NULL && (accountMap.get(opp.AccountId).Active_HeyPaket__r.HeyPaket_Status__c == SYSTEM.Label.HeyPaket_Active || accountMap.get(opp.AccountId).Active_HeyPaket__r.HeyPaket_Status__c == SYSTEM.Label.HeyPaket_Cancelled)) // Upsell
                            ){
                        //Deactivating previous Pakets
                        accountMap.get(opp.AccountId).Active_HeyPaket__r.HeyPaket_Status__c = SYSTEM.Label.HeyPaket_Inactive;
                        deactivatedOppList.add(accountMap.get(opp.AccountId).Active_HeyPaket__r);
                        //Activating Renewal & upsell accounts
                        accountMap.get(opp.AccountId).Last_HeyPaket__c = accountMap.get(opp.AccountId).Active_HeyPaket__c;
                        accountMap.get(opp.AccountId).Active_HeyPaket__c = opp.Id;
                        accountMap.get(opp.AccountId).Next_HeyPaket__c = NULL;
                        activatedAccList.add(accountMap.get(opp.AccountId));
                        //To do - Logic to send Renewal activation Slack message
                        
                        //Checking eligibility for budget validity case - Professional to Professional (or) Professional to Ultimate (or) Ultimate to Ultimate
                        if((accountMap.get(opp.AccountId).Active_HeyPaket__r.HeyPaket_Type__c == SYSTEM.Label.HeyPaket_Professional && opp.HeyPaket_Type__c == SYSTEM.Label.HeyPaket_Professional) 
                           || (accountMap.get(opp.AccountId).Active_HeyPaket__r.HeyPaket_Type__c == SYSTEM.Label.HeyPaket_Ultimate && opp.HeyPaket_Type__c == SYSTEM.Label.HeyPaket_Ultimate)
                          	|| (accountMap.get(opp.AccountId).Active_HeyPaket__r.HeyPaket_Type__c == SYSTEM.Label.HeyPaket_Professional && opp.HeyPaket_Type__c == SYSTEM.Label.HeyPaket_Ultimate)){
                                oppIdVsAccIdMap.put(accountMap.get(opp.AccountId).Last_HeyPaket__c, accountMap.get(opp.AccountId).Id);
                        }
                    }
                    /* Commented as a part of RO-1604. The entry point is combined with the renewal activations
                     * else if(accountMap.get(opp.AccountId).Active_HeyPaket__c != NULL && (accountMap.get(opp.AccountId).Active_HeyPaket__r.HeyPaket_Status__c == SYSTEM.Label.HeyPaket_Active || accountMap.get(opp.AccountId).Active_HeyPaket__r.HeyPaket_Status__c == SYSTEM.Label.HeyPaket_Cancelled)){
                        //Deactivating previous Pakets
                        accountMap.get(opp.AccountId).Active_HeyPaket__r.HeyPaket_Status__c = SYSTEM.Label.HeyPaket_Inactive;
                        deactivatedOppList.add(accountMap.get(opp.AccountId).Active_HeyPaket__r);
                        //Activating Upsell accounts
                        accountMap.get(opp.AccountId).Last_HeyPaket__c = accountMap.get(opp.AccountId).Active_HeyPaket__c;
                        accountMap.get(opp.AccountId).Active_HeyPaket__c = opp.Id;
                        accountMap.get(opp.AccountId).Next_HeyPaket__c = NULL;
                        activatedAccList.add(accountMap.get(opp.AccountId));
                        //To do - Logic to send Upsell activation Slack message
                    }*/
                }
            }
            
            //RO-1604
            if(!oppIdVsAccIdMap.isEmpty()){
                createBudgetValidityCase(oppIdVsAccIdMap);
            }
            
            /*if(!deactivatedOppList.isEmpty()){
                oppList.addAll(deactivatedOppList);
            }*/
            
            // Record updates and Error Logs
            String controlDatabaseMethod = System.Label.HeyPaketActivation_DataBaseMethod;
            if(controlDatabaseMethod == 'Yes'){
                
                //Update deactivated packets
                if(!deactivatedOppList.isEmpty()){
                	Database.SaveResult[] resultsDeactivatedOppList = Database.update(deactivatedOppList, false);
                	// Log errors
                	for (Database.SaveResult sr : resultsDeactivatedOppList) {
                    	if (!sr.isSuccess()) {
                        	for(Database.Error err : sr.getErrors()) {
                            	Logger.finest('HeyPaket activation failed - unable to deactivate old paket: ' + sr.getId() + '. The error occurred: ' + err.getStatusCode() + ' - ' + err.getMessage());
                            	}
                        	}
                    	}		
                	Logger.saveLog();
            	}
                
                //Activate latest packets
                Database.SaveResult[] resultsOppList = Database.update(oppList, false);
                // Log errors
                for (Database.SaveResult sr : resultsOppList) {
                    if (!sr.isSuccess()) {
                        for(Database.Error err : sr.getErrors()) {
                            Logger.finest('HeyPaket activation failed - unable to activate opp: ' + sr.getId() + '. The error occurred: ' + err.getStatusCode() + ' - ' + err.getMessage());
                        }
                    }
                }
                Logger.saveLog();
                
                //Update accounts with recent packet information
                Database.SaveResult[] resultsAccList = Database.update(activatedAccList, false);
                // Log errors
                for (Database.SaveResult sr : resultsAccList) {
                    if (!sr.isSuccess()) {
                        for(Database.Error err : sr.getErrors()) {
                            Logger.finest('HeyPaket activation failed - unable to update accounts with activation details: ' + sr.getId() + '. The error occurred: ' + err.getStatusCode() + ' - ' + err.getMessage());
                        }
                    }
                }		
                Logger.saveLog();                
                
            } else{
                
                //Update deactivated packets
                if(!deactivatedOppList.isEmpty()){
                    try{
                        update deactivatedOppList;  
                    }catch(Exception e){
                        Logger.finest('HeyPaket activation failed - unable to deactivate old pakets : '+deactivatedOppList+' '+'The error occurred: '+e.getMessage());
                        Logger.saveLog();
                    }
                }
                
                //Activate latest packets
                try{
                    update oppList;
                }catch(Exception e){
                    Logger.finest('HeyPaket activation failed - unable to activate opps : '+oppList+' '+'The error occurred: '+e.getMessage());
                    Logger.saveLog();
                }
                
                //Update accounts with recent packet information
                try{
                    update activatedAccList;
                }catch(Exception e){
                    Logger.finest('HeyPaket activation failed - unable to update accounts with activation details : '+activatedAccList+' '+'The error occurred: '+e.getMessage());
                    Logger.saveLog();
                }
                                 
            }
            
        }/*Commented as a part of RO-1604. 
           else{
            Map<String, Object> flowInputs = new Map<String, Object>();
            flowInputs.put('varOppList', oppList);
            flowInputs.put('varAccountList', accountMap.values());
            Flow.Interview.HeyPaket_Activation heypaketActivationFlow = new Flow.Interview.HeyPaket_Activation(flowInputs);
            if(!Test.isRunningTest()){
                heypaketActivationFlow.start();
            }
        }*/
    }
    
    /**
    @Methodname     : createBudgetValidityCase
    @Param          : Map<Id, Id> -> Opportunity Id and Account Id
    @Return         : Null
    @Description    : RO-1604 - To create Budget Validity case for deactivated HeyPakets
    **/
    
    public static void createBudgetValidityCase(Map<Id, Id> oppVsAccIdMap){
        
        Feature_Activation__mdt fa = Feature_Activation__mdt.getInstance('createBudgetValidityCase');
        Boolean isActive = (Boolean)fa.get('Is_Active__c');
        
        if(isActive){
            List<Case> budgetCaseList = new List<Case>();
            Id caseRepeatPurchaseRT = Schema.SObjectType.Case.getRecordTypeInfosByName().get(SYSTEM.Label.Case_Repeat_Purchase).getRecordTypeId();
            Id cusOpsQueueId = [SELECT Id FROM Group WHERE DeveloperName = 'CusOps_Case_Queue'].Id;
            
            if(!oppVsAccIdMap.isEmpty()){
                for(Id oppId : oppVsAccIdMap.keySet()){
                    Case budgetCase = new Case();
                    budgetCase.Subject = SYSTEM.Label.HeyPaket_Budget_Extension_Case ;
                    budgetCase.Description_RichText__c = SYSTEM.Label.HeyPaket_Budget_Validity_Case_Description;
                    budgetCase.Opportunity__c = oppId;
                    budgetCase.RecordTypeId = caseRepeatPurchaseRT;
                    budgetCase.Status = SYSTEM.Label.New_Case;
                    budgetCase.AccountId = oppVsAccIdMap.get(oppId);
                    budgetCase.OwnerId = cusOpsQueueId;
                    budgetCaseList.add(budgetCase);
                }
            }
            
            if(!budgetCaseList.isEmpty()){
                try{
                    insert budgetCaseList;
                }catch(Exception e){
                    System.debug('Error occurred while inserting budget validity case'+e.getMessage());
                }
            }  
        }
    }
}