force-app/main/default/objects/Account/fields/Blacklist__c.field-meta.xml
<CustomField>
    <fullName>Blacklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>RO-236</description>
    <inlineHelpText>Ein Account sollte auf die Blacklist gesetzt werden, wenn der Kunde dies wünscht (z.B. „Kontaktieren Sie uns nie wieder“). Im Gegensatz dazu, wenn der Kunde sich nur auf sich selbst bezieht („Kontaktieren Sie mich nie wieder“), sollte der jeweilige Kontakt und nicht der Account auf die Blacklist gesetzt werden.</inlineHelpText>
    <label>Blacklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/No_Repeat_Purchase_Typeform__c.field-meta.xml
<CustomField>
    <fullName>No_Repeat_Purchase_Typeform__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Das No Repeat Purchase Typeform (NRPT) Feld, wenn aktiviert (TRUE), umgeht die Notwendigkeit, dass Kunden bei jedem Kauf wiederholt Rechnungs- und Versandinformationen angeben müssen, sofern ihre Account-Daten vollständig sind. Wenn NRPT deaktiviert ist (FALSE), müssen Kunden ein Typeform für jede geschlossene Opportunity ausfüllen, bevor die Opportunity in die Stage &apos;closed won&apos; gehen kann.</inlineHelpText>
    <label>No Repeat Purchase Typeform</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Segment_V02__c.field-meta.xml
<CustomField>
    <fullName>Segment_V02__c</fullName>
    <description>RO - 1973</description>
    <inlineHelpText>RETIRED</inlineHelpText>
    <label>Segment V02 (reporting only)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Stage_ACM__c.field-meta.xml
<CustomField>
    <fullName>Stage_ACM__c</fullName>
    <defaultValue>&apos;Prospect&apos;</defaultValue>
    <inlineHelpText>Definiert, wo sich der Account derzeit in unserem Verkaufsprozess befindet.
Finde die genauen Stage-Definitionen hier: https://heyjobs.atlassian.net/wiki/spaces/EO/pages/2155217116/Salesforce+Accounts+Definition+und+Use-Case#Account-Lifecycle-Stage</inlineHelpText>
    <label>Account Lifecycle Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage_ACM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Discarded.recordType-meta.xml
<RecordType>
    <fullName>Discarded</fullName>
    <active>true</active>
    <description>Accounts that should never be re-engaged because they no longer exists (e.g., due to bankruptcy) or were mistakenly created for a jobseeker.</description>
    <label>Discarded</label>
</RecordType>

force-app/main/default/globalValueSets/Stage_ACM.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot Lost</fullName>
        <isActive>false</isActive>
        <label>Pilot Lost</label>
    </customValue>
    <customValue>
        <fullName>Restart Hunting</fullName>
        <isActive>false</isActive>
        <label>Restart Hunting</label>
    </customValue>
    <customValue>
        <fullName>Blacklist</fullName>
        <isActive>false</isActive>
        <label>Blacklist</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
        <isActive>false</isActive>
        <label>Expansion</label>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
        <isActive>false</isActive>
        <label>Invalid</label>
    </customValue>
    <customValue>
        <fullName>Offline - Pause</fullName>
        <isActive>false</isActive>
        <label>Offline - Pause</label>
    </customValue>
    <customValue>
        <fullName>Hunting Lost</fullName>
        <isActive>false</isActive>
        <label>Hunting Lost</label>
    </customValue>
    <customValue>
        <fullName>Does not exist anymore</fullName>
        <isActive>false</isActive>
        <label>Does not exist anymore</label>
    </customValue>
    <customValue>
        <fullName>Existing Lost</fullName>
        <isActive>false</isActive>
        <label>Existing Lost</label>
    </customValue>
    <masterLabel>Stage_ACM</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountUpdateBatch.cls
global class AccountUpdateBatch implements Database.Batchable<sObject>
{
	global Database.QueryLocator start(Database.BatchableContext BC)
	{
        string RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Discarded').getRecordTypeId();

        String query = 'SELECT Id,No_repeat_purchase_typeform__c from Account where (Stage_ACM__c = \'Prospect\' OR Stage_ACM__c = \'Lost\') AND Segment_V02__c = \'Small\' AND No_repeat_purchase_typeform__c = False And recordtypeId != :RecordTypeId AND Blacklist__c = False';
        system.debug('query::'+query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Account> accountList)
    {
        list<account> accountUpdateList = new list<account>();
        for ( account acc : accountList)
        {
            account accUpdate = new account();
            accUpdate.id = acc.id;
           accUpdate.No_repeat_purchase_typeform__c = true;
           accountUpdateList.add(accUpdate); 
        }
        database.update(accountUpdateList);
    }  
    global void finish(Database.BatchableContext BC)
    {
    }
}