force-app/main/default/objects/Account/fields/Blacklist__c.field-meta.xml
<CustomField>
    <fullName>Blacklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>RO-236</description>
    <inlineHelpText>Ein Account sollte auf die Blacklist gesetzt werden, wenn der Kunde dies wünscht (z.B. „Kontaktieren Sie uns nie wieder“). Im Gegensatz dazu, wenn der Kunde sich nur auf sich selbst bezieht („Kontaktieren Sie mich nie wieder“), sollte der jeweilige Kontakt und nicht der Account auf die Blacklist gesetzt werden.</inlineHelpText>
    <label>Blacklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Description_c__c.field-meta.xml
<CustomField>
    <fullName>Description_c__c</fullName>
    <description>Is used to generate Account Description on Account Lighning Page</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/txtCompanyId__c.field-meta.xml
<CustomField>
    <fullName>txtCompanyId__c</fullName>
    <description>Can be found in Salesforce under Account Details, or via the link to the backend. There, the ID is specified after the last slash</description>
    <externalId>true</externalId>
    <inlineHelpText>Jedes Unternehmen erhält eine eindeutige Company ID, sobald eine Backend Company für diesen Salesforce-Account angelegt wurde. Die Company ID erlaubt uns, Salesforce-Accounts den Companies im Backend zuzuordnen. Daher kann dieser Wert nach dem Eintragen auch nicht verändert werden.</inlineHelpText>
    <label>Company Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Backend_access_enabled__c.field-meta.xml
<CustomField>
    <fullName>Backend_access_enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>RO-1639</description>
    <inlineHelpText>Triggering field for BE company + user creation</inlineHelpText>
    <label>Backend access enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Blacklist__c.field-meta.xml
<CustomField>
    <fullName>Blacklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Blacklist Contact for Campaigns</description>
    <inlineHelpText>Zeigt, dass der Kontakt nicht mehr angegangen werden soll, e.g. weil der Kontakt nie wieder von Heyjobs kontaktiert werden möchte. Geblacklistete Kontakte sind von allen marketing Kampagnen ausgeschlossen.</inlineHelpText>
    <label>Blacklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Timestamp_SSSU__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_SSSU__c</fullName>
    <inlineHelpText>Zeigt, wann der Kontakt das erst mal das Self Service Sign Up Form auf unserer Webseite ausgefüllt hat.</inlineHelpText>
    <label>Timestamp SSSU</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ContactTriggerFunctions.cls
/*
 *      @author Arun Kumar
 *      @date   12-Jun-2023
 *      @description   Business logic based on contact trigger
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 * 
 */
public with sharing class ContactTriggerFunctions {
    
    public static Map<Id, Account> accountMap;
    public static Map<Id, Contact> contactMap;
    
    public static void callingBackendForAccess (List<Contact> newContactList, Map<Id, Contact> oldContactMap){
        List<Id> contactIdList = new List<Id>();
        List<Id> accountIdList = new List<Id>();
        
        for(Contact con : newContactList){
            if(oldContactMap.get(con.Id).Backend_access_enabled__c != con.Backend_access_enabled__c && con.Backend_access_enabled__c == true && con.Timestamp_SSSU__c != NULL){
                contactIdList.add(con.Id);
                accountIdList.add(con.AccountId);
            }
        }
        
        //if(!contactIdList.isEmpty() && !accountIdList.isEmpty()){
        if(contactIdList != NULL && accountIdList != NULL){
        	createBEAccess(contactIdList,accountIdList,'a2L9L00000008k8UAA');
        }
    }
    
    @future (callout = true)
    public static void createBEAccess( List<Id> contactIdList, List<Id> accountIdList, String channelID){
        Map<String, Object> flowInputs = new Map<String, Object>();
        
        if(!contactIdList.isEmpty()){
            contactMap = new Map<Id, Contact>([SELECT Id, Name, AccountId, Email, FirstName, LastName, Blacklist__c
                       		FROM Contact 
                          	WHERE Id =:contactIdList]);
        }
        
        if(!accountIdList.isEmpty()){
            accountMap = new Map<Id, Account>([SELECT Id, Name, Blacklist__c, txtCompanyId__c, RecordTypeId, RecordType.Name, RecordType.DeveloperName, Service_Country__c, CurrencyIsoCode, Description_c__c 
                       		FROM Account 
                          	WHERE Id =:accountIdList]);
        }
        
        if((contactMap != NULL && !contactMap.isEmpty()) && (accountMap != NULL && !accountMap.isEmpty())){
            for(Contact con : contactMap.values()){
                flowInputs.put('varAccount', accountMap.get(con.AccountID));
                flowInputs.put('varContact', contactMap.get(con.Id));
                flowInputs.put('varSlackErrorChannel_ID',channelID);
                Flow.Interview.Automatic_BE_Company_User_Creation backendUserCreation = new Flow.Interview.Automatic_BE_Company_User_Creation(flowInputs);
                backendUserCreation.start();
            }
        }
    }
}