force-app/main/default/objects/Account/fields/Category_3__c.field-meta.xml
<CustomField>
    <fullName>Category_3__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertising Agencies</fullName>
            </value>
            <value>
                <fullName>Advertising sales</fullName>
            </value>
            <value>
                <fullName>Agricultural Engineering</fullName>
            </value>
            <value>
                <fullName>Agricultural Machinery</fullName>
            </value>
            <value>
                <fullName>Aircraft manufacturers</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Aluminum Plants</fullName>
            </value>
            <value>
                <fullName>Animal Feed</fullName>
            </value>
            <value>
                <fullName>Animal Hospitals</fullName>
            </value>
            <value>
                <fullName>Animal Shelters</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Associations</fullName>
            </value>
            <value>
                <fullName>Auditors</fullName>
            </value>
            <value>
                <fullName>Car manufacturers</fullName>
            </value>
            <value>
                <fullName>Car Service</fullName>
            </value>
            <value>
                <fullName>Car Suppliers</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Basic Chemicals</fullName>
            </value>
            <value>
                <fullName>Basketball Teams</fullName>
            </value>
            <value>
                <fullName>Bedroom Stores</fullName>
            </value>
            <value>
                <fullName>Beverage Industry</fullName>
            </value>
            <value>
                <fullName>Bicycle Manufacturer</fullName>
            </value>
            <value>
                <fullName>Book Publishers</fullName>
            </value>
            <value>
                <fullName>Bookstore</fullName>
            </value>
            <value>
                <fullName>Bowling Center</fullName>
            </value>
            <value>
                <fullName>Brewery</fullName>
            </value>
            <value>
                <fullName>Bread Factories</fullName>
            </value>
            <value>
                <fullName>Breweries</fullName>
            </value>
            <value>
                <fullName>Computer Games</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Stage_ACM__c.field-meta.xml
<CustomField>
    <fullName>Stage_ACM__c</fullName>
    <defaultValue>&apos;Prospect&apos;</defaultValue>
    <inlineHelpText>Definiert, wo sich der Account derzeit in unserem Verkaufsprozess befindet.
Finde die genauen Stage-Definitionen hier: https://heyjobs.atlassian.net/wiki/spaces/EO/pages/2155217116/Salesforce+Accounts+Definition+und+Use-Case#Account-Lifecycle-Stage</inlineHelpText>
    <label>Account Lifecycle Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage_ACM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Test_Account__c.field-meta.xml
<CustomField>
    <fullName>Test_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Zeigt an, ob der Account ein Test Account ist.</inlineHelpText>
    <label>Test Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Timestamp_Reactivation__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Reactivation__c</fullName>
    <description>This field shows the timestamp of re-visiting this account after the last opp-lost for further contact</description>
    <label>Legacy Timestamp Reactivation</label>
    <summarizedField>Opportunity.Timestamp_Reactivation__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.plLossReason__c</field>
        <operation>notEqual</operation>
        <value>Admin Only: Clean-Up Sales Funnel</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loss_Reason_Detail__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason_Detail__c</fullName>
    <description>Free Test Field to explain the exact loss reason</description>
    <label>Loss Reason Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/plLossReason__c.field-meta.xml
<CustomField>
    <fullName>plLossReason__c</fullName>
    <description>should be filled to later understand why we lose certain clients</description>
    <inlineHelpText>Jede Opportunity in Stage=&quot;Closed Lost&quot;, also gelostete Opportunity, sollte einen Lost Reason besitzen. Mehr Informationen zu den einzelnen Lost Reasons finden du auf Confluence. 
Eine spätere Analyse warum die Opportunities verloren worden sind, ist nützlich um gegebenenfalls Anpassungen am Sales Prozess oder Produkt vorzunehmen.</inlineHelpText>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currently not hiring</fullName>
            </value>
            <value>
                <fullName>Currently no budget available</fullName>
            </value>
            <value>
                <fullName>Currently no focus jobs</fullName>
            </value>
            <value>
                <fullName>Not happy with price</fullName>
            </value>
            <value>
                <fullName>Not happy with selection of features</fullName>
            </value>
            <value>
                <fullName>Not happy with job performance</fullName>
            </value>
            <value>
                <fullName>Not happy with candidate quality</fullName>
            </value>
            <value>
                <fullName>No need for paid recruiting measures</fullName>
            </value>
            <value>
                <fullName>All contacts are ghosting</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Bankrupt</fullName>
            </value>
            <value>
                <fullName>Dependent on decision at different corporate level</fullName>
            </value>
            <value>
                <fullName>Dependent on ATS integration</fullName>
            </value>
            <value>
                <fullName>Already won in SSSU Process</fullName>
            </value>
            <value>
                <fullName>Duplicate Opportunity</fullName>
            </value>
            <value>
                <fullName>Special Case</fullName>
            </value>
            <value>
                <fullName>Sonderkündigungsrecht used</fullName>
                <label>Sonderkündigungsrecht used (REACH only)</label>
            </value>
            <value>
                <fullName>Admin Only: Opp lost due to inactivity</fullName>
            </value>
            <value>
                <fullName>Admin Only: Clean-Up Sales Funnel</fullName>
            </value>
            <value>
                <fullName>Jobseeker_SSSU_only</fullName>
                <label>(SSSU only) Jobseeker</label>
            </value>
            <value>
                <fullName>Fraudulent_SSSU_only</fullName>
                <label>(SSSU only) Fraudulent</label>
            </value>
            <value>
                <fullName>#N/A​</fullName>
                <isActive>false</isActive>
                <label>#N/A​</label>
            </value>
            <value>
                <fullName>1_No Open Jobs</fullName>
                <isActive>false</isActive>
                <label>1_No Open Jobs</label>
            </value>
            <value>
                <fullName>2_Never paying for recruiting</fullName>
                <isActive>false</isActive>
                <label>2_Never paying for recruiting</label>
            </value>
            <value>
                <fullName>3_Happy with competitor solution (which?)</fullName>
                <isActive>false</isActive>
                <label>3_Happy with competitor solution (which?)</label>
            </value>
            <value>
                <fullName>4_Doing same service inhouse</fullName>
                <isActive>false</isActive>
                <label>4_Doing same service inhouse</label>
            </value>
            <value>
                <fullName>5_TRY CEO MAILING</fullName>
                <isActive>false</isActive>
                <label>5_TRY CEO MAILING</label>
            </value>
            <value>
                <fullName>6_Rejected by HeyJobs (inbound)</fullName>
                <isActive>false</isActive>
                <label>6_Rejected by HeyJobs (inbound)</label>
            </value>
            <value>
                <fullName>7_Not reached after 13 attempts</fullName>
                <isActive>false</isActive>
                <label>7_Not reached after 13 attempts</label>
            </value>
            <value>
                <fullName>8_CleaningOut</fullName>
                <isActive>false</isActive>
                <label>8_CleaningOut</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <formula>TEXT(Account.Service_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Reactivation__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Reactivation__c</fullName>
    <description>Reactivation timestamp after the opportunity is lost.</description>
    <label>Timestamp Reactivation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>RO-715</description>
    <formula>Opportunity.Service_Country__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt. Auf der Quote wird das Service Country des Accounts und der Opportunity angezeigt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/globalValueSets/Stage_ACM.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot Lost</fullName>
        <isActive>false</isActive>
        <label>Pilot Lost</label>
    </customValue>
    <customValue>
        <fullName>Restart Hunting</fullName>
        <isActive>false</isActive>
        <label>Restart Hunting</label>
    </customValue>
    <customValue>
        <fullName>Blacklist</fullName>
        <isActive>false</isActive>
        <label>Blacklist</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
        <isActive>false</isActive>
        <label>Expansion</label>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
        <isActive>false</isActive>
        <label>Invalid</label>
    </customValue>
    <customValue>
        <fullName>Offline - Pause</fullName>
        <isActive>false</isActive>
        <label>Offline - Pause</label>
    </customValue>
    <customValue>
        <fullName>Hunting Lost</fullName>
        <isActive>false</isActive>
        <label>Hunting Lost</label>
    </customValue>
    <customValue>
        <fullName>Does not exist anymore</fullName>
        <isActive>false</isActive>
        <label>Does not exist anymore</label>
    </customValue>
    <customValue>
        <fullName>Existing Lost</fullName>
        <isActive>false</isActive>
        <label>Existing Lost</label>
    </customValue>
    <masterLabel>Stage_ACM</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_batchUpdateTaskOwner.cls
@isTest
public class Test_batchUpdateTaskOwner {
    
    @isTest
    static void testBatchUpdate(){
        List<Account> accList = new List<Account>();
        List<Opportunity> oppList = new List<Opportunity>();
        List<Task> taskList = new List<Task>();
        List<string> categoryList = new list<string>{'Auditors','Computer Games','Call Center','Lawyer','Engineering','Tester','Training'};
        
         for(integer i = 0; i < categoryList.size(); i++) {
            Account acc = new Account();
            acc.Name = 'TestIT'+i;
            acc.Category_1__c = 'Service Provider';
            acc.Category_2__c = 'Consultant & IT';
            acc.Category_3__c = categoryList[i];
            acc.NumberOfEmployees = 15000;
            acc.Service_Country__c = 'DE';
            acc.Stage_ACM__c = 'Lost';
            acc.Test_Account__c = true;
            accList.add(acc); 
        }
        insert accList;
        
        for(integer i = 0; i < accList.size(); i++){
            Opportunity opp = new Opportunity();
            opp.Name = 'test';
            opp.RecordTypeId = '0121v000000z2JFAAY';
            opp.AccountId = accList[i].Id;
            opp.CloseDate = Date.today() + 180;
            opp.StageName = 'Closed Lost';
            opp.plLossReason__c = 'Currently not hiring';
            opp.Loss_Reason_Detail__c = 'Test';
            opp.Timestamp_Reactivation__c = Date.today();
            oppList.add(opp);
        }
        insert oppList;
        
        for(integer i = 0; i < accList.size(); i++){
            Task tk = new Task();
            tk.Subject = 'Follow-Up Quote';
            tk.Status = 'Open';
            //tk.AccountId = accList[i];
            tk.Is_Owner_changed__c = true;
            taskList.add(tk);
        }
        insert taskList;
        
        Test.startTest();
        Database.executeBatch(new batchUpdateTaskOwner());
        Test.stopTest();
        
    }

}