force-app/main/default/objects/Account/fields/Category_3__c.field-meta.xml
<CustomField>
    <fullName>Category_3__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertising Agencies</fullName>
            </value>
            <value>
                <fullName>Advertising sales</fullName>
            </value>
            <value>
                <fullName>Agricultural Engineering</fullName>
            </value>
            <value>
                <fullName>Agricultural Machinery</fullName>
            </value>
            <value>
                <fullName>Aircraft manufacturers</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Aluminum Plants</fullName>
            </value>
            <value>
                <fullName>Animal Feed</fullName>
            </value>
            <value>
                <fullName>Animal Hospitals</fullName>
            </value>
            <value>
                <fullName>Animal Shelters</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Associations</fullName>
            </value>
            <value>
                <fullName>Auditors</fullName>
            </value>
            <value>
                <fullName>Car manufacturers</fullName>
            </value>
            <value>
                <fullName>Car Service</fullName>
            </value>
            <value>
                <fullName>Car Suppliers</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Basic Chemicals</fullName>
            </value>
            <value>
                <fullName>Basketball Teams</fullName>
            </value>
            <value>
                <fullName>Bedroom Stores</fullName>
            </value>
            <value>
                <fullName>Beverage Industry</fullName>
            </value>
            <value>
                <fullName>Bicycle Manufacturer</fullName>
            </value>
            <value>
                <fullName>Book Publishers</fullName>
            </value>
            <value>
                <fullName>Bookstore</fullName>
            </value>
            <value>
                <fullName>Bowling Center</fullName>
            </value>
            <value>
                <fullName>Brewery</fullName>
            </value>
            <value>
                <fullName>Bread Factories</fullName>
            </value>
            <value>
                <fullName>Breweries</fullName>
            </value>
            <value>
                <fullName>Computer Games</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Estates</fullName>
            </value>
            <value>
                <fullName>IT Consulting</fullName>
            </value>
            <value>
                <fullName>Translation</fullName>
            </value>
            <value>
                <fullName>Management Consultant</fullName>
            </value>
            <value>
                <fullName>Headhunter</fullName>
            </value>
            <value>
                <fullName>Research Centers</fullName>
            </value>
            <value>
                <fullName>Software Manufacturer</fullName>
            </value>
            <value>
                <fullName>Temporary Employment Agencies</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Stage_ACM__c.field-meta.xml
<CustomField>
    <fullName>Stage_ACM__c</fullName>
    <defaultValue>&apos;Prospect&apos;</defaultValue>
    <inlineHelpText>Definiert, wo sich der Account derzeit in unserem Verkaufsprozess befindet.
Finde die genauen Stage-Definitionen hier: https://heyjobs.atlassian.net/wiki/spaces/EO/pages/2155217116/Salesforce+Accounts+Definition+und+Use-Case#Account-Lifecycle-Stage</inlineHelpText>
    <label>Account Lifecycle Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage_ACM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Test_Account__c.field-meta.xml
<CustomField>
    <fullName>Test_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Zeigt an, ob der Account ein Test Account ist.</inlineHelpText>
    <label>Test Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/X2020_Reference_Clients__c.field-meta.xml
<CustomField>
    <fullName>X2020_Reference_Clients__c</fullName>
    <description>used for hubspot email campaigns</description>
    <inlineHelpText>Zeigt potentielle Referenzkund*innen, die ähnlich zum vorliegenden Account sind.</inlineHelpText>
    <label>Reference Clients</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Research.recordType-meta.xml
<RecordType>
    <fullName>Research</fullName>
    <active>true</active>
    <description>Accounts that are in Research (Taskdrive, B2B Marketing)</description>
    <label>Research</label>
</RecordType>

force-app/main/default/objects/Category3__c/Category3__c.object-meta.xml
<CustomObject>
    <label>Customer Category</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Category Mapping Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category3__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Category3__c/fields/Reference_Clients__c.field-meta.xml
<CustomField>
    <fullName>Reference_Clients__c</fullName>
    <label>Reference Clients</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Stage_ACM.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot Lost</fullName>
        <isActive>false</isActive>
        <label>Pilot Lost</label>
    </customValue>
    <customValue>
        <fullName>Restart Hunting</fullName>
        <isActive>false</isActive>
        <label>Restart Hunting</label>
    </customValue>
    <customValue>
        <fullName>Blacklist</fullName>
        <isActive>false</isActive>
        <label>Blacklist</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
        <isActive>false</isActive>
        <label>Expansion</label>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
        <isActive>false</isActive>
        <label>Invalid</label>
    </customValue>
    <customValue>
        <fullName>Offline - Pause</fullName>
        <isActive>false</isActive>
        <label>Offline - Pause</label>
    </customValue>
    <customValue>
        <fullName>Hunting Lost</fullName>
        <isActive>false</isActive>
        <label>Hunting Lost</label>
    </customValue>
    <customValue>
        <fullName>Does not exist anymore</fullName>
        <isActive>false</isActive>
        <label>Does not exist anymore</label>
    </customValue>
    <customValue>
        <fullName>Existing Lost</fullName>
        <isActive>false</isActive>
        <label>Existing Lost</label>
    </customValue>
    <masterLabel>Stage_ACM</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_batchCategoryAndClientOnAccount.cls
@isTest
public class Test_batchCategoryAndClientOnAccount {
    
    @isTest
    static void testBatchUpdate(){
        
        List<Account> accList = new List<Account>();
        List<Category3__c> cList = new List<Category3__c>();
        List<string> categoryList = new list<string>{'Auditors','Computer Games','Call Center','Lawyer','Engineering','Estates','IT Consulting','Job Promotion','Translation','Management Consultant','Headhunter','Research Centers','Software Manufacturer','Temporary Employment Agencies','Tester','Training'};
        
        for(integer i = 0; i < categoryList.size(); i++) {
            Account acc = new Account();
            acc.Name = 'TestIT'+i;
            acc.Category_1__c = 'Service Provider';
            acc.Category_2__c = 'Consultant & IT';
            acc.Category_3__c = categoryList[i];
            acc.NumberOfEmployees = 15000;
            acc.Service_Country__c = 'DE';
            acc.Stage_ACM__c = 'Lost';
            acc.Test_Account__c = true;
            acc.X2020_Reference_Clients__c = '';
            accList.add(acc); 
        }
        insert accList;
        
        for(integer i = 0; i < categoryList.size(); i++){
            Category3__c ct = new Category3__c();
            ct.Category__c = categoryList[i];
            ct.Reference_Clients__c = 'Sample client'+categoryList[i];
            cList.add(ct);
        }
        insert cList;
        
        Test.startTest();
        Database.executeBatch(new batchCategoryAndClientOnAccount());
        Test.stopTest();    
    }
}