force-app/main/default/objects/Account/fields/Category_3__c.field-meta.xml
<CustomField>
    <fullName>Category_3__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertising Agencies</fullName>
            </value>
            <value>
                <fullName>Advertising sales</fullName>
            </value>
            <value>
                <fullName>Agricultural Engineering</fullName>
            </value>
            <value>
                <fullName>Agricultural Machinery</fullName>
            </value>
            <value>
                <fullName>Aircraft manufacturers</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Aluminum Plants</fullName>
            </value>
            <value>
                <fullName>Animal Feed</fullName>
            </value>
            <value>
                <fullName>Animal Hospitals</fullName>
            </value>
            <value>
                <fullName>Animal Shelters</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Associations</fullName>
            </value>
            <value>
                <fullName>Auditors</fullName>
            </value>
            <value>
                <fullName>Car manufacturers</fullName>
            </value>
            <value>
                <fullName>Car Service</fullName>
            </value>
            <value>
                <fullName>Car Suppliers</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Basic Chemicals</fullName>
            </value>
            <value>
                <fullName>Basketball Teams</fullName>
            </value>
            <value>
                <fullName>Bedroom Stores</fullName>
            </value>
            <value>
                <fullName>Beverage Industry</fullName>
            </value>
            <value>
                <fullName>Bicycle Manufacturer</fullName>
            </value>
            <value>
                <fullName>Book Publishers</fullName>
            </value>
            <value>
                <fullName>Bookstore</fullName>
            </value>
            <value>
                <fullName>Bowling Center</fullName>
            </value>
            <value>
                <fullName>Brewery</fullName>
            </value>
            <value>
                <fullName>Bread Factories</fullName>
            </value>
            <value>
                <fullName>Breweries</fullName>
            </value>
            <value>
                <fullName>Hospitals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/HeyJobs_Category__c.field-meta.xml
<CustomField>
    <fullName>HeyJobs_Category__c</fullName>
    <description>Sector in Tableau/DWH</description>
    <inlineHelpText>HeyJobs spezifische Segregation der Kund*innen, basiert auf Category 1, 2 &amp; 3. Entspricht den Sektoren in Tableau/DWH.</inlineHelpText>
    <label>HeyJobs - Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Call center</fullName>
            </value>
            <value>
                <fullName>Headhunter</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>High-End</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Temporary Employment Agencies</fullName>
            </value>
            <value>
                <fullName>Banking and Insurance</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Inventory Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/urlCareerPage__c.field-meta.xml
<CustomField>
    <fullName>urlCareerPage__c</fullName>
    <inlineHelpText>Die Career Page muss die URL zur Karriereseite des Kunden/Kundin beinhalten. Jedes angelegte Unternehmen (Account) sollte eine Career Page hinterlegt haben.</inlineHelpText>
    <label>Career Page</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Outbound.recordType-meta.xml
<RecordType>
    <fullName>Outbound</fullName>
    <active>true</active>
    <description>Accounts that are in outbound marketing (B2B Marketing)</description>
    <label>Outbound</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Category_1__c.field-meta.xml
<CustomField>
    <fullName>Category_1__c</fullName>
    <label>Category 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Industry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Category_2__c.field-meta.xml
<CustomField>
    <fullName>Category_2__c</fullName>
    <label>Category 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category_1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant &amp; IT</fullName>
            </value>
            <value>
                <fullName>Finance &amp; Insurance</fullName>
            </value>
            <value>
                <fullName>Leisure &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Gastronomy &amp; Tourism</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Real Estate &amp; Building Service</fullName>
            </value>
            <value>
                <fullName>Municipal</fullName>
            </value>
            <value>
                <fullName>Media &amp; Agencies</fullName>
            </value>
            <value>
                <fullName>Transport &amp; Logistics</fullName>
            </value>
            <value>
                <fullName>DIY &amp; Furnishings</fullName>
            </value>
            <value>
                <fullName>Drugstore &amp; Household</fullName>
            </value>
            <value>
                <fullName>Food Stores</fullName>
            </value>
            <value>
                <fullName>Fashion &amp; Lifestyle</fullName>
            </value>
            <value>
                <fullName>Technology &amp; Car</fullName>
            </value>
            <value>
                <fullName>Car Industry &amp; Aircraft Construction</fullName>
            </value>
            <value>
                <fullName>Construction Industry &amp; Steel</fullName>
            </value>
            <value>
                <fullName>Chemical Industry</fullName>
            </value>
            <value>
                <fullName>Electrical Engineering &amp; Medical Technology</fullName>
            </value>
            <value>
                <fullName>Beverage &amp; Tobacco</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>Consumer Goods Manufacturers</fullName>
            </value>
            <value>
                <fullName>Food Industry</fullName>
            </value>
            <value>
                <fullName>Mechanical Engineering</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Category_3__c.field-meta.xml
<CustomField>
    <fullName>Category_3__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1? Stores</fullName>
            </value>
            <value>
                <fullName>1€ Stores</fullName>
            </value>
            <value>
                <fullName>Advertising Agencies</fullName>
            </value>
            <value>
                <fullName>Advertising sales</fullName>
            </value>
            <value>
                <fullName>Agricultural Engineering</fullName>
            </value>
            <value>
                <fullName>Agricultural Machinery</fullName>
            </value>
            <value>
                <fullName>Aircraft manufacturers</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Aluminum Plants</fullName>
            </value>
            <value>
                <fullName>Animal Feed</fullName>
            </value>
            <value>
                <fullName>Animal Hospitals</fullName>
            </value>
            <value>
                <fullName>Animal Shelters</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Associations</fullName>
            </value>
            <value>
                <fullName>Auditors</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Auto Parts Trade</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Basic Chemicals</fullName>
            </value>
            <value>
                <fullName>Basketball Teams</fullName>
            </value>
            <value>
                <fullName>Bausparkasse</fullName>
            </value>
            <value>
                <fullName>Bedroom Stores</fullName>
            </value>
            <value>
                <fullName>Beverage Industry</fullName>
            </value>
            <value>
                <fullName>Bicycle Manufacturer</fullName>
            </value>
            <value>
                <fullName>Bio-Stores</fullName>
            </value>
            <value>
                <fullName>Book Publishers</fullName>
            </value>
            <value>
                <fullName>Bookstore</fullName>
            </value>
            <value>
                <fullName>Bowling Center</fullName>
            </value>
            <value>
                <fullName>Hospitals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Demo_Date__c.field-meta.xml
<CustomField>
    <fullName>Demo_Date__c</fullName>
    <label>Initial Demo Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/HeyJobs_Category__c.field-meta.xml
<CustomField>
    <fullName>HeyJobs_Category__c</fullName>
    <inlineHelpText>indicates the industry where the lead works and is necessary to assign it to industry experts in the HeyJobs teams</inlineHelpText>
    <label>HeyJobs - Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Call center</fullName>
            </value>
            <value>
                <fullName>Headhunter</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>High-End</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Temporary Employment Agencies</fullName>
            </value>
            <value>
                <fullName>Banking and Insurance</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Hotels</fullName>
                <isActive>false</isActive>
                <label>Hotels</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_selfserviceLeadConversion.cls
@isTest
public class Test_selfserviceLeadConversion {

    @isTest static void testConvertLead() {        
        
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Service_Country__c = 'AT';
        insert acc;
        
        List<Lead> leadList = new List<Lead>();
        Lead ld = new Lead(
            LastName = 'test',
            Email = 'test.test@test.com',
            Category_1__c = 'Service Provider',
            Category_2__c = 'Health',
            Category_3__c = 'Hospitals',
            Demo_Date__c = Date.today(),
            HeyJobs_Category__c = 'Agency',
            LeadSource = 'Outbound',
            Status = 'Not researched yet',
            City = 'Berlin',
            Country = 'Deutschland',
            Street= 'test',
            PostalCode = '10666',
            NumberOfEmployees = 50,
            urlCareerPage__c = 'test@test.com',
            Company = 'test',
            Service_Country__c = 'AT',
            Timestamp_SSSU_lead__c = Date.today(),
            Timestamp_SSSU_HS_Workflow_completed__c = System.now(),
            Conversion_Trigger__c = false
        );
        leadList.add(ld);
        
        Lead ld1 = new Lead(
            LastName = 'test',
            Email = 'test.test@test.com',
            Category_1__c = 'Service Provider',
            Category_2__c = 'Health',
            Category_3__c = 'Hospitals',
            Demo_Date__c = Date.today(),
            HeyJobs_Category__c = 'Agency',
            LeadSource = 'Outbound',
            Status = 'Not researched yet',
            City = 'Berlin',
            Country = 'Deutschland',
            Street= 'test',
            PostalCode = '10666',
            NumberOfEmployees = 50,
            urlCareerPage__c = 'test@test.com',
            Company = 'test',
            Timestamp_SSSU_lead__c = Date.today(),
            Timestamp_SSSU_HS_Workflow_completed__c = System.now(),
            Conversion_Trigger__c = false,
            Existing_Account_Name__c = acc.Id
        );
        leadList.add(ld1);
        insert leadList;
        
        Test.startTest();
         // Create a mock response for the HTTP callout
        HttpMock mock = new HttpMock();
        mock.setMock('{"response": "test"}', 200);
        
        // Set the mock response to the mock HTTP callout
        Test.setMock(HttpCalloutMock.class, mock);
        
        List<Lead> testLead = new List<Lead>([SELECT Id, Conversion_Trigger__c, Existing_Account_Name__c FROM Lead WHERE Timestamp_SSSU_lead__c = TODAY]);
        List<Account> testAccount = new List<Account>([SELECT Id FROM Account LIMIT 1]);
        
        for(Lead tld : testLead){
            tld.Existing_Account_Name__c = testAccount[0].Id;
        	tld.Conversion_Trigger__c = true;
        }
        update testLead;
        Test.stopTest();
    }
    
    private class HttpMock implements HttpCalloutMock {
        private String responseBody;
        private Integer responseStatus;
        
        public void setMock(String responseBody, Integer responseStatus) {
            this.responseBody = responseBody;
            this.responseStatus = responseStatus;
        }
        
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setBody(responseBody);
            res.setStatus(String.valueOf(responseStatus));
            return res;
        }
    }
    
    @isTest static void test_processLeadConversionOutput(){
        
        List<Lead> leadList = new List<Lead>();
        Lead ld = new Lead(
            LastName = 'test',
            Email = 'test.test@test.com',
            Category_1__c = 'Service Provider',
            Category_2__c = 'Health',
            Category_3__c = 'Hospitals',
            Demo_Date__c = Date.today(),
            HeyJobs_Category__c = 'Agency',
            LeadSource = 'Outbound',
            Status = 'Not researched yet',
            City = 'Berlin',
            Country = 'Deutschland',
            Street= 'test',
            PostalCode = '10666',
            NumberOfEmployees = 50,
            urlCareerPage__c = 'test@test.com',
            Company = 'test',
            Service_Country__c = 'AT',
            Timestamp_SSSU_lead__c = Date.today(),
            Timestamp_SSSU_HS_Workflow_completed__c = System.now(),
            Conversion_Trigger__c = false
        );
        leadList.add(ld);
        insert leadList;
        
        Test.startTest();
        //List<Database.LeadConvertResult> lcr = Database.convertLead(leadList);
        //selfserviceLeadConversion.processLeadConversionOutput(lcr);
        //Create a mock response for the HTTP callout
        HttpMock mock = new HttpMock();
        mock.setMock('{"response": "test"}', 200);
        
        // Set the mock response to the mock HTTP callout
        Test.setMock(HttpCalloutMock.class, mock);
        selfserviceLeadConversion.convertLead(leadList);
        Test.stopTest();
        
    }
    
    @isTest static void test_initiateCustomLeadConversion(){
        
        List<Lead> leadList = new List<Lead>();
        Lead ld = new Lead(
            LastName = 'test',
            Email = 'test.test@test.com',
            Category_1__c = 'Service Provider',
            Category_2__c = 'Health',
            Category_3__c = 'Hospitals',
            Demo_Date__c = Date.today(),
            HeyJobs_Category__c = 'Agency',
            LeadSource = 'Outbound',
            Status = 'Not researched yet',
            City = 'Berlin',
            Country = 'Deutschland',
            Street= 'test',
            PostalCode = '10666',
            NumberOfEmployees = 50,
            urlCareerPage__c = 'test@test.com',
            Company = 'test',
            Service_Country__c = 'AT',
            Timestamp_SSSU_lead__c = Date.today(),
            Timestamp_SSSU_HS_Workflow_completed__c = System.now(),
            Conversion_Trigger__c = false
        );
        leadList.add(ld);
        insert leadList;
        
        Map<Id,Lead> oldLeadMap = new Map<Id, Lead>();
        for(Lead lead1 : leadList){
            oldLeadMap.put(lead1.Id, lead1);
        }
        
        Test.startTest();
        //Create a mock response for the HTTP callout
        HttpMock mock = new HttpMock();
        mock.setMock('{"response": "test"}', 200);
        
        // Set the mock response to the mock HTTP callout
        Test.setMock(HttpCalloutMock.class, mock);
        leadList[0].Conversion_Trigger__c = True;
        update leadList;
        selfserviceLeadConversion.initiateCustomLeadConversion(leadList,oldLeadMap);
        Test.stopTest();
        
    }
}