force-app/main/default/objects/Account/fields/Category_3__c.field-meta.xml
<CustomField>
    <fullName>Category_3__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertising Agencies</fullName>
            </value>
            <value>
                <fullName>Advertising sales</fullName>
            </value>
            <value>
                <fullName>Agricultural Engineering</fullName>
            </value>
            <value>
                <fullName>Agricultural Machinery</fullName>
            </value>
            <value>
                <fullName>Aircraft manufacturers</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Aluminum Plants</fullName>
            </value>
            <value>
                <fullName>Animal Feed</fullName>
            </value>
            <value>
                <fullName>Animal Hospitals</fullName>
            </value>
            <value>
                <fullName>Animal Shelters</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Associations</fullName>
            </value>
            <value>
                <fullName>Auditors</fullName>
            </value>
            <value>
                <fullName>Car manufacturers</fullName>
            </value>
            <value>
                <fullName>Car Service</fullName>
            </value>
            <value>
                <fullName>Car Suppliers</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Basic Chemicals</fullName>
            </value>
            <value>
                <fullName>Basketball Teams</fullName>
            </value>
            <value>
                <fullName>Bedroom Stores</fullName>
            </value>
            <value>
                <fullName>Beverage Industry</fullName>
            </value>
            <value>
                <fullName>Bicycle Manufacturer</fullName>
            </value>
            <value>
                <fullName>Book Publishers</fullName>
            </value>
            <value>
                <fullName>Bookstore</fullName>
            </value>
            <value>
                <fullName>Bowling Center</fullName>
            </value>
            <value>
                <fullName>Brewery</fullName>
            </value>
            <value>
                <fullName>Bread Factories</fullName>
            </value>
            <value>
                <fullName>Breweries</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/HeyJobs_Category__c.field-meta.xml
<CustomField>
    <fullName>HeyJobs_Category__c</fullName>
    <description>Sector in Tableau/DWH</description>
    <inlineHelpText>HeyJobs spezifische Segregation der Kund*innen, basiert auf Category 1, 2 &amp; 3. Entspricht den Sektoren in Tableau/DWH.</inlineHelpText>
    <label>HeyJobs - Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Call center</fullName>
            </value>
            <value>
                <fullName>Headhunter</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>High-End</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Temporary Employment Agencies</fullName>
            </value>
            <value>
                <fullName>Banking and Insurance</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Inventory Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Stage_ACM__c.field-meta.xml
<CustomField>
    <fullName>Stage_ACM__c</fullName>
    <defaultValue>&apos;Prospect&apos;</defaultValue>
    <inlineHelpText>Definiert, wo sich der Account derzeit in unserem Verkaufsprozess befindet.
Finde die genauen Stage-Definitionen hier: https://heyjobs.atlassian.net/wiki/spaces/EO/pages/2155217116/Salesforce+Accounts+Definition+und+Use-Case#Account-Lifecycle-Stage</inlineHelpText>
    <label>Account Lifecycle Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage_ACM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/X2020_Reference_Clients__c.field-meta.xml
<CustomField>
    <fullName>X2020_Reference_Clients__c</fullName>
    <description>used for hubspot email campaigns</description>
    <inlineHelpText>Zeigt potentielle Referenzkund*innen, die ähnlich zum vorliegenden Account sind.</inlineHelpText>
    <label>Reference Clients</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category3__c/Category3__c.object-meta.xml
<CustomObject>
    <label>Customer Category</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Category Mapping Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category3__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Category3__c/fields/HeyJobs_Category__c.field-meta.xml
<CustomField>
    <fullName>HeyJobs_Category__c</fullName>
    <label>HeyJobs Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HeyJobs_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Category3__c/fields/Reference_Clients__c.field-meta.xml
<CustomField>
    <fullName>Reference_Clients__c</fullName>
    <label>Reference Clients</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <formula>TEXT(Account.Service_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Category3.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Advertising Agencies</fullName>
    </customValue>
    <customValue>
        <fullName>Advertising sales</fullName>
    </customValue>
    <customValue>
        <fullName>Agricultural Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Agricultural Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>Aircraft manufacturers</fullName>
    </customValue>
    <customValue>
        <fullName>Airlines</fullName>
    </customValue>
    <customValue>
        <fullName>Airports</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminum Plants</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Feed</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Hospitals</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Shelters</fullName>
    </customValue>
    <customValue>
        <fullName>Architects</fullName>
    </customValue>
    <customValue>
        <fullName>Associations</fullName>
    </customValue>
    <customValue>
        <fullName>Auditors</fullName>
    </customValue>
    <customValue>
        <fullName>Car manufacturers</fullName>
    </customValue>
    <customValue>
        <fullName>Car Service</fullName>
    </customValue>
    <customValue>
        <fullName>Car Suppliers</fullName>
    </customValue>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Banks</fullName>
    </customValue>
    <customValue>
        <fullName>Basic Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Basketball Teams</fullName>
    </customValue>
    <customValue>
        <fullName>Bedroom Stores</fullName>
    </customValue>
    <customValue>
        <fullName>Beverage Industry</fullName>
    </customValue>
    <customValue>
        <fullName>Bicycle Manufacturer</fullName>
    </customValue>
    <customValue>
        <fullName>Book Publishers</fullName>
    </customValue>
    <customValue>
        <fullName>Bookstore</fullName>
    </customValue>
    <customValue>
        <fullName>Bowling Center</fullName>
    </customValue>
    <customValue>
        <fullName>Brewery</fullName>
    </customValue>
    <customValue>
        <fullName>Bread Factories</fullName>
    </customValue>
    <customValue>
        <fullName>Breweries</fullName>
    </customValue>
    <customValue>
        <fullName>Logistics</fullName>
    </customValue>
    <masterLabel>Category3</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HeyJobs_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agency</fullName>
    </customValue>
    <customValue>
        <fullName>Call center</fullName>
    </customValue>
    <customValue>
        <fullName>Headhunter</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>High-End</fullName>
    </customValue>
    <customValue>
        <fullName>Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <customValue>
        <fullName>Production</fullName>
    </customValue>
    <customValue>
        <fullName>Public Sector</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Employment Agencies</fullName>
    </customValue>
    <customValue>
        <fullName>Banking and Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>E-commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Inventory Partner</fullName>
    </customValue>
    <masterLabel>HeyJobs Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Stage_ACM.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot Lost</fullName>
        <isActive>false</isActive>
        <label>Pilot Lost</label>
    </customValue>
    <customValue>
        <fullName>Restart Hunting</fullName>
        <isActive>false</isActive>
        <label>Restart Hunting</label>
    </customValue>
    <customValue>
        <fullName>Blacklist</fullName>
        <isActive>false</isActive>
        <label>Blacklist</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
        <isActive>false</isActive>
        <label>Expansion</label>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
        <isActive>false</isActive>
        <label>Invalid</label>
    </customValue>
    <customValue>
        <fullName>Offline - Pause</fullName>
        <isActive>false</isActive>
        <label>Offline - Pause</label>
    </customValue>
    <customValue>
        <fullName>Hunting Lost</fullName>
        <isActive>false</isActive>
        <label>Hunting Lost</label>
    </customValue>
    <customValue>
        <fullName>Does not exist anymore</fullName>
        <isActive>false</isActive>
        <label>Does not exist anymore</label>
    </customValue>
    <customValue>
        <fullName>Existing Lost</fullName>
        <isActive>false</isActive>
        <label>Existing Lost</label>
    </customValue>
    <masterLabel>Stage_ACM</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_UtilityFunctions.cls
@isTest
private class Test_UtilityFunctions {

    @isTest
    static void testGetRecruiterFirstAndLastName_MultipleString() {
        List<UtilityFunctions.RecruiterDetailsInput> recruiterInputList = new List<UtilityFunctions.RecruiterDetailsInput>();
        UtilityFunctions.RecruiterDetailsInput recruiterInput = new UtilityFunctions.RecruiterDetailsInput();
        recruiterInput.recruiterName = 'John Doe Smith';
        recruiterInputList.add(recruiterInput);
        
        Test.startTest();
        List<UtilityFunctions.RecruiterDetailsOutput> results =
            UtilityFunctions.getRecruiterFirstAndLastName(recruiterInputList);
        Test.stopTest();
        
        System.assertEquals(1, results.size());
        System.assertEquals('John', results[0].recruiterFirstName);
        System.assertEquals('Doe Smith', results[0].recruiterLastName);
    }
    
    @isTest
    static void testGetRecruiterFirstAndLastName_SingleString() {
        List<UtilityFunctions.RecruiterDetailsInput> recruiterInputList = new List<UtilityFunctions.RecruiterDetailsInput>();
        UtilityFunctions.RecruiterDetailsInput recruiterInput = new UtilityFunctions.RecruiterDetailsInput();
        recruiterInput.recruiterName = 'Alexandra';
        recruiterInputList.add(recruiterInput);
        
        Test.startTest();
        List<UtilityFunctions.RecruiterDetailsOutput> results =
            UtilityFunctions.getRecruiterFirstAndLastName(recruiterInputList);
        Test.stopTest();
        
        System.assertEquals(1, results.size());
        System.assertEquals('', results[0].recruiterFirstName);
        System.assertEquals('Alexandra', results[0].recruiterLastName);
    }
    
    @isTest
    static void testUpdateStageACMOnReactivation() {
        Account testAccount = new Account(Name='Test Account', Service_Country__c = 'DE');
        insert testAccount;
        
        Opportunity testOpportunity = new Opportunity(
            Name='Test Opportunity',
            AccountId=testAccount.Id,
            StageName='Closed Lost',
            CloseDate= Date.today()+15
        );
        insert testOpportunity;
        
        List<Opportunity> oppList = new List<Opportunity>{ testOpportunity };
        
        Test.startTest();
        List<Account> updatedAccounts =
            UtilityFunctions.updateStageACMOnReactivation(oppList);
        Test.stopTest();
        
        System.assertEquals(1, updatedAccounts.size());
        System.assertEquals('Prospect', updatedAccounts[0].Stage_ACM__c);
    }

    @isTest
    static void testProcessCategoryAndClientOnAccount() {

        Category3__c cat = new Category3__c(
            Category__c = 'Logistics',
            Reference_Clients__c = 'Deutsche Post',
            HeyJobs_Category__c = 'Logistics'
        );
        insert cat;

        Account acc = new Account(
            Name = 'Acc1',
            Service_Country__c = 'DE',
            Category_1__c = 'Service Provider',
            Category_2__c = 'Transport & Logistics',
            Category_3__c = 'Logistics'
        );
        insert acc;

        Test.startTest();
        UtilityFunctions.processCategoryAndClientOnAccount(new List<Account>{ acc });
        Test.stopTest();

        Account updated = [
            SELECT X2020_Reference_Clients__c, HeyJobs_Category__c
            FROM Account WHERE Id = :acc.Id
        ];

        System.assertEquals('Logistics', updated.X2020_Reference_Clients__c);
        System.assertEquals('Logistics', updated.HeyJobs_Category__c);
    }

    @isTest
    static void testProcessReferenceClientChanges() {

        Category3__c cat = new Category3__c(
            Category__c = 'Logistics',
            Reference_Clients__c = 'OldValue',
            HeyJobs_Category__c = 'Logistics'
        );
        insert cat;

        Account acc = new Account(
            Name = 'Retail Acc',
            Service_Country__c='DE',
            Category_1__c = 'Service Provider',
            Category_2__c = 'Transport & Logistics',
            Category_3__c = 'Logistics'
        );
        insert acc;

        Category3__c changed = new Category3__c(
            Id = cat.Id,
            Category__c = 'Logistics',
            Reference_Clients__c = 'NewClient'
        );

        Test.startTest();
        UtilityFunctions.processReferenceClientChanges(new List<Category3__c>{ changed });
        Test.stopTest();

        Account updated = [
            SELECT X2020_Reference_Clients__c
            FROM Account WHERE Id=:acc.Id
        ];

        System.assertEquals('NewClient', updated.X2020_Reference_Clients__c);
    }
}