force-app/main/default/objects/Account/fields/Category_3__c.field-meta.xml
<CustomField>
    <fullName>Category_3__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertising Agencies</fullName>
            </value>
            <value>
                <fullName>Advertising sales</fullName>
            </value>
            <value>
                <fullName>Agricultural Engineering</fullName>
            </value>
            <value>
                <fullName>Agricultural Machinery</fullName>
            </value>
            <value>
                <fullName>Aircraft manufacturers</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Aluminum Plants</fullName>
            </value>
            <value>
                <fullName>Animal Feed</fullName>
            </value>
            <value>
                <fullName>Animal Hospitals</fullName>
            </value>
            <value>
                <fullName>Animal Shelters</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Associations</fullName>
            </value>
            <value>
                <fullName>Auditors</fullName>
            </value>
            <value>
                <fullName>Car manufacturers</fullName>
            </value>
            <value>
                <fullName>Car Service</fullName>
            </value>
            <value>
                <fullName>Car Suppliers</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Basic Chemicals</fullName>
            </value>
            <value>
                <fullName>Basketball Teams</fullName>
            </value>
            <value>
                <fullName>Bedroom Stores</fullName>
            </value>
            <value>
                <fullName>Beverage Industry</fullName>
            </value>
            <value>
                <fullName>Bicycle Manufacturer</fullName>
            </value>
            <value>
                <fullName>Book Publishers</fullName>
            </value>
            <value>
                <fullName>Bookstore</fullName>
            </value>
            <value>
                <fullName>Bowling Center</fullName>
            </value>
            <value>
                <fullName>Brewery</fullName>
            </value>
            <value>
                <fullName>Bread Factories</fullName>
            </value>
            <value>
                <fullName>Breweries</fullName>
            </value>
            <value>
                <fullName>Medical Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Umbrella_Company__c.field-meta.xml
<CustomField>
    <fullName>Umbrella_Company__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be served as a Parent Account</description>
    <inlineHelpText>Wird verwendet, um einen Salesforce Account als multinationalen Account zu kennzeichnen. Umbrella Companies werden genutzt, um Accounts mit unterschiedlichen Service-Ländern in einer Hierarchie zu kombinieren.</inlineHelpText>
    <label>Umbrella Company</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <description>Accounts that are in Sales Process (Customer Acquisition, Account Management)</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <formula>TEXT(Account.Service_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Customer Acquisition Deals Subscription</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/classes/Test_AccountTriggerFunction.cls
@isTest
public class Test_AccountTriggerFunction {
     
     /**
    @Methodname     : test_accountTrigger
    @Param          : Null
    @Return         : Null
    @Description    : Tests "AccountTriggerFunction" methods - updateSegmentation, heyJobsCategoryOnInsert
    **/
    @isTest static void test_accountTrigger(){
        
        List<Account> accountList = new List<Account>();
        
        Account acc = new Account(
            Name ='Foo',
            NumberOfEmployees = 2500,
            Service_Country__c = 'DE',
            Category_1__c = 'Service Provider',
            Category_2__c = 'Health',
            Category_3__c = 'Medical Services');
        accountList.add(acc);
        
        Test.StartTest();
        insert accountList;
        Test.StopTest();
    }
    
    /**
    @Methodname     : test_
    @Param          : Null
    @Return         : Null
    @Description    : Tests the "AccountTriggerFunction" method - heyJobsCategoryOnUpdate
    **/
    
    
    @isTest static void test_validateUmbrellaCompany(){
        
        Account acc = new Account(
            Name ='Glucklich GmbH',
            NumberOfEmployees = 2500,
            Service_Country__c = 'DE',
            Category_1__c = 'Service Provider',
            Category_2__c = 'Health',
            Category_3__c = 'Medical Services');
         insert acc;
        
        Opportunity opp = new Opportunity(
            Name = 'test',
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId(),
            AccountId = acc.Id,
            StageName = 'Qualified Prospect',
            CloseDate = Date.today() + 180);
        insert opp;
        
        Test.StartTest();
        Account accToEdit = [SELECT Id,Category_3__c FROM Account LIMIT 1];
        accToEdit.Umbrella_Company__c = TRUE;
        
        try {
            update accToEdit;
            Assert.fail('DmlException expected');
        } catch (DmlException e) {
            Assert.isTrue(e.getMessage().contains('Umbrella Company'));
        }
        Test.StopTest();
    }
}