force-app/main/default/objects/Account/fields/Category_3__c.field-meta.xml
<CustomField>
    <fullName>Category_3__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertising Agencies</fullName>
            </value>
            <value>
                <fullName>Advertising sales</fullName>
            </value>
            <value>
                <fullName>Agricultural Engineering</fullName>
            </value>
            <value>
                <fullName>Agricultural Machinery</fullName>
            </value>
            <value>
                <fullName>Aircraft manufacturers</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Aluminum Plants</fullName>
            </value>
            <value>
                <fullName>Animal Feed</fullName>
            </value>
            <value>
                <fullName>Animal Hospitals</fullName>
            </value>
            <value>
                <fullName>Animal Shelters</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Associations</fullName>
            </value>
            <value>
                <fullName>Auditors</fullName>
            </value>
            <value>
                <fullName>Car manufacturers</fullName>
            </value>
            <value>
                <fullName>Car Service</fullName>
            </value>
            <value>
                <fullName>Car Suppliers</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Basic Chemicals</fullName>
            </value>
            <value>
                <fullName>Basketball Teams</fullName>
            </value>
            <value>
                <fullName>Bedroom Stores</fullName>
            </value>
            <value>
                <fullName>Beverage Industry</fullName>
            </value>
            <value>
                <fullName>Bicycle Manufacturer</fullName>
            </value>
            <value>
                <fullName>Book Publishers</fullName>
            </value>
            <value>
                <fullName>Bookstore</fullName>
            </value>
            <value>
                <fullName>Bowling Center</fullName>
            </value>
            <value>
                <fullName>Brewery</fullName>
            </value>
            <value>
                <fullName>Bread Factories</fullName>
            </value>
            <value>
                <fullName>Breweries</fullName>
            </value>
            <value>
                <fullName>Bausparkasse</fullName>
            </value>
            <value>
                <fullName>Butcher</fullName>
            </value>
            <value>
                <fullName>Car Rental</fullName>
            </value>
            <value>
                <fullName>Cash-and-Carry</fullName>
            </value>
            <value>
                <fullName>Caterer</fullName>
            </value>
            <value>
                <fullName>Hospitals</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Computer Games</fullName>
            </value>
            <value>
                <fullName>Confiserie</fullName>
            </value>
            <value>
                <fullName>Consumer Organizations</fullName>
            </value>
            <value>
                <fullName>Contract Manufacturers</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Delicacy</fullName>
            </value>
            <value>
                <fullName>Dental Laboratories</fullName>
            </value>
            <value>
                <fullName>Development Banks</fullName>
            </value>
            <value>
                <fullName>Discounter</fullName>
            </value>
            <value>
                <fullName>Liquor Stores</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Estates</fullName>
            </value>
            <value>
                <fullName>Sparkasse</fullName>
            </value>
            <value>
                <fullName>Financial Funds</fullName>
            </value>
            <value>
                <fullName>Generics</fullName>
            </value>
            <value>
                <fullName>Care Services</fullName>
            </value>
            <value>
                <fullName>Health Food Store</fullName>
            </value>
            <value>
                <fullName>Health Insurance</fullName>
            </value>
            <value>
                <fullName>Hearing Care</fullName>
            </value>
            <value>
                <fullName>Hockey Teams</fullName>
            </value>
            <value>
                <fullName>Household Chemistry</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Insurance Broker</fullName>
            </value>
            <value>
                <fullName>IT Consulting</fullName>
            </value>
            <value>
                <fullName>Laboratories</fullName>
            </value>
            <value>
                <fullName>Leasing</fullName>
            </value>
            <value>
                <fullName>Translation</fullName>
            </value>
            <value>
                <fullName>Management Consultant</fullName>
            </value>
            <value>
                <fullName>Medical Services</fullName>
            </value>
            <value>
                <fullName>Care Homes</fullName>
            </value>
            <value>
                <fullName>Optician</fullName>
            </value>
            <value>
                <fullName>Bio-Stores</fullName>
            </value>
            <value>
                <fullName>Packaging Industry</fullName>
            </value>
            <value>
                <fullName>Paint Manufacturers</fullName>
            </value>
            <value>
                <fullName>Paper Mills</fullName>
            </value>
            <value>
                <fullName>Payment Processor</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical Industry</fullName>
            </value>
            <value>
                <fullName>Pharmacies</fullName>
            </value>
            <value>
                <fullName>Private Banks</fullName>
            </value>
            <value>
                <fullName>Professional Association</fullName>
            </value>
            <value>
                <fullName>Radiology Practices</fullName>
            </value>
            <value>
                <fullName>Headhunter</fullName>
            </value>
            <value>
                <fullName>Rehabilitation clinics</fullName>
            </value>
            <value>
                <fullName>Research Centers</fullName>
            </value>
            <value>
                <fullName>Software Manufacturer</fullName>
            </value>
            <value>
                <fullName>Supermarkets</fullName>
            </value>
            <value>
                <fullName>Temporary Employment Agencies</fullName>
            </value>
            <value>
                <fullName>Tester</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Wine Merchant</fullName>
            </value>
            <value>
                <fullName>Wholesale Cleaning</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Investors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/HeyJobs_Category__c.field-meta.xml
<CustomField>
    <fullName>HeyJobs_Category__c</fullName>
    <description>Sector in Tableau/DWH</description>
    <inlineHelpText>HeyJobs spezifische Segregation der Kund*innen, basiert auf Category 1, 2 &amp; 3. Entspricht den Sektoren in Tableau/DWH.</inlineHelpText>
    <label>HeyJobs - Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Call center</fullName>
            </value>
            <value>
                <fullName>Headhunter</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>High-End</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Temporary Employment Agencies</fullName>
            </value>
            <value>
                <fullName>Banking and Insurance</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Inventory Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/X2020_Reference_Clients__c.field-meta.xml
<CustomField>
    <fullName>X2020_Reference_Clients__c</fullName>
    <description>used for hubspot email campaigns</description>
    <inlineHelpText>Zeigt potentielle Referenzkund*innen, die ähnlich zum vorliegenden Account sind.</inlineHelpText>
    <label>Reference Clients</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Research.recordType-meta.xml
<RecordType>
    <fullName>Research</fullName>
    <active>true</active>
    <description>Accounts that are in Research (Taskdrive, B2B Marketing)</description>
    <label>Research</label>
</RecordType>

force-app/main/default/classes/Test_UpdateCategoryOnAccountBatch.cls
@isTest
public class Test_UpdateCategoryOnAccountBatch {
    @isTest static void test1() {
        List<Account> accList = new List<Account>();
        
        List<string> cat3forIT = new list<string>{'Auditors','Computer Games','Call Center','Lawyer','Engineering','Estates','IT Consulting','Job Promotion','Translation','Management Consultant','Headhunter','Research Centers','Software Manufacturer','Temporary Employment Agencies','Tester','Training'};
        for(integer i = 0; i < 16; i++) {
            Account acc = new Account();
            acc.Name = 'TestIT'+i;
            acc.Category_1__c = 'Service Provider';
            acc.Category_2__c = 'Consultant & IT';
            accList.add(acc); 
        }
        
        List<string> cat3forFin = new list<string>{'Banks','Bausparkasse','Collection','Consumer Organizations','Development Banks','Sparkasse','Financial Funds','Insurance','Insurance Broker','Leasing','Payment Processor','Private Banks','Professional Association','Trustee','Investors'};
        for(integer i = 0; i < 15; i++) {
            Account acc = new Account();
            acc.Name = 'TestFin'+i;
            acc.Category_1__c = 'Service Provider';
            acc.Category_2__c = 'Finance & Insurance';
            acc.Category_3__c = cat3forFin[i];
            accList.add(acc); 
        }
        
        List<string> cat3forIndustry = new list<string>{'Basic Chemicals','Contract Manufacturers','Generics','Household Chemistry','Packaging Industry','Paint Manufacturers','Paper Mills','Pharmaceutical Industry'};
        for(integer i = 0; i < 8; i++) {
            Account acc = new Account();
            acc.Name = 'TestChem'+i;
            acc.Category_1__c = 'Industry';
            acc.Category_2__c = 'Chemical Industry';
            acc.Category_3__c = cat3forIndustry[i];
            accList.add(acc); 
        }
        
        List<string> cat3forHealth = new list<string>{'Hospitals','Dental Laboratories','Care Services','Health Insurance','Hearing Care','Laboratories','Medical Services','Care Homes','Optician','Pharmacies','Radiology Practices','Rehabilitation clinics'};
        for(integer i = 0; i < 12; i++) {
            Account acc = new Account();
            acc.Name = 'TestHealth'+i;
            acc.Category_1__c = 'Service Provider';
            acc.Category_2__c = 'Health';
            acc.Category_3__c = cat3forHealth[i];
            accList.add(acc); 
        }
        
        List<string> cat3forFood = new list<string>{'Bakery','Butcher','Cash-and-Carry','Confiserie','Delicacy','Discounter','Liquor Stores','Health Food Store','Bio-Stores','Supermarkets','Wine Merchant',''};
        for(integer i = 0; i < 11; i++) {
            Account acc = new Account();
            acc.Name = 'TestFood'+i;
            acc.Category_1__c = 'Retail';
            acc.Category_2__c = 'Food Stores';
            acc.Category_3__c = cat3forFood[i];
            accList.add(acc); 
        }
        
        List<string> cat3forAir = new list<string>{'Airlines','Caterer','Car Rental'};
        for(integer i = 0; i < 3; i++) {
            Account acc = new Account();
            acc.Name = 'TestAir'+i;
            acc.Category_1__c = 'Service Provider';
            acc.Category_2__c = 'Gastronomy & Tourism';
            acc.Category_3__c = cat3forAir[i];
            accList.add(acc); 
        }
        
        Account acc = new Account();
        acc.Name = 'Test';
        acc.Category_1__c = 'Service Provider';
        acc.Category_2__c = 'Leisure & Entertainment';
        acc.Category_3__c = 'Hockey Teams';
        accList.add(acc);
        
        Account acc2 = new Account();
        acc2.Name = 'Test22';
        acc2.Category_1__c = 'Retail';
        acc2.Category_2__c = 'Food Stores';
        acc2.Category_3__c = 'Delicacy';
        accList.add(acc2);
        
        Account acc3 = new Account();
        acc3.Name = 'Test33';
        acc3.Category_1__c = 'Industry';
        acc3.Category_2__c = 'Wholesale';
        acc3.Category_3__c = 'Builder\'s Merchant';
        accList.add(acc3);
        
        Account acc4 = new Account();
        acc4.Name = 'Test44';
        acc4.Category_1__c = 'Industry';
        acc4.Category_2__c = 'Wholesale';
        acc4.Category_3__c = 'Wholesale Cleaning';
        accList.add(acc4);

        for(Account ac : accList){
            ac.NumberOfEmployees = 2400;
            ac.Service_Country__c ='DE';
        }
        
        insert accList;
        
        Test.startTest();
        String query = 'SELECT Id, Name, Category_3__c, HeyJobs_Category__c, X2020_Reference_Clients__c, RecordType.Name FROM Account WHERE Category_3__c != null';
        Database.executeBatch(new UpdateCategoryOnAccountBatch(query));
        Test.stopTest();
    }
}