force-app/main/default/objects/Account/fields/Category_3__c.field-meta.xml
<CustomField>
    <fullName>Category_3__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advertising Agencies</fullName>
            </value>
            <value>
                <fullName>Advertising sales</fullName>
            </value>
            <value>
                <fullName>Agricultural Engineering</fullName>
            </value>
            <value>
                <fullName>Agricultural Machinery</fullName>
            </value>
            <value>
                <fullName>Aircraft manufacturers</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Aluminum Plants</fullName>
            </value>
            <value>
                <fullName>Animal Feed</fullName>
            </value>
            <value>
                <fullName>Animal Hospitals</fullName>
            </value>
            <value>
                <fullName>Animal Shelters</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Associations</fullName>
            </value>
            <value>
                <fullName>Auditors</fullName>
            </value>
            <value>
                <fullName>Car manufacturers</fullName>
            </value>
            <value>
                <fullName>Car Service</fullName>
            </value>
            <value>
                <fullName>Car Suppliers</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Basic Chemicals</fullName>
            </value>
            <value>
                <fullName>Basketball Teams</fullName>
            </value>
            <value>
                <fullName>Bedroom Stores</fullName>
            </value>
            <value>
                <fullName>Beverage Industry</fullName>
            </value>
            <value>
                <fullName>Bicycle Manufacturer</fullName>
            </value>
            <value>
                <fullName>Book Publishers</fullName>
            </value>
            <value>
                <fullName>Bookstore</fullName>
            </value>
            <value>
                <fullName>Bowling Center</fullName>
            </value>
            <value>
                <fullName>Brewery</fullName>
            </value>
            <value>
                <fullName>Bread Factories</fullName>
            </value>
            <value>
                <fullName>Breweries</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/HeyJobs_Category__c.field-meta.xml
<CustomField>
    <fullName>HeyJobs_Category__c</fullName>
    <description>Sector in Tableau/DWH</description>
    <inlineHelpText>HeyJobs spezifische Segregation der Kund*innen, basiert auf Category 1, 2 &amp; 3. Entspricht den Sektoren in Tableau/DWH.</inlineHelpText>
    <label>HeyJobs - Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Call center</fullName>
            </value>
            <value>
                <fullName>Headhunter</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>High-End</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Temporary Employment Agencies</fullName>
            </value>
            <value>
                <fullName>Banking and Insurance</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Inventory Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Stage_ACM__c.field-meta.xml
<CustomField>
    <fullName>Stage_ACM__c</fullName>
    <defaultValue>&apos;Prospect&apos;</defaultValue>
    <inlineHelpText>Definiert, wo sich der Account derzeit in unserem Verkaufsprozess befindet.
Finde die genauen Stage-Definitionen hier: https://heyjobs.atlassian.net/wiki/spaces/EO/pages/2155217116/Salesforce+Accounts+Definition+und+Use-Case#Account-Lifecycle-Stage</inlineHelpText>
    <label>Account Lifecycle Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage_ACM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Timestamp_Reactivation__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Reactivation__c</fullName>
    <description>This field shows the timestamp of re-visiting this account after the last opp-lost for further contact</description>
    <label>Legacy Timestamp Reactivation</label>
    <summarizedField>Opportunity.Timestamp_Reactivation__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.plLossReason__c</field>
        <operation>notEqual</operation>
        <value>Admin Only: Clean-Up Sales Funnel</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/X2020_Reference_Clients__c.field-meta.xml
<CustomField>
    <fullName>X2020_Reference_Clients__c</fullName>
    <description>used for hubspot email campaigns</description>
    <inlineHelpText>Zeigt potentielle Referenzkund*innen, die ähnlich zum vorliegenden Account sind.</inlineHelpText>
    <label>Reference Clients</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category3__c/Category3__c.object-meta.xml
<CustomObject>
    <label>Customer Category</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Category Mapping Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category3__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Category3__c/fields/HeyJobs_Category__c.field-meta.xml
<CustomField>
    <fullName>HeyJobs_Category__c</fullName>
    <label>HeyJobs Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HeyJobs_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Category3__c/fields/Reference_Clients__c.field-meta.xml
<CustomField>
    <fullName>Reference_Clients__c</fullName>
    <label>Reference Clients</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Reactivation__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Reactivation__c</fullName>
    <description>Reactivation timestamp after the opportunity is lost.</description>
    <label>Timestamp Reactivation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Category3.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Advertising Agencies</fullName>
    </customValue>
    <customValue>
        <fullName>Advertising sales</fullName>
    </customValue>
    <customValue>
        <fullName>Agricultural Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Agricultural Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>Aircraft manufacturers</fullName>
    </customValue>
    <customValue>
        <fullName>Airlines</fullName>
    </customValue>
    <customValue>
        <fullName>Airports</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminum Plants</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Feed</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Hospitals</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Shelters</fullName>
    </customValue>
    <customValue>
        <fullName>Architects</fullName>
    </customValue>
    <customValue>
        <fullName>Associations</fullName>
    </customValue>
    <customValue>
        <fullName>Auditors</fullName>
    </customValue>
    <customValue>
        <fullName>Car manufacturers</fullName>
    </customValue>
    <customValue>
        <fullName>Car Service</fullName>
    </customValue>
    <customValue>
        <fullName>Car Suppliers</fullName>
    </customValue>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Banks</fullName>
    </customValue>
    <customValue>
        <fullName>Basic Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Basketball Teams</fullName>
    </customValue>
    <customValue>
        <fullName>Bedroom Stores</fullName>
    </customValue>
    <customValue>
        <fullName>Beverage Industry</fullName>
    </customValue>
    <customValue>
        <fullName>Bicycle Manufacturer</fullName>
    </customValue>
    <customValue>
        <fullName>Book Publishers</fullName>
    </customValue>
    <customValue>
        <fullName>Bookstore</fullName>
    </customValue>
    <customValue>
        <fullName>Bowling Center</fullName>
    </customValue>
    <customValue>
        <fullName>Brewery</fullName>
    </customValue>
    <customValue>
        <fullName>Bread Factories</fullName>
    </customValue>
    <customValue>
        <fullName>Breweries</fullName>
    </customValue>
    <masterLabel>Category3</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/HeyJobs_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agency</fullName>
    </customValue>
    <customValue>
        <fullName>Call center</fullName>
    </customValue>
    <customValue>
        <fullName>Headhunter</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>High-End</fullName>
    </customValue>
    <customValue>
        <fullName>Logistics</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <customValue>
        <fullName>Production</fullName>
    </customValue>
    <customValue>
        <fullName>Public Sector</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Services</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Employment Agencies</fullName>
    </customValue>
    <customValue>
        <fullName>Banking and Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>E-commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Inventory Partner</fullName>
    </customValue>
    <masterLabel>HeyJobs Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Stage_ACM.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot Lost</fullName>
        <isActive>false</isActive>
        <label>Pilot Lost</label>
    </customValue>
    <customValue>
        <fullName>Restart Hunting</fullName>
        <isActive>false</isActive>
        <label>Restart Hunting</label>
    </customValue>
    <customValue>
        <fullName>Blacklist</fullName>
        <isActive>false</isActive>
        <label>Blacklist</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
        <isActive>false</isActive>
        <label>Expansion</label>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
        <isActive>false</isActive>
        <label>Invalid</label>
    </customValue>
    <customValue>
        <fullName>Offline - Pause</fullName>
        <isActive>false</isActive>
        <label>Offline - Pause</label>
    </customValue>
    <customValue>
        <fullName>Hunting Lost</fullName>
        <isActive>false</isActive>
        <label>Hunting Lost</label>
    </customValue>
    <customValue>
        <fullName>Does not exist anymore</fullName>
        <isActive>false</isActive>
        <label>Does not exist anymore</label>
    </customValue>
    <customValue>
        <fullName>Existing Lost</fullName>
        <isActive>false</isActive>
        <label>Existing Lost</label>
    </customValue>
    <masterLabel>Stage_ACM</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UtilityFunctions.cls
/*
*      @author Arun Kumar
*      @date   03-Aug-2022
*      @description   Utility Class to store reusable business logics
*
*      Modification Log:
*      ------------------------------------------------------------------------------------
*      Developer        Date            Description
*      ------------------------------------------------------------------------------------
*       Arun Kumar      29.08.2023      Created processCategoryAndClientOnAccount() for RO-1525
*       Arun Kumar      29.08.2023      Created processReferenceClientChanges() for RO-1525
*       Arun Kumar      29.08.2023      Created processAccountHappinessChanges() for RO-1570
*       Arun Kumar      15.04.2024      Created getRecruiterFirstAndLastName() for RO-1952
*/

public with sharing class UtilityFunctions {
    
    /**
@Methodname     : updateStageACMOnReactivation
@Param          : List<Opportunity>
@Return         : List<Account>
@Description    : To update the Stage_ACM__c field on Account based on the Timestamp_Reactivation__c on opportunity
**/
    public static List<Account> updateStageACMOnReactivation(List<Opportunity> oppList){
        
        //Fetch the Closed Lost opportunities
        Set<Id> accountIdSet = new Set<Id>();
        List<Account> accountList = new List<Account>();
        
        if(!oppList.isEmpty()){
            for(Opportunity opp : oppList){
                accountIdSet.add(opp.AccountId);
            }
        }
        
        //Approach 1
        if(!accountIdSet.isEmpty()){
            for(Account acc: [SELECT Id, Stage_ACM__c FROM Account WHERE Id =: accountIdSet]){
                acc.Stage_ACM__c = 'Prospect';
                accountList.add(acc);
            }
        }
        
        return accountList;
    }
    
    
    /**
@Methodname     : processCategoryAndClientOnAccount
@Param          : List<Account>
@Return         : List<Account>
@Description    : To update the HeyJobs_Category__c and X2020_Reference_Clients__c field on Account based on the Category_3__c
**/
    public static void processCategoryAndClientOnAccount(List<Account> accountList){
        
        Set<String> categorySet = new Set<String>();
        List<Account> categorisedAccList = new List<Account>();
        List<Category3__c> categoryList = new List<Category3__c>();
        
        for(Account acc : accountList){
            categorySet.add(acc.Category_3__c);
        }
        
        if(!categorySet.isEmpty()){
            categoryList = [SELECT Category__c, Reference_Clients__c, HeyJobs_Category__c  FROM Category3__c WHERE Category__c IN :categorySet];
        }
        
        if(!categoryList.isEmpty()){
            for(Account acc : accountList){
                for(Category3__c ct : categoryList){
                    if(ct.Category__c == acc.Category_3__c){
                        acc.X2020_Reference_Clients__c = ct.Category__c;
                        acc.HeyJobs_Category__c = ct.HeyJobs_Category__c;
                        categorisedAccList.add(acc);
                    }
                }  
            }
        }
        
        if(!categorisedAccList.isEmpty()){
            try{
                update categorisedAccList;
            }catch(Exception e){
                System.debug('Error while updating Heyjobs category and reference clients on account');
            }
        }
    }
    
    /**
@Methodname     : processReferenceClientChanges
@Param          : List<Category3__c>
@Return         : List<Account>
@Description    : To update the X2020_Reference_Clients__c field on Account based on the latest changes in the Reference client values
**/
    public static void processReferenceClientChanges (List<Category3__c> changedCategoryList){
        
        Set<String> accCategorySet = new Set<String>();
        List<Account> accList = new List<Account>();
        Map<String, String> categoryVsNewReferenceMap = new Map<String, String>();
        
        for(Category3__c ctry : changedCategoryList){
            accCategorySet.add(ctry.Category__c);
            categoryVsNewReferenceMap.put(ctry.Category__c, ctry.Reference_Clients__c);
        }
        
        if(!accCategorySet.isEmpty()){
            for(Account acc : [SELECT Id, Category_3__c, HeyJobs_Category__c, X2020_Reference_Clients__c FROM Account WHERE Category_3__c IN :accCategorySet]){
                if(acc.Category_3__c != NULL && !categoryVsNewReferenceMap.isEmpty() && categoryVsNewReferenceMap.containsKey(acc.Category_3__c)){
                    acc.X2020_Reference_Clients__c = categoryVsNewReferenceMap.get(acc.Category_3__c);
                    accList.add(acc);
                }
            }
        }
        
        if(!accList.isEmpty()){
            try{
                update accList;
            }catch(Exception e){
                System.debug('Error while updating reference clients');
            }
        }
    }
    
    
    
     /**
@Methodname     : getRecruiterFirstAndLastName
@Param          : List<RecruiterDetailsInput>
@Return         : List<RecruiterDetailsOutput>
@Description    : Based on the input from the flow, this method splits the recruiter name to FirstName and LastName
**/

    @InvocableMethod(Label = 'Get Recruiter First and Last Name')
    public static List<RecruiterDetailsOutput> getRecruiterFirstAndLastName(List<RecruiterDetailsInput> recruiterInputList){
        List<RecruiterDetailsOutput> firstAndLastNameList = new List<RecruiterDetailsOutput>();
        
        for (RecruiterDetailsInput input : recruiterInputList) {
            if (String.isNotBlank(input.recruiterName)) {
                String[] nameParts = input.recruiterName.trim().split('\\s+');
                RecruiterDetailsOutput output = new RecruiterDetailsOutput();
                if(nameParts.size() > 1) {
                    output.recruiterFirstName = nameParts[0];
                    output.recruiterLastName = '';
                    for (Integer i = 1; i < nameParts.size(); i++) {
                        output.recruiterLastName += (String.isEmpty(output.recruiterLastName) ? '' : ' ') + nameParts[i];
                    }
                }else if(nameParts.size() == 1){
                    output.recruiterFirstName = '';
                    output.recruiterLastName = nameParts[0];
                }
                firstAndLastNameList.add(output);
            } else {
                continue;
            }
        }
        return firstAndLastNameList;
    }
    
    public class RecruiterDetailsInput {
        @InvocableVariable
        public String recruiterName;
    }
    
    public class RecruiterDetailsOutput {
        @InvocableVariable
        public String recruiterFirstName;
        @InvocableVariable
        public String recruiterLastName;
    }
}