force-app/main/default/objects/Account/fields/Competitor_1_current_future__c.field-meta.xml
<CustomField>
    <fullName>Competitor_1_current_future__c</fullName>
    <description>RO-2315</description>
    <inlineHelpText>Welche Rekrutierungslösungen werden derzeit eingesetzt oder für die Zukunft in Betracht gezogen?
Erfasst die Rekrutierungslösungen, die von potenziellen Kunden derzeit genutzt werden oder in der Zukunft in Betracht gezogen werden.</inlineHelpText>
    <label>Competitor 1: current &amp; future</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GTM_Motion_Account__c.field-meta.xml
<CustomField>
    <fullName>GTM_Motion_Account__c</fullName>
    <description>RO - 1958</description>
    <inlineHelpText>Das GTM Motion zeigt an, in welchem Motion (Segment) sich ein Account befindet oder zugeordnet werden sollte. Hier findest du mehr Informationen zu den GTM Motion.</inlineHelpText>
    <label>GTM Motion Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GTM_Motion_values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/HeyJobs_Category__c.field-meta.xml
<CustomField>
    <fullName>HeyJobs_Category__c</fullName>
    <description>Sector in Tableau/DWH</description>
    <inlineHelpText>HeyJobs spezifische Segregation der Kund*innen, basiert auf Category 1, 2 &amp; 3. Entspricht den Sektoren in Tableau/DWH.</inlineHelpText>
    <label>HeyJobs - Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Call center</fullName>
            </value>
            <value>
                <fullName>Headhunter</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>High-End</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Temporary Employment Agencies</fullName>
            </value>
            <value>
                <fullName>Banking and Insurance</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Inventory Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/plOpenJobs__c.field-meta.xml
<CustomField>
    <fullName>plOpenJobs__c</fullName>
    <inlineHelpText>Dieses Feld erfasst die Gesamtanzahl der aktuell offenen Stellen im gesamten Unternehmen. 
(Bitte beachte: Es geht nicht um die im Meeting besprochenen Stellen, sondern um die Gesamtzahl aller offenen Positionen, wie sie beispielsweise auf der Karriereseite angegeben sind.)</inlineHelpText>
    <label>Open Jobs</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1-4</fullName>
            </value>
            <value>
                <fullName>5-9</fullName>
            </value>
            <value>
                <fullName>10-19</fullName>
            </value>
            <value>
                <fullName>20-49</fullName>
            </value>
            <value>
                <fullName>50-99</fullName>
            </value>
            <value>
                <fullName>100-249</fullName>
            </value>
            <value>
                <fullName>250-499</fullName>
            </value>
            <value>
                <fullName>500-1000</fullName>
            </value>
            <value>
                <fullName>&gt;1000</fullName>
            </value>
            <value>
                <fullName>0-10</fullName>
                <isActive>false</isActive>
                <label>0-10</label>
            </value>
            <value>
                <fullName>1.000</fullName>
                <isActive>false</isActive>
                <label>1.000</label>
            </value>
            <value>
                <fullName>10-50</fullName>
                <isActive>false</isActive>
                <label>10-50</label>
            </value>
            <value>
                <fullName>10.0</fullName>
                <isActive>false</isActive>
                <label>10.0</label>
            </value>
            <value>
                <fullName>100-250</fullName>
                <isActive>false</isActive>
                <label>100-250</label>
            </value>
            <value>
                <fullName>3</fullName>
                <isActive>false</isActive>
                <label>3</label>
            </value>
            <value>
                <fullName>50-100</fullName>
                <isActive>false</isActive>
                <label>50-100</label>
            </value>
            <value>
                <fullName>500-1.000</fullName>
                <isActive>false</isActive>
                <label>500-1.000</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>6</label>
            </value>
            <value>
                <fullName>8</fullName>
                <isActive>false</isActive>
                <label>8</label>
            </value>
            <value>
                <fullName>&lt;10</fullName>
                <isActive>false</isActive>
                <label>&lt;10</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <description>RO-177</description>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Stage_ACM__c.field-meta.xml
<CustomField>
    <fullName>Stage_ACM__c</fullName>
    <defaultValue>&apos;Prospect&apos;</defaultValue>
    <inlineHelpText>Definiert, wo sich der Account derzeit in unserem Verkaufsprozess befindet.
Finde die genauen Stage-Definitionen hier: https://heyjobs.atlassian.net/wiki/spaces/EO/pages/2155217116/Salesforce+Accounts+Definition+und+Use-Case#Account-Lifecycle-Stage</inlineHelpText>
    <label>Account Lifecycle Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage_ACM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Outbound.recordType-meta.xml
<RecordType>
    <fullName>Outbound</fullName>
    <active>true</active>
    <description>Accounts that are in outbound marketing (B2B Marketing)</description>
    <label>Outbound</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <description>Accounts that are in Sales Process (Customer Acquisition, Account Management)</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Competitor_1_current_future__c.field-meta.xml
<CustomField>
    <fullName>Competitor_1_current_future__c</fullName>
    <description>RO-2093</description>
    <inlineHelpText>Welche Rekrutierungslösungen werden derzeit eingesetzt oder für die Zukunft in Betracht gezogen?</inlineHelpText>
    <label>Competitor 1: current &amp; future</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GTM_Motion_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>GTM_Motion_Opportunity__c</fullName>
    <description>RO - 1958</description>
    <inlineHelpText>Das GTM Motion zeigt an, zu welcher Motion (Segment) ein Opportunity gehört. Das Feld wird mit der GTM Motion auf Account aligned, so lange die Opportunity offen ist. Nach dem schließen der Opportunity kann der Wert nicht mehr verändert werden.</inlineHelpText>
    <label>GTM Motion Opportunity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GTM_Motion_values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Creation_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Creation_Trigger__c</fullName>
    <label>Opportunity Creation Trigger</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Origins</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/plLossReason__c.field-meta.xml
<CustomField>
    <fullName>plLossReason__c</fullName>
    <description>should be filled to later understand why we lose certain clients</description>
    <inlineHelpText>Jede Opportunity in Stage=&quot;Closed Lost&quot;, also gelostete Opportunity, sollte einen Lost Reason besitzen. Mehr Informationen zu den einzelnen Lost Reasons finden du auf Confluence. 
Eine spätere Analyse warum die Opportunities verloren worden sind, ist nützlich um gegebenenfalls Anpassungen am Sales Prozess oder Produkt vorzunehmen.</inlineHelpText>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currently not hiring</fullName>
            </value>
            <value>
                <fullName>Currently no budget available</fullName>
            </value>
            <value>
                <fullName>Currently no focus jobs</fullName>
            </value>
            <value>
                <fullName>Not happy with price</fullName>
            </value>
            <value>
                <fullName>Not happy with selection of features</fullName>
            </value>
            <value>
                <fullName>Not happy with job performance</fullName>
            </value>
            <value>
                <fullName>Not happy with candidate quality</fullName>
            </value>
            <value>
                <fullName>No need for paid recruiting measures</fullName>
            </value>
            <value>
                <fullName>All contacts are ghosting</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Bankrupt</fullName>
            </value>
            <value>
                <fullName>Dependent on decision at different corporate level</fullName>
            </value>
            <value>
                <fullName>Dependent on ATS integration</fullName>
            </value>
            <value>
                <fullName>Already won in SSSU Process</fullName>
            </value>
            <value>
                <fullName>Duplicate Opportunity</fullName>
            </value>
            <value>
                <fullName>Special Case</fullName>
            </value>
            <value>
                <fullName>Sonderkündigungsrecht used</fullName>
                <label>Sonderkündigungsrecht used (REACH only)</label>
            </value>
            <value>
                <fullName>Admin Only: Opp lost due to inactivity</fullName>
            </value>
            <value>
                <fullName>Admin Only: Clean-Up Sales Funnel</fullName>
            </value>
            <value>
                <fullName>Jobseeker_SSSU_only</fullName>
                <label>(SSSU only) Jobseeker</label>
            </value>
            <value>
                <fullName>Fraudulent_SSSU_only</fullName>
                <label>(SSSU only) Fraudulent</label>
            </value>
            <value>
                <fullName>#N/A​</fullName>
                <isActive>false</isActive>
                <label>#N/A​</label>
            </value>
            <value>
                <fullName>1_No Open Jobs</fullName>
                <isActive>false</isActive>
                <label>1_No Open Jobs</label>
            </value>
            <value>
                <fullName>2_Never paying for recruiting</fullName>
                <isActive>false</isActive>
                <label>2_Never paying for recruiting</label>
            </value>
            <value>
                <fullName>3_Happy with competitor solution (which?)</fullName>
                <isActive>false</isActive>
                <label>3_Happy with competitor solution (which?)</label>
            </value>
            <value>
                <fullName>4_Doing same service inhouse</fullName>
                <isActive>false</isActive>
                <label>4_Doing same service inhouse</label>
            </value>
            <value>
                <fullName>5_TRY CEO MAILING</fullName>
                <isActive>false</isActive>
                <label>5_TRY CEO MAILING</label>
            </value>
            <value>
                <fullName>6_Rejected by HeyJobs (inbound)</fullName>
                <isActive>false</isActive>
                <label>6_Rejected by HeyJobs (inbound)</label>
            </value>
            <value>
                <fullName>7_Not reached after 13 attempts</fullName>
                <isActive>false</isActive>
                <label>7_Not reached after 13 attempts</label>
            </value>
            <value>
                <fullName>8_CleaningOut</fullName>
                <isActive>false</isActive>
                <label>8_CleaningOut</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <formula>TEXT(Account.Service_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Customer Acquisition Deals Subscription</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Sales_Transactional.recordType-meta.xml
<RecordType>
    <fullName>Sales_Transactional</fullName>
    <active>true</active>
    <businessProcess>Sales Transactional</businessProcess>
    <description>Customer Acquisition Deals Transactional</description>
    <label>Sales Transactional</label>
</RecordType>

force-app/main/default/globalValueSets/Competitors.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Stepstone</fullName>
    </customValue>
    <customValue>
        <fullName>Indeed</fullName>
    </customValue>
    <customValue>
        <fullName>Karriere.at</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIn</fullName>
    </customValue>
    <customValue>
        <fullName>Xing/onlyfy</fullName>
    </customValue>
    <customValue>
        <fullName>Stellenanzeigen.de</fullName>
    </customValue>
    <customValue>
        <fullName>Talent.com</fullName>
    </customValue>
    <customValue>
        <fullName>Kleinanzeigen</fullName>
    </customValue>
    <customValue>
        <fullName>Agentur für Arbeit</fullName>
    </customValue>
    <customValue>
        <fullName>Monster</fullName>
    </customValue>
    <customValue>
        <fullName>Agentur</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <label>No Competitors</label>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>RO-2093</description>
    <masterLabel>Competitors</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/GTM_Motion_values.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Inside Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Subscription New Business</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise New Business</fullName>
    </customValue>
    <customValue>
        <fullName>Subscription Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Inventory Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Expansion</fullName>
        <isActive>false</isActive>
        <label>Enterprise Expansion</label>
    </customValue>
    <customValue>
        <fullName>Subscription Expansion</fullName>
        <isActive>false</isActive>
        <label>Subscription Expansion</label>
    </customValue>
    <description>RO - 1958</description>
    <masterLabel>GTM Motion values</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Opportunity_Origins.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1. Lifecycle change: Opportunity Handler</fullName>
    </customValue>
    <customValue>
        <fullName>2. Auto ClosedWon</fullName>
    </customValue>
    <customValue>
        <fullName>3. HeyPaket Auto Close Won</fullName>
    </customValue>
    <customValue>
        <fullName>4. HeyPaket Auto Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>5. SSSU Opportunity Creation</fullName>
    </customValue>
    <customValue>
        <fullName>6. Opportunity Handler: Email Labelling</fullName>
    </customValue>
    <description>To track which Opps created an opportunity</description>
    <masterLabel>Opportunity Origins</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Stage_ACM.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot Lost</fullName>
        <isActive>false</isActive>
        <label>Pilot Lost</label>
    </customValue>
    <customValue>
        <fullName>Restart Hunting</fullName>
        <isActive>false</isActive>
        <label>Restart Hunting</label>
    </customValue>
    <customValue>
        <fullName>Blacklist</fullName>
        <isActive>false</isActive>
        <label>Blacklist</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
        <isActive>false</isActive>
        <label>Expansion</label>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
        <isActive>false</isActive>
        <label>Invalid</label>
    </customValue>
    <customValue>
        <fullName>Offline - Pause</fullName>
        <isActive>false</isActive>
        <label>Offline - Pause</label>
    </customValue>
    <customValue>
        <fullName>Hunting Lost</fullName>
        <isActive>false</isActive>
        <label>Hunting Lost</label>
    </customValue>
    <customValue>
        <fullName>Does not exist anymore</fullName>
        <isActive>false</isActive>
        <label>Does not exist anymore</label>
    </customValue>
    <customValue>
        <fullName>Existing Lost</fullName>
        <isActive>false</isActive>
        <label>Existing Lost</label>
    </customValue>
    <masterLabel>Stage_ACM</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/test_batchAutoCloseOpps.cls
@isTest
public class test_batchAutoCloseOpps {
    @isTest
    static void testBatchAutoCloseOpps() {
        // Retrieve necessary record type IDs
        Id oppSalesRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Sales').getRecordTypeId();
        Id oppTransactionalRT = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Sales_Transactional').getRecordTypeId();
        Id accOutboundRT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Outbound').getRecordTypeId();

        // Create test accounts
        Account testAcct1 = new Account(
            Name = 'Auto Closing Sales Account 1',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Sales').getRecordTypeId(),
            Service_Country__c = 'DE',
            HeyJobs_Category__c = 'Logistics',
            NumberOfEmployees = 1234,
            plOpenJobs__c = '5-9',
            GTM_Motion_Account__c = 'Subscription New Business'
        );

        Account testAcct2 = new Account(
            Name = 'Auto Closing Sales Account 2',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Sales').getRecordTypeId(),
            Service_Country__c = 'DE',
            HeyJobs_Category__c = 'Logistics',
            NumberOfEmployees = 234,
            plOpenJobs__c = '5-9',
            GTM_Motion_Account__c = 'Inside Sales'
        );

        insert new List<Account>{testAcct1, testAcct2};

        // Create test opportunities
        List<Opportunity> testOpps = new List<Opportunity>{
            new Opportunity(Name = 'Test_ToBeClosed', RecordTypeId = oppTransactionalRT, StageName = 'Ready for Sales', CloseDate = Date.today(), Competitor_1_current_future__c = 'None', AccountId = testAcct1.Id),
            new Opportunity(Name = 'Test_TooYoung', RecordTypeId = oppSalesRT, StageName = 'Not reached yet', CloseDate = Date.today(), AccountId = testAcct2.Id, Opportunity_Creation_Trigger__c = '2. Auto ClosedWon'),
            new Opportunity(Name = 'Test_ToBeClosed_NoTrigger', RecordTypeId = oppSalesRT, StageName = 'Not reached yet', CloseDate = Date.today(), AccountId = testAcct2.Id),
            new Opportunity(Name = 'Test_EnterpriseNewBusiness', RecordTypeId = oppSalesRT, StageName = 'Not reached yet', CloseDate = Date.today(), AccountId = testAcct2.Id, Opportunity_Creation_Trigger__c = '2. Auto ClosedWon', GTM_Motion_Opportunity__c = 'Enterprise New Business')
        };

        insert testOpps;

        // Modify Created Dates
        Integer oppThresholdAge1 = Integer.valueOf(Label.HouseKeeping_OppLosingThreshold); // 30 days
        Integer oppThresholdAge2 = Integer.valueOf(Label.HouseKeeping_UploadOppLosingThreshold); // 60 days
        DateTime thresholdDateTime1 = DateTime.now().addDays(-oppThresholdAge1);
        DateTime thresholdDateTime2 = DateTime.now().addDays(-oppThresholdAge2);
        Test.setCreatedDate(testOpps[0].Id, thresholdDateTime1.addDays(-31)); // 31 days old
        Test.setCreatedDate(testOpps[1].Id, thresholdDateTime1.addDays(1));  // 29 days old
        Test.setCreatedDate(testOpps[2].Id, thresholdDateTime2.addDays(-1)); // 61 days old
        Test.setCreatedDate(testOpps[3].Id, thresholdDateTime1.addDays(-1)); // 31 days old

        Test.startTest();
        Database.executeBatch(new batchAutoCloseOpps());
        Test.stopTest();

        // Re-query all Opportunities after batch execution for fresh data
        List<Opportunity> refreshedTestOpps = [
            SELECT Id, Record_Type__c, StageName, plLossReason__c, Account.OwnerId, Account.RecordTypeId, Account.Stage_ACM__c, GTM_Motion_Opportunity__c
            FROM Opportunity
            WHERE Id IN :testOpps
        ];

        // Assertions
        for (Opportunity opp : refreshedTestOpps) {
            if (opp.Id == testOpps[0].Id || opp.Id == testOpps[2].Id) {
                System.assertEquals('Closed Lost', opp.StageName, 'Opp should be closed.');
                System.assertEquals(Label.HouseKeeping_OppLosingLossReason, opp.plLossReason__c, 'Opp should have the correct loss reason.');
                System.assertEquals(accOutboundRT, opp.Account.RecordTypeId, 'Account should be in RT Outbound.');
            }
        }
    }
}