force-app/main/default/objects/Account/fields/Competitor_1_current_future__c.field-meta.xml
<CustomField>
    <fullName>Competitor_1_current_future__c</fullName>
    <description>RO-2315</description>
    <inlineHelpText>Welche Rekrutierungslösungen werden derzeit eingesetzt oder für die Zukunft in Betracht gezogen?
Erfasst die Rekrutierungslösungen, die von potenziellen Kunden derzeit genutzt werden oder in der Zukunft in Betracht gezogen werden.</inlineHelpText>
    <label>Competitor 1: current &amp; future</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor_1_current_future__c.field-meta.xml
<CustomField>
    <fullName>Competitor_1_current_future__c</fullName>
    <description>RO-2093</description>
    <inlineHelpText>Welche Rekrutierungslösungen werden derzeit eingesetzt oder für die Zukunft in Betracht gezogen?</inlineHelpText>
    <label>Competitor 1: current &amp; future</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <formula>TEXT(Account.Service_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>RO-715</description>
    <formula>Opportunity.Service_Country__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt. Auf der Quote wird das Service Country des Accounts und der Opportunity angezeigt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

force-app/main/default/globalValueSets/Competitors.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Stepstone</fullName>
    </customValue>
    <customValue>
        <fullName>Indeed</fullName>
    </customValue>
    <customValue>
        <fullName>Karriere.at</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIn</fullName>
    </customValue>
    <customValue>
        <fullName>Xing/onlyfy</fullName>
    </customValue>
    <customValue>
        <fullName>Stellenanzeigen.de</fullName>
    </customValue>
    <customValue>
        <fullName>Talent.com</fullName>
    </customValue>
    <customValue>
        <fullName>Kleinanzeigen</fullName>
    </customValue>
    <customValue>
        <fullName>Agentur für Arbeit</fullName>
    </customValue>
    <customValue>
        <fullName>Monster</fullName>
    </customValue>
    <customValue>
        <fullName>Agentur</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <label>No Competitors</label>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>RO-2093</description>
    <masterLabel>Competitors</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_quoteProcess.cls
@isTest(SeeAllData=true)
public class Test_quoteProcess {

    @IsTest
    static void test_createQuoteLineItems(){
        Test.startTest();
        List<Quote> lstQuote = new List<Quote>();

        Account objAccount = new Account(Name ='TEST Acc for Quote',
                                            Service_Country__c = 'DE',
                                            NumberOfEmployees = 2500,
                                        	Competitor_1_current_future__c = 'None');
        insert objAccount;
        
        
        Product2 objProduct = new Product2(Name = 'Test product1', family = 'Cafe');                                           
        insert objProduct;
        
        // Insert Pricebook
        PriceBook2 customPriceBook = new PriceBook2();
        customPriceBook.Name='Custom Pricebook';
        customPriceBook.IsActive=true;
        insert customPriceBook;
        
        // Query Standard and Custom Price Books
        Pricebook2 customPriceBookRec=[select Id from Pricebook2 where id=:customPriceBook.Id];
        //Id stdPriceBookRecId = Test.getStandardPricebookId();
        Id stdPriceBookRecId = [Select Id,name,isstandard from Pricebook2 Where IsStandard=true].Id;
        
        // Create Standard PriceBookEntry
        PriceBookEntry stdPriceBookEntry = new PriceBookEntry();
        stdPriceBookEntry.Product2Id=objProduct.Id;
        stdPriceBookEntry.Pricebook2Id=stdPriceBookRecId;
        stdPriceBookEntry.UnitPrice=2000;
        stdPriceBookEntry.IsActive=true;
        insert stdPriceBookEntry;
        
        //Create custom PriceBookEntry
        PriceBookEntry objPBE = new PriceBookEntry(UnitPrice = 300, PriceBook2Id = customPriceBookRec.Id,
                                                        Product2Id = objProduct.Id, IsActive = true);
        insert objPBE;
        
        Opportunity objOpp = new Opportunity(Name = 'Test Opp', AccountId = objAccount.Id, StageName = 'Offer', CloseDate = Date.today()+1);
        insert objOpp;
        
        for(Integer i=0; i< 10 ; i++){
            lstQuote.add(new Quote(OpportunityId = objOpp.Id, Name = 'Test Quote' + i, Pricebook2Id = customPriceBookRec.Id, Status = 'Draft'));
        }
        insert lstQuote;
        List<quoteProcess.InputVariables> inputList = new List<quoteProcess.InputVariables>();
        quoteProcess.InputVariables inputVariable = new quoteProcess.InputVariables();
        inputVariable.quoteId = lstQuote[0].Id;
        inputList.add(inputVariable);
      
        
        quoteProcess.createQuoteLineItems(inputList);
        Test.stopTest();
    }
}