force-app/main/default/objects/Account/fields/Competitor_1_current_future__c.field-meta.xml
<CustomField>
    <fullName>Competitor_1_current_future__c</fullName>
    <description>RO-2315</description>
    <inlineHelpText>Welche Rekrutierungslösungen werden derzeit eingesetzt oder für die Zukunft in Betracht gezogen?
Erfasst die Rekrutierungslösungen, die von potenziellen Kunden derzeit genutzt werden oder in der Zukunft in Betracht gezogen werden.</inlineHelpText>
    <label>Competitor 1: current &amp; future</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <inlineHelpText>With the contact email our team can contact via client for questions or to generate a sale</inlineHelpText>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <label>Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <label>Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/txtContactsSalutation__c.field-meta.xml
<CustomField>
    <fullName>txtContactsSalutation__c</fullName>
    <label>Contacts Salutation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <description>Accounts that are in Sales Process (Customer Acquisition, Account Management)</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RO - 2158.</description>
    <inlineHelpText>Zeigt die zuletzt geöffnete Opportunity an, auf der der Kontakt eine Contact Role war.</inlineHelpText>
    <label>Latest Open Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/Onboarding__c.object-meta.xml
<CustomObject>
    <label>Onboarding</label>
    <nameField>
        <label>Onboarding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Onboardings</relationshipLabel>
    <relationshipName>Onboardings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Onboardings</relationshipLabel>
    <relationshipName>Onboardings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Onboardings</relationshipLabel>
    <relationshipName>Onboardings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/txtComments__c.field-meta.xml
<CustomField>
    <fullName>txtComments__c</fullName>
    <label>Comments Hunter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account Tableau Link</description>
    <formula>HYPERLINK(&quot;https://eu-west-1a.online.tableau.com/#/site/heyjobs/views/ClientPerformanceOverview/ClientPerformanceReport?Company%20ID=&quot; &amp;  TEXT(Account.txtCompanyId__c) ,&quot;Tableau Link&quot;)</formula>
    <inlineHelpText>Account Tableau Link</inlineHelpText>
    <label>Tableau Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor_1_current_future__c.field-meta.xml
<CustomField>
    <fullName>Competitor_1_current_future__c</fullName>
    <description>RO-2093</description>
    <inlineHelpText>Welche Rekrutierungslösungen werden derzeit eingesetzt oder für die Zukunft in Betracht gezogen?</inlineHelpText>
    <label>Competitor 1: current &amp; future</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Competitors</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Onboarding__c.field-meta.xml
<CustomField>
    <fullName>Onboarding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Onboarding</label>
    <referenceTo>Onboarding__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/plLossReason__c.field-meta.xml
<CustomField>
    <fullName>plLossReason__c</fullName>
    <description>should be filled to later understand why we lose certain clients</description>
    <inlineHelpText>Jede Opportunity in Stage=&quot;Closed Lost&quot;, also gelostete Opportunity, sollte einen Lost Reason besitzen. Mehr Informationen zu den einzelnen Lost Reasons finden du auf Confluence. 
Eine spätere Analyse warum die Opportunities verloren worden sind, ist nützlich um gegebenenfalls Anpassungen am Sales Prozess oder Produkt vorzunehmen.</inlineHelpText>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currently not hiring</fullName>
            </value>
            <value>
                <fullName>Currently no budget available</fullName>
            </value>
            <value>
                <fullName>Currently no focus jobs</fullName>
            </value>
            <value>
                <fullName>Not happy with price</fullName>
            </value>
            <value>
                <fullName>Not happy with selection of features</fullName>
            </value>
            <value>
                <fullName>Not happy with job performance</fullName>
            </value>
            <value>
                <fullName>Not happy with candidate quality</fullName>
            </value>
            <value>
                <fullName>No need for paid recruiting measures</fullName>
            </value>
            <value>
                <fullName>All contacts are ghosting</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Bankrupt</fullName>
            </value>
            <value>
                <fullName>Dependent on decision at different corporate level</fullName>
            </value>
            <value>
                <fullName>Dependent on ATS integration</fullName>
            </value>
            <value>
                <fullName>Already won in SSSU Process</fullName>
            </value>
            <value>
                <fullName>Duplicate Opportunity</fullName>
            </value>
            <value>
                <fullName>Special Case</fullName>
            </value>
            <value>
                <fullName>Sonderkündigungsrecht used</fullName>
                <label>Sonderkündigungsrecht used (REACH only)</label>
            </value>
            <value>
                <fullName>Admin Only: Opp lost due to inactivity</fullName>
            </value>
            <value>
                <fullName>Admin Only: Clean-Up Sales Funnel</fullName>
            </value>
            <value>
                <fullName>Jobseeker_SSSU_only</fullName>
                <label>(SSSU only) Jobseeker</label>
            </value>
            <value>
                <fullName>Fraudulent_SSSU_only</fullName>
                <label>(SSSU only) Fraudulent</label>
            </value>
            <value>
                <fullName>#N/A​</fullName>
                <isActive>false</isActive>
                <label>#N/A​</label>
            </value>
            <value>
                <fullName>1_No Open Jobs</fullName>
                <isActive>false</isActive>
                <label>1_No Open Jobs</label>
            </value>
            <value>
                <fullName>2_Never paying for recruiting</fullName>
                <isActive>false</isActive>
                <label>2_Never paying for recruiting</label>
            </value>
            <value>
                <fullName>3_Happy with competitor solution (which?)</fullName>
                <isActive>false</isActive>
                <label>3_Happy with competitor solution (which?)</label>
            </value>
            <value>
                <fullName>4_Doing same service inhouse</fullName>
                <isActive>false</isActive>
                <label>4_Doing same service inhouse</label>
            </value>
            <value>
                <fullName>5_TRY CEO MAILING</fullName>
                <isActive>false</isActive>
                <label>5_TRY CEO MAILING</label>
            </value>
            <value>
                <fullName>6_Rejected by HeyJobs (inbound)</fullName>
                <isActive>false</isActive>
                <label>6_Rejected by HeyJobs (inbound)</label>
            </value>
            <value>
                <fullName>7_Not reached after 13 attempts</fullName>
                <isActive>false</isActive>
                <label>7_Not reached after 13 attempts</label>
            </value>
            <value>
                <fullName>8_CleaningOut</fullName>
                <isActive>false</isActive>
                <label>8_CleaningOut</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <formula>TEXT(Account.Service_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Customer Acquisition Deals Subscription</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>RO-715</description>
    <formula>Opportunity.Service_Country__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt. Auf der Quote wird das Service Country des Accounts und der Opportunity angezeigt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

force-app/main/default/globalValueSets/Competitors.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Stepstone</fullName>
    </customValue>
    <customValue>
        <fullName>Indeed</fullName>
    </customValue>
    <customValue>
        <fullName>Karriere.at</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIn</fullName>
    </customValue>
    <customValue>
        <fullName>Xing/onlyfy</fullName>
    </customValue>
    <customValue>
        <fullName>Stellenanzeigen.de</fullName>
    </customValue>
    <customValue>
        <fullName>Talent.com</fullName>
    </customValue>
    <customValue>
        <fullName>Kleinanzeigen</fullName>
    </customValue>
    <customValue>
        <fullName>Agentur für Arbeit</fullName>
    </customValue>
    <customValue>
        <fullName>Monster</fullName>
    </customValue>
    <customValue>
        <fullName>Agentur</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
        <label>No Competitors</label>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <description>RO-2093</description>
    <masterLabel>Competitors</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CloseQuoteTest.cls
@isTest
public class CloseQuoteTest {
    Static Account acc = new Account(
        name = 'test',
        NumberOfEmployees = 2500,
        Service_Country__c = 'DE',
        Contact_Email__c ='test@test.com',
        Contact_First_Name__c ='testF',
        Contact_Last_Name__c = 'testL',
        txtContactsSalutation__c = 'Herr',
        Competitor_1_current_future__c = 'None'
        
    );
    
    Static Opportunity  opp = new Opportunity (
        name = 'test',
        CloseDate = Date.today(),
        StageName= 'Offer',
        plLossReason__c = 'Admin Only: Clean-Up Sales Funnel'
    );
    
   
    Static Contact con = new Contact(
       LastName ='test',
       Email = 'test@test.com'
    );
    
  
    Static Quote q = new Quote (
        name= 'test'
    );
    
    static testMethod void testCloseQuote() {
        insert acc;
        insert con;
        
        opp.AccountId = acc.Id;
        insert opp;
        
        q.OpportunityId = opp.Id;
        insert q;
        q.Status ='Sent';
        update q;
        
        Onboarding__c onb = new Onboarding__c();
        onb.Account__c = q.AccountId;
        onb.Opportunity__c = q.OpportunityId;
        onb.Contact__c = con.Id;
        onb.txtComments__c = 'test';
        insert onb;
        
        opp.Onboarding__c = onb.Id;
        update opp;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(q);
        CloseQuote testCTRL = new CloseQuote(sc);
        testCTRL.getAttachments();
        testCTRL.AddAttachs();
        testCTRL.save();
        
        closeQuoteRejected testCTRLRejected = new closeQuoteRejected(sc);
        testCTRLRejected.save();
        testCTRLRejected.saveComplete();
    }
    
    static testMethod void testCloseQuoteWithoutOnboarding() {
        insert acc;
        insert con;
        
        opp.AccountId = acc.Id;
        insert opp;
        
        q.OpportunityId = opp.Id;
        insert q;
        q.Status ='Sent';
        update q;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(q);
        CloseQuote testCTRL = new CloseQuote(sc);
        testCTRL.fileList = null;
        testCTRL.getAttachments();
        testCTRL.AddAttachs();
        testCTRL.save();
    }
    
    static testMethod void testCloseQuoteWithAttachment() {
        insert acc;
        insert con;
        
        opp.AccountId = acc.Id;
        insert opp;
        
        q.OpportunityId = opp.Id;
        insert q;
        q.Status ='Sent';
        update q;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(q);
        CloseQuote testCTRL = new CloseQuote(sc);
        
        Attachment att = new Attachment();
        att.Name = 'Test Attachment';
        att.Body = Blob.valueOf('Test Body');
        testCTRL.fileList = new List<Attachment>{att};
        
        testCTRL.uploadAttachment();
        testCTRL.save();
    }
}