force-app/main/default/objects/Account/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <inlineHelpText>With the contact email our team can contact via client for questions or to generate a sale</inlineHelpText>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <label>Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <label>Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/plPlannedHires__c.field-meta.xml
<CustomField>
    <fullName>plPlannedHires__c</fullName>
    <label>PlannedHires</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Planned_Hires</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/txtContactsSalutation__c.field-meta.xml
<CustomField>
    <fullName>txtContactsSalutation__c</fullName>
    <label>Contacts Salutation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/plLossReason__c.field-meta.xml
<CustomField>
    <fullName>plLossReason__c</fullName>
    <description>should be filled to later understand why we lose certain clients</description>
    <inlineHelpText>Jede Opportunity in Stage=&quot;Closed Lost&quot;, also gelostete Opportunity, sollte einen Lost Reason besitzen. Mehr Informationen zu den einzelnen Lost Reasons finden du auf Confluence. 
Eine spätere Analyse warum die Opportunities verloren worden sind, ist nützlich um gegebenenfalls Anpassungen am Sales Prozess oder Produkt vorzunehmen.</inlineHelpText>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currently not hiring</fullName>
            </value>
            <value>
                <fullName>Currently no budget available</fullName>
            </value>
            <value>
                <fullName>Currently no focus jobs</fullName>
            </value>
            <value>
                <fullName>Not happy with price</fullName>
            </value>
            <value>
                <fullName>Not happy with selection of features</fullName>
            </value>
            <value>
                <fullName>Not happy with job performance</fullName>
            </value>
            <value>
                <fullName>Not happy with candidate quality</fullName>
            </value>
            <value>
                <fullName>No need for paid recruiting measures</fullName>
            </value>
            <value>
                <fullName>All contacts are ghosting</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Bankrupt</fullName>
            </value>
            <value>
                <fullName>Dependent on decision at different corporate level</fullName>
            </value>
            <value>
                <fullName>Dependent on ATS integration</fullName>
            </value>
            <value>
                <fullName>Already won in SSSU Process</fullName>
            </value>
            <value>
                <fullName>Duplicate Opportunity</fullName>
            </value>
            <value>
                <fullName>Special Case</fullName>
            </value>
            <value>
                <fullName>Sonderkündigungsrecht used</fullName>
                <label>Sonderkündigungsrecht used (REACH only)</label>
            </value>
            <value>
                <fullName>Admin Only: Opp lost due to inactivity</fullName>
            </value>
            <value>
                <fullName>Admin Only: Clean-Up Sales Funnel</fullName>
            </value>
            <value>
                <fullName>Jobseeker_SSSU_only</fullName>
                <label>(SSSU only) Jobseeker</label>
            </value>
            <value>
                <fullName>Fraudulent_SSSU_only</fullName>
                <label>(SSSU only) Fraudulent</label>
            </value>
            <value>
                <fullName>#N/A​</fullName>
                <isActive>false</isActive>
                <label>#N/A​</label>
            </value>
            <value>
                <fullName>1_No Open Jobs</fullName>
                <isActive>false</isActive>
                <label>1_No Open Jobs</label>
            </value>
            <value>
                <fullName>2_Never paying for recruiting</fullName>
                <isActive>false</isActive>
                <label>2_Never paying for recruiting</label>
            </value>
            <value>
                <fullName>3_Happy with competitor solution (which?)</fullName>
                <isActive>false</isActive>
                <label>3_Happy with competitor solution (which?)</label>
            </value>
            <value>
                <fullName>4_Doing same service inhouse</fullName>
                <isActive>false</isActive>
                <label>4_Doing same service inhouse</label>
            </value>
            <value>
                <fullName>5_TRY CEO MAILING</fullName>
                <isActive>false</isActive>
                <label>5_TRY CEO MAILING</label>
            </value>
            <value>
                <fullName>6_Rejected by HeyJobs (inbound)</fullName>
                <isActive>false</isActive>
                <label>6_Rejected by HeyJobs (inbound)</label>
            </value>
            <value>
                <fullName>7_Not reached after 13 attempts</fullName>
                <isActive>false</isActive>
                <label>7_Not reached after 13 attempts</label>
            </value>
            <value>
                <fullName>8_CleaningOut</fullName>
                <isActive>false</isActive>
                <label>8_CleaningOut</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

force-app/main/default/globalValueSets/Planned_Hires.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1-4</fullName>
    </customValue>
    <customValue>
        <fullName>5-9</fullName>
    </customValue>
    <customValue>
        <fullName>10-19</fullName>
    </customValue>
    <customValue>
        <fullName>20-49</fullName>
    </customValue>
    <customValue>
        <fullName>50-99</fullName>
    </customValue>
    <customValue>
        <fullName>100-249</fullName>
    </customValue>
    <customValue>
        <fullName>250-499</fullName>
    </customValue>
    <customValue>
        <fullName>500-1000</fullName>
    </customValue>
    <customValue>
        <fullName>&gt;1000</fullName>
    </customValue>
    <customValue>
        <fullName>250-500</fullName>
        <isActive>false</isActive>
        <label>250-500</label>
    </customValue>
    <customValue>
        <fullName>100-250</fullName>
        <isActive>false</isActive>
        <label>100-250</label>
    </customValue>
    <customValue>
        <fullName>50-100</fullName>
        <isActive>false</isActive>
        <label>50-100</label>
    </customValue>
    <customValue>
        <fullName>10-50</fullName>
        <isActive>false</isActive>
        <label>10-50</label>
    </customValue>
    <masterLabel>Planned Hires</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/closeQuoteRejected.cls
public class closeQuoteRejected  {
    
    public Quote quote {get;set;}    
    public Opportunity opportunity {get;set;}
    public Account account {get;set;}
 
   

    public closeQuoteRejected(ApexPages.StandardController controller) 
    {
        quote     = (Quote) controller.getRecord(); 
        quote = [Select OpportunityId, Opportunity.plLossReason__c, Account.Type,Account.plPlannedHires__c,Account.txtContactsSalutation__c,
                 Account.Contact_First_Name__c, Account.Contact_Last_Name__c,Account.Contact_Email__c from Quote where id=:quote.Id];
      
        opportunity   = new Opportunity();
        opportunity.AccountID         = quote.AccountId;
        opportunity.ID        = quote.OpportunityId;

    
    }
    
    
    public void save()
    {
        saveComplete();
        quote.Status = 'Rejected'; 
   
        update quote.Account;
        update quote.Opportunity;
             update quote;
        
        
 }
  
   
    
    
    public PageReference saveComplete()
    {
        
        return new PageReference('/'+quote.Id);
        
    }
}