force-app/main/default/objects/Account/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <inlineHelpText>With the contact email our team can contact via client for questions or to generate a sale</inlineHelpText>
    <label>Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <label>Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <label>Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/plPlannedHires__c.field-meta.xml
<CustomField>
    <fullName>plPlannedHires__c</fullName>
    <label>PlannedHires</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Planned_Hires</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/txtContactsSalutation__c.field-meta.xml
<CustomField>
    <fullName>txtContactsSalutation__c</fullName>
    <label>Contacts Salutation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/Onboarding__c.object-meta.xml
<CustomObject>
    <label>Onboarding</label>
    <nameField>
        <label>Onboarding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Onboardings</relationshipLabel>
    <relationshipName>Onboardings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Onboardings</relationshipLabel>
    <relationshipName>Onboardings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Onboardings</relationshipLabel>
    <relationshipName>Onboardings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/txtComments__c.field-meta.xml
<CustomField>
    <fullName>txtComments__c</fullName>
    <label>Comments Hunter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account Tableau Link</description>
    <formula>HYPERLINK(&quot;https://eu-west-1a.online.tableau.com/#/site/heyjobs/views/ClientPerformanceOverview/ClientPerformanceReport?Company%20ID=&quot; &amp;  TEXT(Account.txtCompanyId__c) ,&quot;Tableau Link&quot;)</formula>
    <inlineHelpText>Account Tableau Link</inlineHelpText>
    <label>Tableau Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Onboarding__c.field-meta.xml
<CustomField>
    <fullName>Onboarding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Onboarding</label>
    <referenceTo>Onboarding__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

force-app/main/default/globalValueSets/Planned_Hires.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1-4</fullName>
    </customValue>
    <customValue>
        <fullName>5-9</fullName>
    </customValue>
    <customValue>
        <fullName>10-19</fullName>
    </customValue>
    <customValue>
        <fullName>20-49</fullName>
    </customValue>
    <customValue>
        <fullName>50-99</fullName>
    </customValue>
    <customValue>
        <fullName>100-249</fullName>
    </customValue>
    <customValue>
        <fullName>250-499</fullName>
    </customValue>
    <customValue>
        <fullName>500-1000</fullName>
    </customValue>
    <customValue>
        <fullName>&gt;1000</fullName>
    </customValue>
    <customValue>
        <fullName>250-500</fullName>
        <isActive>false</isActive>
        <label>250-500</label>
    </customValue>
    <customValue>
        <fullName>100-250</fullName>
        <isActive>false</isActive>
        <label>100-250</label>
    </customValue>
    <customValue>
        <fullName>50-100</fullName>
        <isActive>false</isActive>
        <label>50-100</label>
    </customValue>
    <customValue>
        <fullName>10-50</fullName>
        <isActive>false</isActive>
        <label>10-50</label>
    </customValue>
    <masterLabel>Planned Hires</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CloseQuote.cls
public with sharing class CloseQuote {
    
    public Quote quote {get;set;}    
    public Onboarding__c onboardingObj {get;set;}
    public Account account {get;set;}
    public Attachment attach {get; set;}
    public List<Attachment> fileList {get; set;}
    public Quote c;
   

    public closeQuote(ApexPages.StandardController controller) 
    {
        attach = new Attachment();
        fileList = new List<Attachment>();
        fileList.add(attach);
        quote     = (Quote) controller.getRecord(); 
         quote = [Select OpportunityId,Opportunity.Onboarding__c ,Account.plPlannedHires__c,Account.txtContactsSalutation__c,
                 Account.Contact_First_Name__c, Account.Contact_Last_Name__c,Account.Contact_Email__c from Quote where id=:quote.Id];
        if(quote.Opportunity.Onboarding__c != null){
            
            onboardingObj = [select Account__c,Opportunity__c,Name,Contact__c,txtComments__c from Onboarding__c where Id =:quote.Opportunity.Onboarding__c];
        }else{
            onboardingObj   = new Onboarding__c();
            onboardingObj.Account__c         = quote.AccountId;
            onboardingObj.Opportunity__c        = quote.OpportunityId;
        }

        c = (Quote) controller.getRecord(); 
    }
    
    
    public List<Attachment> getAttachments(){
      if(fileList == null) 
         fileList = new List<Attachment>();
      return fileList; 
    }
     
     public PageReference AddAttachs() {
        fileList.add(new Attachment());
        return null;
      }
     
    
    public PageReference save()
    {
        update quote.Account;
        upsert onboardingObj;
        quote.Opportunity.Onboarding__c  = onboardingObj.Id;
        update quote.Opportunity;
        
        quote.Status = 'Accepted'; 
        update quote;
        
       
        
        uploadAttachment();
        return new PageReference('/'+quote.Id);
    }
    
    public PageReference uploadAttachment() { 
      
          if(quote != null) {            
               List<Attachment> attachments = new List<Attachment>();                               
                      
                for(Attachment att : fileList)              
                { 
                if(att.name != null && att.body != null)
                attachments.add(new Attachment(parentId = quote.OpportunityId, name = att.name, body = att.body)) ;                
                }
                if(attachments != null){
                   upsert attachments;                 
                }          
          }                    
  
      return new PageReference('/'+quote.Id);      
    }   
    
    
}