force-app/main/default/objects/Account/fields/GTM_Motion_Account__c.field-meta.xml
<CustomField>
    <fullName>GTM_Motion_Account__c</fullName>
    <description>RO - 1958</description>
    <inlineHelpText>Das GTM Motion zeigt an, in welchem Motion (Segment) sich ein Account befindet oder zugeordnet werden sollte. Hier findest du mehr Informationen zu den GTM Motion.</inlineHelpText>
    <label>GTM Motion Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GTM_Motion_values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <description>RO-177</description>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stage_ACM__c.field-meta.xml
<CustomField>
    <fullName>Stage_ACM__c</fullName>
    <defaultValue>&apos;Prospect&apos;</defaultValue>
    <inlineHelpText>Definiert, wo sich der Account derzeit in unserem Verkaufsprozess befindet.
Finde die genauen Stage-Definitionen hier: https://heyjobs.atlassian.net/wiki/spaces/EO/pages/2155217116/Salesforce+Accounts+Definition+und+Use-Case#Account-Lifecycle-Stage</inlineHelpText>
    <label>Account Lifecycle Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage_ACM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Agency_Customer_Sales.recordType-meta.xml
<RecordType>
    <fullName>Agency_Customer_Sales</fullName>
    <active>true</active>
    <description>Used for HeyJob&apos;s agencies&apos; customers</description>
    <label>Agency Customer Sales</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Agency_Sales.recordType-meta.xml
<RecordType>
    <fullName>Agency_Sales</fullName>
    <active>true</active>
    <description>Used for HeyJob&apos;s agencies</description>
    <label>Agency Sales</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Inventory_Partner.recordType-meta.xml
<RecordType>
    <fullName>Inventory_Partner</fullName>
    <active>true</active>
    <description>Used for Inventory Partners that index jobs on our Talent Platform</description>
    <label>Inventory Partner</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Outbound.recordType-meta.xml
<RecordType>
    <fullName>Outbound</fullName>
    <active>true</active>
    <description>Accounts that are in outbound marketing (B2B Marketing)</description>
    <label>Outbound</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <description>Accounts that are in Sales Process (Customer Acquisition, Account Management)</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Lead/fields/OwnerProfile__c.field-meta.xml
<CustomField>
    <fullName>OwnerProfile__c</fullName>
    <formula>Owner:User.Profile.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OwnerProfile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GTM_Motion_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>GTM_Motion_Opportunity__c</fullName>
    <description>RO - 1958</description>
    <inlineHelpText>Das GTM Motion zeigt an, zu welcher Motion (Segment) ein Opportunity gehört. Das Feld wird mit der GTM Motion auf Account aligned, so lange die Opportunity offen ist. Nach dem schließen der Opportunity kann der Wert nicht mehr verändert werden.</inlineHelpText>
    <label>GTM Motion Opportunity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GTM_Motion_values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Creation_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Creation_Trigger__c</fullName>
    <label>Opportunity Creation Trigger</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Origins</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OwnerProfile__c.field-meta.xml
<CustomField>
    <fullName>OwnerProfile__c</fullName>
    <formula>Owner.Profile.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OwnerProfile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/plLossReason__c.field-meta.xml
<CustomField>
    <fullName>plLossReason__c</fullName>
    <description>should be filled to later understand why we lose certain clients</description>
    <inlineHelpText>Jede Opportunity in Stage=&quot;Closed Lost&quot;, also gelostete Opportunity, sollte einen Lost Reason besitzen. Mehr Informationen zu den einzelnen Lost Reasons finden du auf Confluence. 
Eine spätere Analyse warum die Opportunities verloren worden sind, ist nützlich um gegebenenfalls Anpassungen am Sales Prozess oder Produkt vorzunehmen.</inlineHelpText>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currently not hiring</fullName>
            </value>
            <value>
                <fullName>Currently no budget available</fullName>
            </value>
            <value>
                <fullName>Currently no focus jobs</fullName>
            </value>
            <value>
                <fullName>Not happy with price</fullName>
            </value>
            <value>
                <fullName>Not happy with selection of features</fullName>
            </value>
            <value>
                <fullName>Not happy with job performance</fullName>
            </value>
            <value>
                <fullName>Not happy with candidate quality</fullName>
            </value>
            <value>
                <fullName>No need for paid recruiting measures</fullName>
            </value>
            <value>
                <fullName>All contacts are ghosting</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Bankrupt</fullName>
            </value>
            <value>
                <fullName>Dependent on decision at different corporate level</fullName>
            </value>
            <value>
                <fullName>Dependent on ATS integration</fullName>
            </value>
            <value>
                <fullName>Already won in SSSU Process</fullName>
            </value>
            <value>
                <fullName>Duplicate Opportunity</fullName>
            </value>
            <value>
                <fullName>Special Case</fullName>
            </value>
            <value>
                <fullName>Sonderkündigungsrecht used</fullName>
                <label>Sonderkündigungsrecht used (REACH only)</label>
            </value>
            <value>
                <fullName>Admin Only: Opp lost due to inactivity</fullName>
            </value>
            <value>
                <fullName>Admin Only: Clean-Up Sales Funnel</fullName>
            </value>
            <value>
                <fullName>Jobseeker_SSSU_only</fullName>
                <label>(SSSU only) Jobseeker</label>
            </value>
            <value>
                <fullName>Fraudulent_SSSU_only</fullName>
                <label>(SSSU only) Fraudulent</label>
            </value>
            <value>
                <fullName>#N/A​</fullName>
                <isActive>false</isActive>
                <label>#N/A​</label>
            </value>
            <value>
                <fullName>1_No Open Jobs</fullName>
                <isActive>false</isActive>
                <label>1_No Open Jobs</label>
            </value>
            <value>
                <fullName>2_Never paying for recruiting</fullName>
                <isActive>false</isActive>
                <label>2_Never paying for recruiting</label>
            </value>
            <value>
                <fullName>3_Happy with competitor solution (which?)</fullName>
                <isActive>false</isActive>
                <label>3_Happy with competitor solution (which?)</label>
            </value>
            <value>
                <fullName>4_Doing same service inhouse</fullName>
                <isActive>false</isActive>
                <label>4_Doing same service inhouse</label>
            </value>
            <value>
                <fullName>5_TRY CEO MAILING</fullName>
                <isActive>false</isActive>
                <label>5_TRY CEO MAILING</label>
            </value>
            <value>
                <fullName>6_Rejected by HeyJobs (inbound)</fullName>
                <isActive>false</isActive>
                <label>6_Rejected by HeyJobs (inbound)</label>
            </value>
            <value>
                <fullName>7_Not reached after 13 attempts</fullName>
                <isActive>false</isActive>
                <label>7_Not reached after 13 attempts</label>
            </value>
            <value>
                <fullName>8_CleaningOut</fullName>
                <isActive>false</isActive>
                <label>8_CleaningOut</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Customer Acquisition Deals Subscription</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Sales_Transactional.recordType-meta.xml
<RecordType>
    <fullName>Sales_Transactional</fullName>
    <active>true</active>
    <businessProcess>Sales Transactional</businessProcess>
    <description>Customer Acquisition Deals Transactional</description>
    <label>Sales Transactional</label>
</RecordType>

force-app/main/default/globalValueSets/GTM_Motion_values.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Inside Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Subscription New Business</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise New Business</fullName>
    </customValue>
    <customValue>
        <fullName>Subscription Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Agency Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Inventory Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Expansion</fullName>
        <isActive>false</isActive>
        <label>Enterprise Expansion</label>
    </customValue>
    <customValue>
        <fullName>Subscription Expansion</fullName>
        <isActive>false</isActive>
        <label>Subscription Expansion</label>
    </customValue>
    <description>RO - 1958</description>
    <masterLabel>GTM Motion values</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Opportunity_Origins.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1. Lifecycle change: Opportunity Handler</fullName>
    </customValue>
    <customValue>
        <fullName>2. Auto ClosedWon</fullName>
    </customValue>
    <customValue>
        <fullName>3. HeyPaket Auto Close Won</fullName>
    </customValue>
    <customValue>
        <fullName>4. HeyPaket Auto Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>5. SSSU Opportunity Creation</fullName>
    </customValue>
    <customValue>
        <fullName>6. Opportunity Handler: Email Labelling</fullName>
    </customValue>
    <description>To track which Opps created an opportunity</description>
    <masterLabel>Opportunity Origins</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Stage_ACM.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot Lost</fullName>
        <isActive>false</isActive>
        <label>Pilot Lost</label>
    </customValue>
    <customValue>
        <fullName>Restart Hunting</fullName>
        <isActive>false</isActive>
        <label>Restart Hunting</label>
    </customValue>
    <customValue>
        <fullName>Blacklist</fullName>
        <isActive>false</isActive>
        <label>Blacklist</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
        <isActive>false</isActive>
        <label>Expansion</label>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
        <isActive>false</isActive>
        <label>Invalid</label>
    </customValue>
    <customValue>
        <fullName>Offline - Pause</fullName>
        <isActive>false</isActive>
        <label>Offline - Pause</label>
    </customValue>
    <customValue>
        <fullName>Hunting Lost</fullName>
        <isActive>false</isActive>
        <label>Hunting Lost</label>
    </customValue>
    <customValue>
        <fullName>Does not exist anymore</fullName>
        <isActive>false</isActive>
        <label>Does not exist anymore</label>
    </customValue>
    <customValue>
        <fullName>Existing Lost</fullName>
        <isActive>false</isActive>
        <label>Existing Lost</label>
    </customValue>
    <masterLabel>Stage_ACM</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/batchAutoCloseOpps.cls
/*
*      @author Lisa Müller
*      @date   16-Apr-2024
*      @description   Logic to automatically close open opps RO-2036
*
*      Modification Log:
*      ------------------------------------------------------------------------------------
*       Developer                   Date                    Description
*      ------------------------------------------------------------------------------------
*       Lisa Müller                 2024-06-12              RO-2090 Include new Opp RT Transactional with new Stage
*       Varun Subhash               2024-07-12              RO-2146 Updated to exclude opps created via upload and 
*       Varun Subhash               2024-10-22              RO-2265 Excluded Account ownership updates to Lead Gen for Account of GTM Motion Insode Sales
*       Varun Subhash               2024-12-23              RO-2353 Removal of updates on Account
*/
public class batchAutoCloseOpps implements Database.Batchable<sObject> {
    
    // Getting RT & user IDs
    private static final Id oppSalesRT                  =   Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Sales').getRecordTypeId();
    private static final Id oppTransactionalRT          =   Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Sales_Transactional').getRecordTypeId();
    private static final Id accInventoryRT              =   Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Inventory_Partner').getRecordTypeId();
    private static final Id accAgencySalesRT            =   Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agency_Sales').getRecordTypeId();
    private static final Id accAgencyCustomerSalesRT    =   Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Agency_Customer_Sales').getRecordTypeId();
    private static final Id accOutboundRT               =   Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Outbound').getRecordTypeId();
    private static final Id userLeadGenId;
    private static final Integer oppThresholdAge1;
    private static final Integer oppThresholdAge2;
    private static final Date oppThresholdDate1;
    private static final Date oppThresholdDate2;
    private static final String oppLossReason;
    
    static {
        userLeadGenId       =   [SELECT Id FROM User WHERE Name = 'Lead Gen' LIMIT 1].Id;
        oppThresholdAge1    =   Integer.valueOf(Label.HouseKeeping_OppLosingThreshold);
        oppThresholdAge2    =   Integer.valueOf(Label.HouseKeeping_UploadOppLosingThreshold);
        oppThresholdDate1   =   System.today().addDays(-oppThresholdAge1);
        oppThresholdDate2   =   System.today().addDays(-oppThresholdAge2);
        oppLossReason       =   Label.HouseKeeping_OppLosingLossReason;
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator([
            SELECT Id, Record_Type__c,StageName,GTM_Motion_Opportunity__c,CreatedDate,Opportunity_Creation_Trigger__c, AccountId, Account.RecordTypeId, Account.Stage_ACM__c, Account.Record_Type__c,Account.OwnerId,Account.GTM_Motion_Account__c FROM Opportunity WHERE 
                (RecordTypeId = :oppSalesRT OR RecordTypeId = :oppTransactionalRT)
                AND (StageName = 'Not reached yet' OR StageName = 'Qualified Prospect' OR StageName = 'Ready for Sales')
                AND ((Opportunity_Creation_Trigger__c != null AND CreatedDate <= :oppThresholdDate1) OR (Opportunity_Creation_Trigger__c = null AND CreatedDate <= :oppThresholdDate2))
                AND GTM_Motion_Opportunity__c NOT IN ('Enterprise Retention',  'Enterprise Expansion',  'Enterprise New Business')
              AND OwnerProfile__c != 'Large Prospector - External'
                AND Account.RecordTypeId != :accInventoryRT AND Account.RecordTypeId != :accAgencySalesRT AND Account.RecordTypeId != :accAgencyCustomerSalesRT    
            ]);
    }
    
    public void execute(Database.BatchableContext BC, List<Opportunity> opps) {
        List<Opportunity> oppsToUpdate  =   new List<Opportunity>();
        List<Account> acctsToUpdate     =   new List<Account>();
        Map<Id, Account> accountMap     =   new Map<Id, Account>();
               
        for (Opportunity opp : opps) {
            if (opp.Opportunity_Creation_Trigger__c != null && opp.Record_Type__c != 'oppTransactionalRT') {
                // Use oppThresholdDate1 for opportunities where Opportunity_Creation_Trigger__c is not null
                if ((opp.CreatedDate <= oppThresholdDate1)) {
                    opp.StageName     =   'Closed Lost';
                    opp.plLossReason__c =   oppLossReason;
                    oppsToUpdate.add(opp);
                   
                    if (!accountMap.containsKey(opp.AccountId)) {
                        accountMap.put(opp.AccountId, opp.Account);
                    }
                }
            } else {
                
                // Use oppThresholdDate2 for opportunities where Opportunity_Creation_Trigger__c is null
                if ((opp.CreatedDate <= oppThresholdDate2))  {
                    opp.StageName ='Closed Lost';
                    opp.plLossReason__c =   oppLossReason;
                    oppsToUpdate.add(opp);
                    if (!accountMap.containsKey(opp.AccountId)) {
                        accountMap.put(opp.AccountId, opp.Account);
                    }
                }
            }
        }
        System.debug('Account Info>>'+accountMap);
        for (Account acc : accountMap.values()) {
            System.debug('Account Updates>>');
            acc.RecordTypeId    =   accOutboundRT;
            acc.Stage_ACM__c    =   'Prospect';
            System.debug('Account Owner>>'+acc.OwnerId);
            acctsToUpdate.add(acc);
        }
        
        
        // Update records      
        Database.SaveResult[] resultsOpps   =   Database.update(oppsToUpdate, false);
        Database.SaveResult[] resultsAccts  =   Database.update(acctsToUpdate, false);
        // Log errors
        for (Database.SaveResult sr : resultsOpps) {
            if (!sr.isSuccess()) {
                for (Database.Error err : sr.getErrors()) {
                    System.debug('Failed to update Opportunity with ID: ' + sr.getId() + '. The error occurred: ' + err.getStatusCode() + ' - ' + err.getMessage());
                }
            }
        }
        
        for (Database.SaveResult sr : resultsAccts) {
            if (!sr.isSuccess()) {
                for (Database.Error err : sr.getErrors()) {
                    System.debug('Failed to update Account with ID: ' + sr.getId() + '. The error occurred: ' + err.getStatusCode() + ' - ' + err.getMessage());
                }
            }
        }       
        Logger.saveLog();
    }
    
    public void finish(Database.BatchableContext BC) {
    }
}