force-app/main/default/objects/Account/fields/Last_Booking_Generated_Date_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Last_Booking_Generated_Date_Hierarchy__c</fullName>
    <inlineHelpText>Hier wird angezeigt, wann die letzte Opportunity für diesen Kunden gewonnen wurde. Wenn dieses Konto nicht Teil einer Hierarchie ist, werden die direkten Opportunities dieses Kontos berücksichtigt. Wenn dieses Konto eine Hierarchie hat, dann werden alle Opportunities von allen Konten in dieser Hierarchie geprüft.</inlineHelpText>
    <label>Last Booking Generated Date Hierarchy</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ultimate_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Account_ID__c</fullName>
    <formula>CASESAFEID(
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Id )), Parent.Parent.Parent.Parent.Parent.Id, 
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Id, 
IF(NOT(ISBLANK(Parent.Parent.Parent.Id)), Parent.Parent.Parent.Id, 
IF(NOT(ISBLANK(Parent.Parent.Id)), Parent.Parent.Id, 
IF(NOT(ISBLANK(Parent.Id)),Parent.Id, 
Id)))))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ultimate Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Closed_Won__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Closed_Won__c</fullName>
    <description>RO-169</description>
    <formula>IF(
TEXT(StageName) = &apos;Closed Won&apos; &amp;&amp;  NOT(ISBLANK(dateTimestampClosedWonLost__c)), 
    dateTimestampClosedWonLost__c,
			    	null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Timestamp Closed Won</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/batchUpdateLastBookingMade.cls
/*
*      @author Arun Kumar
*      @date   15-Dec-2024
*      @description  
*
*      Modification Log:
*      ------------------------------------------------------------------------------------
*      Developer                       Date                Description
*      ------------------------------------------------------------------------------------
*      
* 
*/
global class batchUpdateLastBookingMade implements Database.Batchable<sObject>, Database.AllowsCallouts {
    global Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, Amount, Timestamp_Closed_Won__c, AccountId, Account.Ultimate_Account_ID__c FROM Opportunity WHERE StageName = \'Closed Won\' AND Timestamp_Closed_Won__c = YESTERDAY AND Amount <> NULL AND Amount > 0';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Opportunity> oppList){
        if(!oppList.isEmpty()){
            List<Account> accountList = new List<Account>();
            Map<Id, Account> ultimateParentMap;
            Map<Id, Account> accountToUpdate = new Map<Id, Account>();
            Set<Id> ultimateAccountIdSet = new Set<Id>();
            
            for(Opportunity opp : oppList){
                ultimateAccountIdSet.add(opp.Account.Ultimate_Account_ID__c);
            }
            
            if(!ultimateAccountIdSet.isEmpty()){
                ultimateParentMap = new Map<Id, Account>([SELECT Id, Last_Booking_Generated_Date_Hierarchy__c
                                                          FROM Account
                                                          WHERE Id IN :ultimateAccountIdSet]);
            }
            
            if(!ultimateParentMap.isEmpty()){
                for(Opportunity opp : oppList){
                    if(ultimateParentMap.containsKey(opp.Account.Ultimate_Account_ID__c)){
                        if((ultimateParentMap.get(opp.Account.Ultimate_Account_ID__c).Last_Booking_Generated_Date_Hierarchy__c == NULL)
                           || (ultimateParentMap.get(opp.Account.Ultimate_Account_ID__c).Last_Booking_Generated_Date_Hierarchy__c != NULL 
                               && ultimateParentMap.get(opp.Account.Ultimate_Account_ID__c).Last_Booking_Generated_Date_Hierarchy__c < opp.Timestamp_Closed_Won__c)
                           || (accountToUpdate.containsKey(opp.Account.Ultimate_Account_ID__c) 
                               && accountToUpdate.get(opp.Account.Ultimate_Account_ID__c).Last_Booking_Generated_Date_Hierarchy__c < opp.Timestamp_Closed_Won__c)
                          ){
                              ultimateParentMap.get(opp.Account.Ultimate_Account_ID__c).Last_Booking_Generated_Date_Hierarchy__c = opp.Timestamp_Closed_Won__c;
                              accountToUpdate.put(opp.Account.Ultimate_Account_ID__c,ultimateParentMap.get(opp.Account.Ultimate_Account_ID__c)); 
                          }
                    }
                }
            }
           
            if(!accountToUpdate.isEmpty()){
                try{
                    update accountToUpdate.values();
                }catch(Exception e){
                    //Add error logging mechanism
                }
            }
        }
    }
    
    global void finish(Database.BatchableContext bc) {
    }
}