force-app/main/default/objects/Account/fields/Segment_V02__c.field-meta.xml
<CustomField>
    <fullName>Segment_V02__c</fullName>
    <description>RO - 1973</description>
    <inlineHelpText>RETIRED</inlineHelpText>
    <label>Segment V02 (reporting only)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Stage_ACM__c.field-meta.xml
<CustomField>
    <fullName>Stage_ACM__c</fullName>
    <defaultValue>&apos;Prospect&apos;</defaultValue>
    <inlineHelpText>Definiert, wo sich der Account derzeit in unserem Verkaufsprozess befindet.
Finde die genauen Stage-Definitionen hier: https://heyjobs.atlassian.net/wiki/spaces/EO/pages/2155217116/Salesforce+Accounts+Definition+und+Use-Case#Account-Lifecycle-Stage</inlineHelpText>
    <label>Account Lifecycle Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage_ACM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Timestamp_Reactivation__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Reactivation__c</fullName>
    <description>This field shows the timestamp of re-visiting this account after the last opp-lost for further contact</description>
    <label>Legacy Timestamp Reactivation</label>
    <summarizedField>Opportunity.Timestamp_Reactivation__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.plLossReason__c</field>
        <operation>notEqual</operation>
        <value>Admin Only: Clean-Up Sales Funnel</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Reactivation__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Reactivation__c</fullName>
    <description>Reactivation timestamp after the opportunity is lost.</description>
    <label>Timestamp Reactivation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Stage_ACM.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Outbound</fullName>
    </customValue>
    <customValue>
        <fullName>Prospect</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Retention</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Pilot Lost</fullName>
        <isActive>false</isActive>
        <label>Pilot Lost</label>
    </customValue>
    <customValue>
        <fullName>Restart Hunting</fullName>
        <isActive>false</isActive>
        <label>Restart Hunting</label>
    </customValue>
    <customValue>
        <fullName>Blacklist</fullName>
        <isActive>false</isActive>
        <label>Blacklist</label>
    </customValue>
    <customValue>
        <fullName>Expansion</fullName>
        <isActive>false</isActive>
        <label>Expansion</label>
    </customValue>
    <customValue>
        <fullName>Invalid</fullName>
        <isActive>false</isActive>
        <label>Invalid</label>
    </customValue>
    <customValue>
        <fullName>Offline - Pause</fullName>
        <isActive>false</isActive>
        <label>Offline - Pause</label>
    </customValue>
    <customValue>
        <fullName>Hunting Lost</fullName>
        <isActive>false</isActive>
        <label>Hunting Lost</label>
    </customValue>
    <customValue>
        <fullName>Does not exist anymore</fullName>
        <isActive>false</isActive>
        <label>Does not exist anymore</label>
    </customValue>
    <customValue>
        <fullName>Existing Lost</fullName>
        <isActive>false</isActive>
        <label>Existing Lost</label>
    </customValue>
    <masterLabel>Stage_ACM</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/batchUpdateStageACM.cls
global class batchUpdateStageACM implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc){
        //String query = 'SELECT NumberOfEmployees, Segment_V02__c FROM Account WHERE Segment_V02__c = NULL';
        String query = 'SELECT AccountId FROM Opportunity WHERE StageName = \'Closed Lost\' AND Timestamp_Reactivation__c <> NULL AND Timestamp_Reactivation__c = TODAY AND Account.Stage_ACM__c = \'Lost\'';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Opportunity> oppList){

        if(!oppList.isEmpty()){
            List<Account> accList = UtilityFunctions.updateStageACMOnReactivation(oppList);
            update accList;
        }
    }

    global void finish(Database.BatchableContext bc) {
    }
}