force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/txtEmailDomain__c.field-meta.xml
<CustomField>
    <fullName>txtEmailDomain__c</fullName>
    <label>Email Domain</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Email_domain__c.field-meta.xml
<CustomField>
    <fullName>Email_domain__c</fullName>
    <label>Email domain</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>Lead_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Lead_Phone__c.field-meta.xml
<CustomField>
    <fullName>Lead_Phone__c</fullName>
    <description>RO-1439</description>
    <label>Lead Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <formula>TEXT(Account.Service_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Country_Lead__c.field-meta.xml
<CustomField>
    <fullName>Service_Country_Lead__c</fullName>
    <label>Service Country Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Timestamp_SSSU_Case__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_SSSU_Case__c</fullName>
    <label>Timestamp SSSU Case</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Domain_Match_on_Lead__c.field-meta.xml
<CustomField>
    <fullName>Domain_Match_on_Lead__c</fullName>
    <label>Domain Match on Lead</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <formula>IF( OR(
CONTAINS(Email, &quot;hotmail&quot;),
CONTAINS(Email, &quot;gmx&quot;),
CONTAINS(Email, &quot;heyjobs&quot;),
CONTAINS(Email, &quot;hj.de&quot;),
CONTAINS(Email, &quot;aol.de&quot;),
CONTAINS(Email, &quot;aol.com&quot;),
CONTAINS(Email, &quot;arcor.de&quot;),
CONTAINS(Email, &quot;freenet.de&quot;),
CONTAINS(Email, &quot;gmail.com&quot;),
CONTAINS(Email, &quot;googlemail.com&quot;),
CONTAINS(Email, &quot;outlook&quot;),
CONTAINS(Email, &quot;yahoo&quot;),
CONTAINS(Email, &quot;icloud.com&quot;),
CONTAINS(Email, &quot;inbox.lv&quot;),
CASE(SUBSTITUTE(Email, LEFT(Email, FIND(&quot;@&quot;, Email)), NULL),
   &quot;t-online.de&quot;, &quot;true&quot;,
   &quot;web.de&quot;, &quot;true&quot;,
   &quot;mail.de&quot;, &quot;true&quot;,
   &quot;mail.com&quot;, &quot;true&quot;,
   &quot;live.de&quot;, &quot;true&quot;,
   &quot;live.com&quot;, &quot;true&quot;,
   &quot;test.de&quot;, &quot;true&quot;,
   &quot;false&quot;)
   = &quot;true&quot;  ),

null,
SUBSTITUTE(Email, LEFT(Email, FIND(&quot;@&quot;, Email)), NULL)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Timestamp_SSSU_HS_Workflow_completed__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_SSSU_HS_Workflow_completed__c</fullName>
    <description>RO-1559</description>
    <label>Timestamp SSSU HS Workflow completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Timestamp_SSSU_lead__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_SSSU_lead__c</fullName>
    <inlineHelpText>This timestamps gets populated when the customer submitted the Self-Service Sign Up Form on our website</inlineHelpText>
    <label>Timestamp SSSU</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LeadUtilityFunctions.cls
/*
 *      @author Arun Kumar
 *      @date   29-Jul-2023
 *      @description   Logic to handle the lead object related functions
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      
 * 
 * 
 */
public with sharing class LeadUtilityFunctions {

    /**
    * @Methodname     : calculateDomainMatchCount
    * @Param          : List<Lead>
    * @Return         : Null
    * @Description    : Performs three functions
    * 1. Call to create SSSU Duplicate case
    * 2. Calculates and updates domain match on lead
    * 3. Convert the lead if domain match is zero
**/
    
    public static void calculateDomainMatchCount(List<Lead> leadList){
        
        Set<String> leadDomainSet = new Set<String>();
        List<Lead> sssuNewLeadList = new List<Lead>();
        List<Lead> domainOnLeadList = new List<Lead>();
        Map<String, Integer> domainVsMatchCountsMap = new Map<String, Integer>();
        
        //Create SSSU Duplicate Cases
        createSSSUDuplicateCase(leadList);
        
        for(Lead ld : leadList){
            if(ld.Email_Domain__c != NULL){
                leadDomainSet.add(ld.Email_Domain__c);
            }
        }
        
        // Fetch accounts with same email domain
        if(!leadDomainSet.isEmpty()){
            for(AggregateResult result : [SELECT txtEmailDomain__c, COUNT(Id) matchCount
                                          FROM Account
                                          WHERE txtEmailDomain__c IN :leadDomainSet
                                          GROUP BY txtEmailDomain__c
                                         ]) {
                                             String domain = (String) result.get('txtEmailDomain__c');
                                             Integer matchCount = (Integer) result.get('matchCount');
                                             domainVsMatchCountsMap.put(domain.toLowerCase(), matchCount);
                                         }
            
            // Identify the matched domains
            for(Lead ld : leadList){
                if (ld.Email_Domain__c != null){
                    if(domainVsMatchCountsMap.containsKey(ld.Email_Domain__c)){
                        ld.Domain_Match_on_Lead__c = domainVsMatchCountsMap.get(ld.Email_Domain__c);
                        domainOnLeadList.add(ld);
                    }else{
                        ld.Domain_Match_on_Lead__c = 0;
                        sssuNewLeadList.add(ld);
                    }
                }
            }  
        }
        
        //Update domain match count on lead
        domainOnLeadList.addAll(sssuNewLeadList);
        if(!domainOnLeadList.isEmpty()){
            try{
                update domainOnLeadList;
            }catch(Exception e){
                System.debug('Error while updating domain match on lead'+e.getStackTraceString());
            }
        }
        
        //Auto convert the leads whose domain match is zero
        if(!sssuNewLeadList.isEmpty()){
            selfserviceLeadConversion.convertLead(sssuNewLeadList);
        }
    }
    
    /**
@Methodname     : createSSSUDuplicateCase
@Param          : List<Lead>
@Return         : Null
@Description    : To create SSSU Duplicate Check case types for eligible signups
**/
    
    public static void createSSSUDuplicateCase(List<Lead> signedUpLeadList){
        List<Case> sssuCaseList = new List<Case>();
        Id caseSSSULeadDuplicateRT = Schema.SObjectType.Case.getRecordTypeInfosByName().get('SSSU Lead Duplicate Case').getRecordTypeId();
        
        for(Lead inputLead : signedUpLeadList){
            if(inputLead.Timestamp_SSSU_lead__c != NULL && inputLead.Timestamp_SSSU_HS_Workflow_completed__c != NULL){
                Case cs = new Case();
                cs.Company_Name__c 			= inputLead.Company;
                cs.Email__c 				= inputLead.Email ;
                cs.Email_domain__c 			= inputLead.Email_Domain__c;
                cs.Lead_Owner__c 			= inputLead.OwnerId;
                cs.Lead_Phone__c 			= inputLead.Phone;
                cs.Lead__c 					= inputLead.Id;
                cs.OwnerId 					= inputLead.OwnerId;
                cs.Priority 				= 'SSSU Duplicate Check';
                cs.RecordTypeId 			= caseSSSULeadDuplicateRT;
                cs.Service_Country_Lead__c 	= inputLead.Service_Country__c;
                cs.Status 					= 'New';
                cs.Subject 					= 'SSSU Lead Duplicate';
                cs.Timestamp_SSSU_Case__c 	= inputLead.Timestamp_SSSU_lead__c;
                sssuCaseList.add(cs);
            }
        }
        
        if(!sssuCaseList.isEmpty()){
            try{
                insert sssuCaseList;
            }catch(Exception e){
                System.debug('Error while creating SSSU Duplicate Case'+e.getStackTraceString());
            }
        }
    }
    
    /**
@Methodname     : domainMatchAndConversionCheck
@Param          : List<Lead>
@Return         : Null
@Description    : To be called from flow to start the domain match and lead conversion
**/
    @InvocableMethod(Label = 'Initiate Domain match and conversion (if applicable)')
    public static void domainMatchAndConversionCheck(List<InputVariables> inputList){
        
        List<Lead> leadInputList = new List<Lead>();
        Lead leadInfo = inputList.get(0).signedLead;
        leadInputList.add(leadInfo);
        calculateDomainMatchCount(leadInputList);
    }
    
    public class InputVariables{
        @InvocableVariable
        public Lead signedLead;
    }
}