force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <description>Accounts that are in Sales Process (Customer Acquisition, Account Management)</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <formula>TEXT(Account.Service_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Customer Acquisition Deals Subscription</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Automatic_Quote_E_Mail__c.field-meta.xml
<CustomField>
    <fullName>Automatic_Quote_E_Mail__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>(Enterprise only) Wenn TRUE (checked) wird beim Ändern des Quote Status auf “Sent” eine Email, die die Quote enthält an den Kontakt geschickt, der in Contact Name hinterlegt ist. 
Mehr informationen findest du hier https://heyjobs.atlassian.net/wiki/spaces/EO/pages/2788294675/Salesforce+Quotes+Definition+und+Use+Case#Automate-Quote-Email-(Enterprise-only)</inlineHelpText>
    <label>Automatic Quote E-Mail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>RO-715</description>
    <formula>Opportunity.Service_Country__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt. Auf der Quote wird das Service Country des Accounts und der Opportunity angezeigt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

force-app/main/default/objects/User/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteTriggerHandlerTest.cls
@isTest 
public class QuoteTriggerHandlerTest {
	@isTest  static void TestMethod1() {
        Account acc = new Account (       
        Name ='Foo',
        NumberOfEmployees = 2500,
        Service_Country__c = 'DE');
        insert acc;
         Id recTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.CloseDate = Date.today().addDays(5);
        opp.StageName = 'offer';
        opp.AccountId = acc.id;
        opp.RecordTypeId = recTypeId;
        insert opp;

		Pricebook2 pb = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true );
			insert pb;
		Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
			insert prod;
		PricebookEntry pbe=new PricebookEntry(unitprice=0.01,Product2Id=prod.Id, Pricebook2Id=Test.getStandardPricebookId(), IsActive= true); 
			 insert pbe;   
        
        User u = [SELECT Id,name FROM User WHERE name LIKE '%Theresa Lehmann%' and IsActive = true limit 1];
       // System.runAs(u) {
            Quote q= new Quote ();
            q.Name= 'Testq';
        	q.OpportunityId= Opp.id;
        	q.BillingStreet= '123';
        	q.BillingCity= 'City';
        	q.BillingPostalCode= '12345';
        	q.Pricebook2Id= pb.id;
        	insert q;
            
            q.Status = 'sent';
        	update q;
        //}
        
	}
    
    @isTest  static void TestMethod2() {
        Account acc = new Account (       
        Name ='Foo',
        NumberOfEmployees = 2500,
        Service_Country__c = 'DE');
        insert acc;
         Id recTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.CloseDate = Date.today().addDays(5);
        opp.StageName = 'offer';
        opp.AccountId = acc.id;
        opp.RecordTypeId = recTypeId;
        insert opp;
        
        contact con = new contact();
        con.FirstName = 'test';
        con.LastName = 'test';
        con.AccountId = acc.id;
        con.Email= 'gagan.madaan@heyjobs.de';
        insert con;

		Pricebook2 pb = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true );
			insert pb;
		Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
			insert prod;
		PricebookEntry pbe=new PricebookEntry(unitprice=0.01,Product2Id=prod.Id, Pricebook2Id=Test.getStandardPricebookId(), IsActive= true); 
			 insert pbe;   
        
        User u = [SELECT Id,name FROM User WHERE name LIKE '%Theresa Lehmann%' and IsActive = true limit 1];
       // System.runAs(u) {
            Quote q= new Quote ();
            q.Name= 'Testq';
        	q.OpportunityId= Opp.id;
        	q.BillingStreet= '123';
        	q.BillingCity= 'City';
        	q.BillingPostalCode= '12345';
        	q.Pricebook2Id= pb.id;
        	q.ContactId = con.id;
        q.Automatic_Quote_E_Mail__c = true;
        	insert q;
            
        	q.Status = 'sent';
        	update q;
        //}
        
	}
}