force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Umbrella_Company__c.field-meta.xml
<CustomField>
    <fullName>Umbrella_Company__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be served as a Parent Account</description>
    <inlineHelpText>Wird verwendet, um einen Salesforce Account als multinationalen Account zu kennzeichnen. Umbrella Companies werden genutzt, um Accounts mit unterschiedlichen Service-Ländern in einer Hierarchie zu kombinieren.</inlineHelpText>
    <label>Umbrella Company</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <formula>TEXT(Account.Service_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/leadConversionValidationHelper.cls
public class leadConversionValidationHelper 
{
    public static void validateLeads(List<Lead> leadList) 
    {
        Map<string,Lead> leadMap = new Map<string,Lead>();
        Set<string> convertedAccIds = new set<string>();
        Set<string> convertedOpportunityIds = new set<string>();
        
        for(lead ld : leadList) 
        {
            if(ld.IsConverted) 
            {
                system.debug('--LEAD-->>'+ld);
                if(ld.Service_Country__c != null) 
                {
                    leadMap.put(ld.id, ld);
                    if(ld.ConvertedAccountId != null) {
                        convertedAccIds.add(ld.ConvertedAccountId);
                    }
                    if(ld.ConvertedOpportunityId != null) {
                        convertedOpportunityIds.add(ld.ConvertedOpportunityId);
                    }
                } else {
                    ld.addError('You have to define a Service Country before you can convert the Lead to an Account.');
                }
            }
        }
        system.debug('--leadMap-->>'+leadMap.size());
        system.debug('--convertedAccIds-->>'+convertedAccIds.size());
        system.debug('--convertedOpportunityIds-->>'+convertedOpportunityIds.size());
        
        if(!leadMap.isEmpty()) 
        {
            Map<string,Account> accMap;
            Map<string,Opportunity> oppMap;
            if(!convertedAccIds.isEmpty()) {
                accMap = new map<string,account>([select id, Service_Country__c, Umbrella_Company__c from account where id in :convertedAccIds]);
            }
            if(!convertedOpportunityIds.isEmpty()) {
                oppMap = new map<string,Opportunity>([select id, Service_Country__c from Opportunity where id in :convertedOpportunityIds]);
            }
            system.debug('---accMap-->>'+accMap);
            system.debug('---oppMap-->>'+oppMap);
            
            for(string ld : leadMap.keySet()) {
                lead leadObj = leadMap.get(ld);
                // Account Validation for Service Country
                if(leadObj.ConvertedAccountId != null && accMap != null && !accMap.isEmpty() && accMap.containsKey(leadObj.ConvertedAccountId)) {
                    if(leadObj.Service_Country__c != accMap.get(leadObj.ConvertedAccountId).Service_Country__c) {
                        leadObj.addError('You can not convert a Lead into an Account when they have different Service Countries.');
                    } else if(accMap.get(leadObj.ConvertedAccountId).Umbrella_Company__c) {
                        // Validation for Account marked as Umbrella Company.
                        leadObj.addError('You can not convert the lead into account with Umbrella company.');
                    }
                }
                // Opportunity validation for Service Country
                else if(leadObj.ConvertedOpportunityId != null && oppMap != null && !oppMap.isEmpty() && oppMap.containsKey(leadObj.ConvertedOpportunityId)) {
                    if(leadObj.Service_Country__c != oppMap.get(leadObj.ConvertedOpportunityId).Service_Country__c) {
                        leadObj.addError('You can not convert a Lead into an Opportunity when they have different Service Countries.');
                    }
                }
            }
        }
    }
}