force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Umbrella_Company__c.field-meta.xml
<CustomField>
    <fullName>Umbrella_Company__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be served as a Parent Account</description>
    <inlineHelpText>Wird verwendet, um einen Salesforce Account als multinationalen Account zu kennzeichnen. Umbrella Companies werden genutzt, um Accounts mit unterschiedlichen Service-Ländern in einer Hierarchie zu kombinieren.</inlineHelpText>
    <label>Umbrella Company</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Backend_access_enabled__c.field-meta.xml
<CustomField>
    <fullName>Backend_access_enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>RO-1639</description>
    <inlineHelpText>Triggering field for BE company + user creation</inlineHelpText>
    <label>Backend access enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Timestamp_SSSU__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_SSSU__c</fullName>
    <inlineHelpText>Zeigt, wann der Kontakt das erst mal das Self Service Sign Up Form auf unserer Webseite ausgefüllt hat.</inlineHelpText>
    <label>Timestamp SSSU</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_ContactTriggerFunctions.cls
@isTest
public class Test_ContactTriggerFunctions {
    
    @isTest static void testcallingBackendForAccess(){
        
        Test.startTest();
        Account acc = new Account();
        acc.Name = 'Test Acc';
        //acc.Umbrella_Company__c = true;
        acc.NumberOfEmployees = 2500;
        acc.Service_Country__c = 'DE';
        insert acc;
        
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.Email = 'testuser@salesforce.de';
        con.AccountId = acc.Id;
        con.Timestamp_SSSU__c = System.today();
        insert con;
        
        con.Backend_access_enabled__c = true;
        update con;
        
        Test.stopTest();
    }

}