force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/dateTimestampClosedWonLost__c.field-meta.xml
<CustomField>
    <fullName>dateTimestampClosedWonLost__c</fullName>
    <label>Timestamp Closed Won/Lost</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Demo_Date__c.field-meta.xml
<CustomField>
    <fullName>Demo_Date__c</fullName>
    <inlineHelpText>Datum, an dem die Demo mit dem Kund*in stattfindet.</inlineHelpText>
    <label>Demo Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hunter__c.field-meta.xml
<CustomField>
    <fullName>Hunter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name der Person, die die Demo hält.</inlineHelpText>
    <label>Demo Hunter</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Head of</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Large</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Small</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Large VP</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Enterprise</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Agency</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>System</value>
        </filterItems>
        <infoMessage>Make sure to choose someone from the German Customer Acquisition team!</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <formula>TEXT(Account.Service_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Demo_Held__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Demo_Held__c</fullName>
    <description>RO-281 Tracks if the Demo took place. Populates by flow in 1 day after the Event&apos;s Start Time and if the Event was not cancelled.</description>
    <label>Timestamp Demo Held</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Demo_Held_Time__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Demo_Held_Time__c</fullName>
    <description>RO-1473</description>
    <label>Timestamp Demo Held-Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Inbound.recordType-meta.xml
<RecordType>
    <fullName>Inbound</fullName>
    <active>false</active>
    <businessProcess>Inbound</businessProcess>
    <description>Legacy - Inbound sales process for SMB pilot business</description>
    <label>Inbound</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/objects/User/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_LocalDemoHeldUpdate.cls
@isTest
public class Test_LocalDemoHeldUpdate {
    @isTest
    static void testUpdateDemoFields() {
        // Create test data - account and opportunity and task records
        Account testAccount = new Account(
            Name = 'Test Account',
            Service_Country__c = 'DE'
        );
        insert testAccount;
        Id sfAdminUserId = [SELECT Id FROM User WHERE Name = 'Salesforce Admin' LIMIT 1].Id;
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Closed Lost',
            dateTimestampClosedWonLost__c = Date.today(),
            Timestamp_Demo_Held__c = null,
            CloseDate = Date.today(),
            AccountId = testAccount.Id,
            OwnerId = sfAdminUserId
        );
        insert testOpportunity;

        Task testTask = new Task(
            Subject = 'Test Call',
            CallType = 'Inbound',
            CallDurationInSeconds = 130,
            WhatId = testOpportunity.Id,
            CreatedDate = DateTime.now().addMinutes(-10),
            OwnerId = sfAdminUserId
        );
        insert testTask;

        // Execute the method being tested
        Test.startTest();
        List<Opportunity> oppListToUpdate = new List<Opportunity>{ testOpportunity };
        LocalDemoHeldUpdate.UpdateDemoFields(oppListToUpdate);
        Test.stopTest();

        // Retrieve the updated Opportunity record and verify the fields
        Opportunity updatedOpportunity = [SELECT Id, Demo_Date__c, Hunter__c, Timestamp_Demo_Held__c, Timestamp_Demo_Held_Time__c FROM Opportunity WHERE Id = :testOpportunity.Id];

        // Assert that the fields have been updated correctly
        System.assertEquals(testTask.CreatedDate.date(), updatedOpportunity.Demo_Date__c, 'Demo_Date__c field not updated correctly.');
        System.assertEquals(testTask.OwnerId, updatedOpportunity.Hunter__c, 'Hunter__c field not updated correctly.');
        System.assertEquals(testTask.CreatedDate.date(), updatedOpportunity.Timestamp_Demo_Held__c, 'Timestamp_Demo_Held__c field not updated correctly.');
        System.assertEquals(testTask.CreatedDate, updatedOpportunity.Timestamp_Demo_Held_Time__c, 'Timestamp_Demo_Held_Time__c field not updated correctly.');
    }

    @isTest
    static void testUpdateDemoFields_NoRelatedCall() {
        // Create test data - account and opportunity without any related calls
        Account testAccount = new Account(
            Name = 'Test Account',
            Service_Country__c = 'DE'
        );
        insert testAccount;
        Id sfAdminUserId = [SELECT Id FROM User WHERE Name = 'Salesforce Admin' LIMIT 1].Id;
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Closed Lost',
            dateTimestampClosedWonLost__c = Date.today(),
            Timestamp_Demo_Held__c = null,
            CloseDate = Date.today(),
            AccountId = testAccount.Id,
            OwnerId = sfAdminUserId
        );
        insert testOpportunity;

        // Execute the method being tested
        Test.startTest();
        List<Opportunity> oppListToUpdate = new List<Opportunity>{ testOpportunity };
        LocalDemoHeldUpdate.UpdateDemoFields(oppListToUpdate);
        Test.stopTest();

        // Retrieve the updated Opportunity record and verify the fields remain unchanged
        Opportunity updatedOpportunity = [SELECT Id, Demo_Date__c, Hunter__c, Timestamp_Demo_Held__c, Timestamp_Demo_Held_Time__c FROM Opportunity WHERE Id = :testOpportunity.Id];

        // Assert that the fields have not been updated
        System.assertEquals(null, updatedOpportunity.Demo_Date__c, 'Demo_Date__c field should remain null.');
        System.assertEquals(null, updatedOpportunity.Hunter__c, 'Hunter__c field should remain null.');
        System.assertEquals(null, updatedOpportunity.Timestamp_Demo_Held__c, 'Timestamp_Demo_Held__c field should remain null.');
        System.assertEquals(null, updatedOpportunity.Timestamp_Demo_Held_Time__c, 'Timestamp_Demo_Held_Time__c field should remain null.');
    }

}