force-app/main/default/objects/Account/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <description>Defines in which country the customer operates.</description>
    <inlineHelpText>Jedes angelegte Unternehmen (Accounts) muss einem Service Country zugewiesen sein. Ausnahmen sind Umbrella Companies. Diese dürfen kein Service Country zugeordnet haben. 

Das Service country definiert in welchem Land der Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Umbrella_Company__c.field-meta.xml
<CustomField>
    <fullName>Umbrella_Company__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be served as a Parent Account</description>
    <inlineHelpText>Wird verwendet, um einen Salesforce Account als multinationalen Account zu kennzeichnen. Umbrella Companies werden genutzt, um Accounts mit unterschiedlichen Service-Ländern in einer Hierarchie zu kombinieren.</inlineHelpText>
    <label>Umbrella Company</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <description>Accounts that are in Sales Process (Customer Acquisition, Account Management)</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <formula>TEXT(Account.Service_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Das Service Country definiert, in welchem Land der zugehörige Account seine operativen Tätigkeiten durchführt.</inlineHelpText>
    <label>Service Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Customer Acquisition Deals Subscription</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/classes/AccountTriggerTest.cls
@isTest
public Class AccountTriggerTest
{    
    Static Account a = new Account(
        Name ='Foo',
        NumberOfEmployees = 2500,
        Service_Country__c = 'DE'
        
    );
    @isTest    
    public static void TestAccount() {
        insert a;
    }
    
    // Gagan
    @isTest static void test_validateUmbrellaCompany() {
        Test.startTest();
        Account acc = new Account();
        acc.Name = 'Test Acc';
        acc.Umbrella_Company__c = true;
        acc.NumberOfEmployees = 2500;
        //acc.Service_Country__c = 'DE';
        insert acc;
        
        /*Id recTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sales').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp';
        opp.CloseDate = Date.today().addDays(5);
        opp.StageName = 'Scheduling';
        opp.AccountId = acc.id;
        opp.RecordTypeId = recTypeId;
        insert opp;*/
        Test.stopTest();
    }
}