force-app/main/default/objects/Lead/fields/Category_1__c.field-meta.xml
<CustomField>
    <fullName>Category_1__c</fullName>
    <label>Category 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Industry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Category_2__c.field-meta.xml
<CustomField>
    <fullName>Category_2__c</fullName>
    <label>Category 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category_1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant &amp; IT</fullName>
            </value>
            <value>
                <fullName>Finance &amp; Insurance</fullName>
            </value>
            <value>
                <fullName>Leisure &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Gastronomy &amp; Tourism</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Real Estate &amp; Building Service</fullName>
            </value>
            <value>
                <fullName>Municipal</fullName>
            </value>
            <value>
                <fullName>Media &amp; Agencies</fullName>
            </value>
            <value>
                <fullName>Transport &amp; Logistics</fullName>
            </value>
            <value>
                <fullName>DIY &amp; Furnishings</fullName>
            </value>
            <value>
                <fullName>Drugstore &amp; Household</fullName>
            </value>
            <value>
                <fullName>Food Stores</fullName>
            </value>
            <value>
                <fullName>Fashion &amp; Lifestyle</fullName>
            </value>
            <value>
                <fullName>Technology &amp; Car</fullName>
            </value>
            <value>
                <fullName>Car Industry &amp; Aircraft Construction</fullName>
            </value>
            <value>
                <fullName>Construction Industry &amp; Steel</fullName>
            </value>
            <value>
                <fullName>Chemical Industry</fullName>
            </value>
            <value>
                <fullName>Electrical Engineering &amp; Medical Technology</fullName>
            </value>
            <value>
                <fullName>Beverage &amp; Tobacco</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>Consumer Goods Manufacturers</fullName>
            </value>
            <value>
                <fullName>Food Industry</fullName>
            </value>
            <value>
                <fullName>Mechanical Engineering</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Category_3__c.field-meta.xml
<CustomField>
    <fullName>Category_3__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1? Stores</fullName>
            </value>
            <value>
                <fullName>1€ Stores</fullName>
            </value>
            <value>
                <fullName>Advertising Agencies</fullName>
            </value>
            <value>
                <fullName>Advertising sales</fullName>
            </value>
            <value>
                <fullName>Agricultural Engineering</fullName>
            </value>
            <value>
                <fullName>Agricultural Machinery</fullName>
            </value>
            <value>
                <fullName>Aircraft manufacturers</fullName>
            </value>
            <value>
                <fullName>Airlines</fullName>
            </value>
            <value>
                <fullName>Airports</fullName>
            </value>
            <value>
                <fullName>Aluminum Plants</fullName>
            </value>
            <value>
                <fullName>Animal Feed</fullName>
            </value>
            <value>
                <fullName>Animal Hospitals</fullName>
            </value>
            <value>
                <fullName>Animal Shelters</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Associations</fullName>
            </value>
            <value>
                <fullName>Auditors</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Auto Parts Trade</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Basic Chemicals</fullName>
            </value>
            <value>
                <fullName>Basketball Teams</fullName>
            </value>
            <value>
                <fullName>Bausparkasse</fullName>
            </value>
            <value>
                <fullName>Bedroom Stores</fullName>
            </value>
            <value>
                <fullName>Beverage Industry</fullName>
            </value>
            <value>
                <fullName>Bicycle Manufacturer</fullName>
            </value>
            <value>
                <fullName>Bio-Stores</fullName>
            </value>
            <value>
                <fullName>Book Publishers</fullName>
            </value>
            <value>
                <fullName>Bookstore</fullName>
            </value>
            <value>
                <fullName>Bowling Center</fullName>
            </value>
            <value>
                <fullName>Hospitals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Demo_Date__c.field-meta.xml
<CustomField>
    <fullName>Demo_Date__c</fullName>
    <label>Initial Demo Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Engagement_Score__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Score__c</fullName>
    <description>RO-1605</description>
    <label>Engagement Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/HeyJobs_Category__c.field-meta.xml
<CustomField>
    <fullName>HeyJobs_Category__c</fullName>
    <inlineHelpText>indicates the industry where the lead works and is necessary to assign it to industry experts in the HeyJobs teams</inlineHelpText>
    <label>HeyJobs - Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>Call center</fullName>
            </value>
            <value>
                <fullName>Headhunter</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>High-End</fullName>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Temporary Employment Agencies</fullName>
            </value>
            <value>
                <fullName>Banking and Insurance</fullName>
            </value>
            <value>
                <fullName>E-commerce</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Hotels</fullName>
                <isActive>false</isActive>
                <label>Hotels</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/MQL_Type_Lead__c.field-meta.xml
<CustomField>
    <fullName>MQL_Type_Lead__c</fullName>
    <description>MQL Types based on Hubspot criteria. Synced from HS to SF Lead and Contact.</description>
    <inlineHelpText>MQL Types based on Marketing definitions. Find details here: https://heyjobs.atlassian.net/wiki/spaces/EOP/pages/3107455666/MQL+to+Demo+Process#MQL-Type</inlineHelpText>
    <label>MQL Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MQL_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Service_Country__c.field-meta.xml
<CustomField>
    <fullName>Service_Country__c</fullName>
    <label>Service Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Timestamp_Latest_MQL_conversion__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Latest_MQL_conversion__c</fullName>
    <description>RO-1700</description>
    <label>Timestamp Latest MQL conversion</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/urlCareerPage__c.field-meta.xml
<CustomField>
    <fullName>urlCareerPage__c</fullName>
    <inlineHelpText>should be filled with the career page URL of the client. Is used afterwards in prospecting to prepare for client meetings</inlineHelpText>
    <label>Career Page</label>
    <type>Url</type>
</CustomField>

force-app/main/default/globalValueSets/MQL_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Type 1</fullName>
    </customValue>
    <customValue>
        <fullName>Type 2</fullName>
    </customValue>
    <customValue>
        <fullName>Type 3</fullName>
    </customValue>
    <description>MQL Types based on Hubspot criteria. Synced from HS to SF Lead and Contact</description>
    <masterLabel>MQL Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_MQLConversionFunction.cls
@isTest
public class Test_MQLConversionFunction {

    @isTest static void testConvertLeadOnInsert() {        
        List<Lead> leadList = new List<Lead>();
        Lead ld = new Lead(
            FirstName = 'Andy',
            LastName = 'Cooper',
            Email = 'a.cooper@planetearth.de',
            Category_1__c = 'Service Provider',
            Category_2__c = 'Health',
            Category_3__c = 'Hospitals',
            Demo_Date__c = Date.today(),
            HeyJobs_Category__c = 'Agency',
            LeadSource = 'Outbound',
            Status = 'Not researched yet',
            City = 'Berlin',
            Country = 'Deutschland',
            Street= 'Sponholzstrasse',
            PostalCode = '10612',
            NumberOfEmployees = 80,
            urlCareerPage__c = 'planetearth.de',
            Company = 'Planet Earth',
            Service_Country__c = 'AT',
            MQL_Type_Lead__c = 'Type 1',
            Timestamp_Latest_MQL_Conversion__c = DateTime.now().addDays(-1)
        );
        leadList.add(ld);
        
        Test.startTest();
        insert leadList;        
        Test.stopTest();
    }
    
    @isTest static void testConvertLeadOnUpdate() {        
        List<Lead> leadList = new List<Lead>();
        Lead ld = new Lead(
            FirstName = 'William',
            LastName = 'Samson',
            Email = 'w.samson@samplers.de',
            Category_1__c = 'Service Provider',
            Category_2__c = 'Health',
            Category_3__c = 'Hospitals',
            Demo_Date__c = Date.today(),
            HeyJobs_Category__c = 'Agency',
            LeadSource = 'Outbound',
            Status = 'Not researched yet',
            City = 'Berlin',
            Country = 'Deutschland',
            Street= 'test',
            PostalCode = '10066',
            NumberOfEmployees = 70,
            urlCareerPage__c = 'samplers.de',
            Company = 'Samplers',
            Service_Country__c = 'AT',
            MQL_Type_Lead__c = 'Type 3',
            Engagement_Score__c = 50,
            Timestamp_Latest_MQL_Conversion__c = DateTime.now().addDays(-2)
        );
        leadList.add(ld);
        
        Test.startTest();
        insert leadList;
        // Updating the engagement score
        List<Lead> updatedLeadList = new List<Lead>([SELECT Engagement_Score__c FROM Lead WHERE MQL_Type_Lead__c = 'Type 3']);
        for(Lead tld : updatedLeadList){
            tld.Engagement_Score__c = 150;
            tld.Timestamp_Latest_MQL_Conversion__c = DateTime.now();
        }
        update updatedLeadList;
        Test.stopTest();
    }
    
    @isTest static void testTimestampLatestMQLConversion() {
        List<Lead> leadList = new List<Lead>();
        Lead ld = new Lead(
            FirstName = 'Alex',
            LastName = 'Johnson',
            Email = 'a.johnson@innovation.de',
            Category_1__c = 'Service Provider',
            Category_2__c = 'Health',
            Category_3__c = 'Hospitals',
            Demo_Date__c = Date.today(),
            HeyJobs_Category__c = 'Agency',
            LeadSource = 'Outbound',
            Status = 'Not researched yet',
            City = 'Berlin',
            Country = 'Deutschland',
            Street= 'Innovationstrasse',
            PostalCode = '10777',
            NumberOfEmployees = 100,
            urlCareerPage__c = 'innovation.de',
            Company = 'Innovation Inc',
            Service_Country__c = 'AT',
            Timestamp_Latest_MQL_Conversion__c = DateTime.now().addHours(-1)
        );
        leadList.add(ld);
        
        Test.startTest();
        insert leadList;
        Test.stopTest();
    }
}