force-app/main/default/objects/Opportunity/fields/dateTimestampClosedWonLost__c.field-meta.xml
<CustomField>
    <fullName>dateTimestampClosedWonLost__c</fullName>
    <label>Timestamp Closed Won/Lost</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Demo_Date__c.field-meta.xml
<CustomField>
    <fullName>Demo_Date__c</fullName>
    <inlineHelpText>Datum, an dem die Demo mit dem Kund*in stattfindet.</inlineHelpText>
    <label>Demo Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hunter__c.field-meta.xml
<CustomField>
    <fullName>Hunter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name der Person, die die Demo hält.</inlineHelpText>
    <label>Demo Hunter</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4 OR 5 OR 6 OR 7</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Head of</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Large</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Small</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Large VP</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Enterprise</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>Agency</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>startsWith</operation>
            <value>System</value>
        </filterItems>
        <infoMessage>Make sure to choose someone from the German Customer Acquisition team!</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Segment_Opp_V02__c.field-meta.xml
<CustomField>
    <fullName>Segment_Opp_V02__c</fullName>
    <description>RO-841</description>
    <inlineHelpText>indicates the size (number of employees) of the opportunity</inlineHelpText>
    <label>Segment Opp V02 (reporting only)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
                <color>#FF99FF</color>
                <label>Small</label>
            </value>
            <value>
                <fullName>Large</fullName>
                <color>#FFCC66</color>
                <label>Large</label>
            </value>
            <value>
                <fullName>Enterprise</fullName>
                <color>#FF6600</color>
                <label>Enterprise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Currently_in_Contact__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Currently_in_Contact__c</fullName>
    <description>Set the Timestamp when Opportunity is in Stage Currently in Contact</description>
    <inlineHelpText>Timestamp when Opportunity was in Stage Currently in Contact</inlineHelpText>
    <label>Timestamp Currently in Contact</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Currently_in_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Currently_in_Contact_Time__c</fullName>
    <description>RO-1473</description>
    <label>Timestamp Currently in Contact-Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Demo_confirmed__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Demo_confirmed__c</fullName>
    <description>Set the Timestamp when Opportunity is in Stage Confirmed</description>
    <inlineHelpText>Timestamp when Opportunity was in Stage Confirmed</inlineHelpText>
    <label>Timestamp Demo confirmed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Demo_Held__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Demo_Held__c</fullName>
    <description>RO-281 Tracks if the Demo took place. Populates by flow in 1 day after the Event&apos;s Start Time and if the Event was not cancelled.</description>
    <label>Timestamp Demo Held</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Demo_Held_Time__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Demo_Held_Time__c</fullName>
    <description>RO-1473</description>
    <label>Timestamp Demo Held-Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Demo_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Demo_Scheduled__c</fullName>
    <description>1st time when Opportunity was in Stage Demo</description>
    <inlineHelpText>1st time when Opportunity was in Stage Demo</inlineHelpText>
    <label>Timestamp Demo Scheduled</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Not_reached_yet__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Not_reached_yet__c</fullName>
    <description>Set the Timestamp when Opportunity is in Stage Not reached yet</description>
    <inlineHelpText>Timestamp when Opportunity was in Stage Not reached yet</inlineHelpText>
    <label>Timestamp Not reached yet</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Not_reached_yet_time__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Not_reached_yet_time__c</fullName>
    <description>RO-1473</description>
    <label>Timestamp Not reached yet-time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Qualified_Prospect__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Qualified_Prospect__c</fullName>
    <description>Set the Timestamp when Opportunity is in Stage Qualified Prospect</description>
    <inlineHelpText>Timestamp when Opportunity was in Stage Qualified Prospect</inlineHelpText>
    <label>Timestamp Qualified Prospect</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Timestamp_Qualified_Prospect_Time__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Qualified_Prospect_Time__c</fullName>
    <description>RO-1473</description>
    <label>Timestamp Qualified Prospect-Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Customer Acquisition Deals Subscription</description>
    <label>Sales</label>
</RecordType>

force-app/main/default/classes/batchLocalDemoHeldUpdate.cls
/*
 *      @author Lisa Müller
 *      @date   25-Jul-2023
 *      @description   RO-1620 Batch Class to perform bulk update of Demo Held Timestamp of lost Local opps 
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      Lisa Müller					11.09.2023				Add Timestamp fields to query
 * 
 * 
 */
global class batchLocalDemoHeldUpdate implements Database.Batchable<sObject>, Database.AllowsCallouts {
    global Database.QueryLocator start(Database.BatchableContext bc){
        Id salesRecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND DeveloperName = 'Sales' LIMIT 1].Id;
        String query = 'SELECT Id, AccountId, OwnerId, CreatedDate, Demo_Date__c, Hunter__c, Timestamp_Demo_Held__c, Timestamp_Demo_Held_Time__c, Timestamp_Not_reached_yet__c, Timestamp_Not_reached_yet_time__c, Timestamp_Qualified_Prospect__c, Timestamp_Qualified_Prospect_Time__c, Timestamp_Currently_in_Contact__c, Timestamp_Currently_in_Contact_Time__c, Timestamp_Demo_Scheduled__c, Timestamp_Demo_confirmed__c FROM Opportunity WHERE RecordTypeId = \'' + salesRecordTypeId + '\' AND StageName = \'Closed Lost\' AND Segment_Opp_V02__c = \'Small\'  AND dateTimestampClosedWonLost__c = TODAY AND Timestamp_Demo_Held__c =NULL ';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Opportunity> oppList){
        if(!oppList.isEmpty() && !Test.isRunningTest()){
            LocalDemoHeldUpdate.UpdateDemoFields(oppList);
        }
    }

    global void finish(Database.BatchableContext bc) {
    }
}