force-app/main/default/objects/Opportunity/fields/HeyPaket_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Start_Date__c</fullName>
    <description>RO-1432</description>
    <inlineHelpText>Startdatum des HeyPakets. Das Datum wird automatisch beim Akzeptieren der Quote aus dem HeyPaket Start Date auf der Quote eingetragen und definiert, wann das HeyPaket aktiviert wird, also ab wann der Kunde das Budget freigeschaltet bekommt.</inlineHelpText>
    <label>HeyPaket Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HeyPaket_Start_Date_reached__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Start_Date_reached__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HeyPaket Start Date reached</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HeyPaket_Status__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Status__c</fullName>
    <description>RO-1432</description>
    <inlineHelpText>Aktueller Status des HeyPakets. 
Active = HeyPaket ist aktiv und wird automatisch zum angegebenen End date verlängert
Inactive = HeyPaket wird nicht verlängert, Account hat kein aktives HeyPaket
Renewed = HeyPaket ist aktiv und die Kündigungsfrist ist abgelaufen. HeyPaket wird zum End date automatisch erneuert
Cancelled = HeyPaket wurde gekündigt, verlängert sich nicht, und hat ab dem End date kein aktives HeyPaket mehr
Scheduled = HeyPaket ist für die Zukunft geplant.</inlineHelpText>
    <label>HeyPaket Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HeyPaket_Type__c.field-meta.xml
<CustomField>
    <fullName>HeyPaket_Type__c</fullName>
    <description>RO-1432</description>
    <inlineHelpText>&quot;HeyPaket-Typ der Opportunity. Mögliche Werte sind: Essential, Advanced, Professional, Ultimate

Mehr Informationen findest du hier https://heyjobs.atlassian.net/wiki/spaces/B2B/pages/2820964365/HeyPakete+bersicht#Leistungen-der-einzelnen-HeyPakete-im-Detail &quot;</inlineHelpText>
    <label>HeyPaket Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Essential</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Ultimate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/batchHeyPaketActivation.cls
/*
 *      @author Arun Kumar
 *      @date   21-Apr-2023
 *      @description   Batch Class to perform bulk activation of HeyPakets
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      
 * 
 */
global class batchHeyPaketActivation implements Database.Batchable<sObject>, Database.AllowsCallouts {
    global Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, Name, AccountId, HeyPaket_Type__c, HeyPaket_Status__c, HeyPaket_Start_Date__c, HeyPaket_Start_Date_reached__c FROM Opportunity WHERE HeyPaket_Status__c = \'Scheduled\' AND HeyPaket_Start_Date__c = TODAY';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Opportunity> oppList){
        if(!oppList.isEmpty() && !Test.isRunningTest()){
            HeyPaketUtility.heypaketActivation(oppList);
        }
    }

    global void finish(Database.BatchableContext bc) {
    }
}