force-app/main/default/objects/Contact/fields/Exclude_from_Outreach__c.field-meta.xml
<CustomField>
    <fullName>Exclude_from_Outreach__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Wenn diese Option auf „TRUE“ gesetzt ist, wird der Kontakt nicht in die Outreach-Kampagnen aufgenommen. Diese Einstellung wird nach 6 Wochen automatisch auf „FALSCH“ gesetzt.</inlineHelpText>
    <label>Exclude from Outreach</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Timestamp_Exclude_from_Outreach__c.field-meta.xml
<CustomField>
    <fullName>Timestamp_Exclude_from_Outreach__c</fullName>
    <inlineHelpText>Zeigt an, wann dieser bestimmte Kontakt für den Ausschluss von Outreach-Kampagnen markiert wurde</inlineHelpText>
    <label>Timestamp Exclude from Outreach</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/batchRevertCampaignExclusion.cls
/*
 *      @author Arun Kumar
 *      @date   28-Mar-2025
 *      @description   Batch Class to make the contacts eligible for Outreach Campaigns after 6 weeks of original exclusion
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      
 * 
 */
global class batchRevertCampaignExclusion implements Database.Batchable<sObject>, Database.AllowsCallouts {
    global Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, Name, Exclude_from_Outreach__c, Timestamp_Exclude_from_Outreach__c  FROM Contact WHERE Exclude_from_Outreach__c = True AND Timestamp_Exclude_from_Outreach__c  < LAST_N_DAYS:42 ORDER BY LastModifiedDate ASC';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Contact> conList){
        if(!conList.isEmpty()){
            for(Contact con : conList){
                con.Exclude_from_Outreach__c = FALSE;
                con.Timestamp_Exclude_from_Outreach__c  = NULL;
            }
            
            try{
                update conList;
            }catch(Exception e){
                Logger.finest('Failed to revert the contacts as eligible for outreach: '+ conList+' '+'The error occurred: '+ e.getMessage());
                Logger.saveLog();
            }
        }
    }

    global void finish(Database.BatchableContext bc) {
    }
}