force-app/main/default/objects/Category3__c/Category3__c.object-meta.xml
<CustomObject>
    <label>Customer Category</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Category Mapping Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category3__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Category3__c/fields/Old_Reference_Clients__c.field-meta.xml
<CustomField>
    <fullName>Old_Reference_Clients__c</fullName>
    <label>Old Reference Clients</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category3__c/fields/Reference_Clients__c.field-meta.xml
<CustomField>
    <fullName>Reference_Clients__c</fullName>
    <label>Reference Clients</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category3__c/fields/Updated__c.field-meta.xml
<CustomField>
    <fullName>Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Category3.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Advertising Agencies</fullName>
    </customValue>
    <customValue>
        <fullName>Advertising sales</fullName>
    </customValue>
    <customValue>
        <fullName>Agricultural Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Agricultural Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>Aircraft manufacturers</fullName>
    </customValue>
    <customValue>
        <fullName>Airlines</fullName>
    </customValue>
    <customValue>
        <fullName>Airports</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminum Plants</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Feed</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Hospitals</fullName>
    </customValue>
    <customValue>
        <fullName>Animal Shelters</fullName>
    </customValue>
    <customValue>
        <fullName>Architects</fullName>
    </customValue>
    <customValue>
        <fullName>Associations</fullName>
    </customValue>
    <customValue>
        <fullName>Auditors</fullName>
    </customValue>
    <customValue>
        <fullName>Car manufacturers</fullName>
    </customValue>
    <customValue>
        <fullName>Car Service</fullName>
    </customValue>
    <customValue>
        <fullName>Car Suppliers</fullName>
    </customValue>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Banks</fullName>
    </customValue>
    <customValue>
        <fullName>Basic Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Basketball Teams</fullName>
    </customValue>
    <customValue>
        <fullName>Bedroom Stores</fullName>
    </customValue>
    <customValue>
        <fullName>Beverage Industry</fullName>
    </customValue>
    <customValue>
        <fullName>Bicycle Manufacturer</fullName>
    </customValue>
    <customValue>
        <fullName>Book Publishers</fullName>
    </customValue>
    <customValue>
        <fullName>Bookstore</fullName>
    </customValue>
    <customValue>
        <fullName>Bowling Center</fullName>
    </customValue>
    <customValue>
        <fullName>Brewery</fullName>
    </customValue>
    <customValue>
        <fullName>Bread Factories</fullName>
    </customValue>
    <customValue>
        <fullName>Breweries</fullName>
    </customValue>
    <masterLabel>Category3</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/batchReferenceClientChanges.cls
/*
 *      @author Arun Kumar
 *      @date   29-Aug-2023
 *      @description   Batch class to retrieve and send accounts for populating the updated X2020_Reference_Clients__c
 *
 *      Modification Log:
 *      ------------------------------------------------------------------------------------
 *      Developer                       Date                Description
 *      ------------------------------------------------------------------------------------
 *      
 * 
 */
global class batchReferenceClientChanges implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, Updated__c, Category__c, Old_Reference_Clients__c, Reference_Clients__c FROM Category3__c WHERE Updated__c = TRUE';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Category3__c> categoryList){
        if(!categoryList.isEmpty()){
            UtilityFunctions.processReferenceClientChanges(categoryList);
        }
    }

    global void finish(Database.BatchableContext bc) {
    }
}